package/libutempter: fix dependencies
Commit 02c818bc5c7a6967a212f12e4caa8ccdfa0b452b forgot to add
dependencies resulting in the following static build failure:

/home/autobuild/autobuild/instance-5/output-1/host/bin/arm-buildroot-linux-uclibcgnueabi-gcc -Wl,-z,relro -Wl,-stats  -static  -shared \
	-Wl,-soname,libutempter.so.0,--version-script=libutempter.map,-z,defs \
	-lc iface.os -o libutempter.so
/home/autobuild/autobuild/instance-5/output-1/host/lib/gcc/arm-buildroot-linux-uclibcgnueabi/12.3.0/../../../../arm-buildroot-linux-uclibcgnueabi/bin/ld: /home/autobuild/autobuild/instance-5/output-1/host/arm-buildroot-linux-uclibcgnueabi/sysroot/lib/libc.a(__uClibc_main.os): in function `__uClibc_fini':
__uClibc_main.c:(.text+0x190): undefined reference to `__fini_array_start'

Fixes:
 - http://autobuild.buildroot.org/results/781ab393455f0e6823b850f474f6fe38b27d8efa

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Adam Duskett <adam.duskett@amarulasolutions.com>
Tested-by: Adam Duskett <adam.duskett@amarulasolutions.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>