package/zeek: add various fixes for gcc >= 13.x
Fixes:
https://autobuild.buildroot.net/results/906/9061a358d5b37d7674fe5498686cecefda6cf51e/

The build error

  ripemd_160.hpp:52:23: error: 'uint8_t' was not declared in this scope

which is fixed by patch 0002, afaics, first occurred on 2024-04-04:
https://autobuild.buildroot.net/results/7ff/7ff3d6a09bd4911ff78e01c14f2bfb7da3d43d60/
so a backport should be considered.

After fixing the build error other build errors occurred which are fixed by
backporting various upstream commits.

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit eb8ee9f7fdd0bddda62e72fa0c5c47f4e1f4b39c)
Signed-off-by: Thomas Perale <thomas.perale@mind.be>