package/ffmpeg: bump to latest commit in 6.1.x branch
Version 6.1.2 of ffmpeg fails to build with GCC 14.x due to the V4L2
ioctl code:

libavdevice/v4l2.c:137:17: error: assignment to ‘int (*)(int,  long unsigned int, ...)’ from incompatible pointer type ‘int (*)(int,  int, ...)’ [-W
incompatible-pointer-types]
  137 |     s->ioctl_f  = prefix ## ioctl;      \
      |                 ^
libavdevice/v4l2.c:151:9: note: in expansion of macro ‘SET_WRAPPERS’
  151 |         SET_WRAPPERS();
      |         ^~~~~~~~~~~~

This has been fixed upstream in the release/6.1 branch, which has 27
fixes on top of 6.1.2. The commits necessary to fix our issue are:

f71076c009f84917e7a0f2f1ece86b718de2d8d3 configure: improve check for POSIX ioctl
60593d6c06c9b610359bd6af26a268feff1293eb configure: restore autodetection of v4l2 and fbdev

However, since all other commits are fixes, we believe bumping to the
latest commit in the release/6.1 branch is a better idea.

This allows to drop
0008-libavcodec-arm-mlpdsp_armv5te-fix-label-format-to-wo.patch, which
is upstream as of:

4c688845a50f7dce3af9afebe60f0f7a493c4f07 libavcodec/arm/mlpdsp_armv5te: fix label format to work with binutils 2.43

Note that we set FFMPEG_CPE_ID_VERSION to get proper CVE matching even
with FFMPEG_VERSION being set to n6.1.2-27-ge16ff06adb. One who have
ideally set FFMPEG_VERSION to n$(FFMPEG_CPE_ID_VERSION)-ge16ff06adb,
but that makes check-package unhappy with:

WARNING: package/ffmpeg/ffmpeg.mk:7: expecting package version to be set before CPE_ID_VERSION

Fixes:

  https://autobuild.buildroot.net/results/fe1574443acd50ca7e576bb4beb24467be1713e3/

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
Signed-off-by: Arnout Vandecappelle <arnout@rnout.be>