package/libcap: needs MMU
libcap uses fork() since version 2.33 and
https://git.kernel.org/pub/scm/linux/kernel/git/morgan/libcap.git/commit/?id=ef485973d5547431782f9e5f4323eabfebb38622

So add MMU dependency to avoid the following build failure on
applications using libcap without MMU such as ntp:

/tmp/instance-0/output-1/host/opt/ext-toolchain/arm-buildroot-uclinux-uclibcgnueabi/bin/ld.real: /tmp/instance-0/output-1/host/bin/../arm-buildroot-uclinux-uclibcgnueabi/sysroot/usr/lib/libcap.a(cap_proc.o): in function `cap_launch':
/tmp/instance-0/output-1/build/libcap-2.42/libcap/cap_proc.c:912: undefined reference to `fork'

All packages that select BR2_PACKAGE_LIBCAP already have a BR2_USE_MMU
dependency, so none of them have to be changed.

Fixes:

 - http://autobuild.buildroot.org/results/89f39dae01c07977062b909079bfcd45a68060d3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>