package/sconeserver: fix build with gcc 4.8
Fix the following build failure with gcc 4.8 raised since commit
8b42bbf30a914b0fd40a4518e61ac7bc511a7deb:

/home/buildroot/autobuild/run/instance-1/output-1/build/sconeserver-8d1935919a2013358993a8e9dfa992cbde56e503/http/AuthRealmDB.cpp: In member function 'virtual std::string http::AuthRealmDB::lookup_hash(const string&)':
/home/buildroot/autobuild/run/instance-1/output-1/build/sconeserver-8d1935919a2013358993a8e9dfa992cbde56e503/http/AuthRealmDB.cpp:93:3: error: 'unique_ptr' is not a member of 'std'
   std::unique_ptr<scx::DbQuery> query(m_db->object()->new_query(
   ^

Fixes:
 - http://autobuild.buildroot.org/results/198c23f1de5cc90efe2d3b4ce053939457e003f7

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>