package/libp11: needs threads
threads are mandatory since bump to version 0.4.12 in commit
86ab91483dcb4b60de8c1daa20e2f42bd95ab5fb and
https://github.com/OpenSC/libp11/commit/4bd92da60a670e3c25d9cb69fca3363f47a225c7:

In file included from eng_back.c:30:
p11_pthread.h:92:2: error: #error Locking not supported on this platform.
   92 | #error Locking not supported on this platform.
      |  ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/22adeb78ec4a807c362e6666825f50db6c0408f7

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>