package/brltty: bump to version 6.8
Commit [1] has made ncurses a requirement for building the package.

The added patches fix the following build errors:

/usr/bin/install -c -d ../../../lib
buildroot/output/host/bin/arm-buildroot-linux-gnueabihf-gcc -shared   -Wl,-export-dynamic -o ../../../lib/libbrlttyxfv.so screen.o -ltinfo
buildroot/output/host/lib/gcc/arm-buildroot-linux-gnueabihf/14.3.0/../../../../arm-buildroot-linux-gnueabihf/bin/ld: cannot find -ltinfo: No such file or directory
collect2: error: ld returned 1 exit status

./unicode.c: In function ‘getTransliteratedCharacter’:
./unicode.c:349:27: error: initialization of ‘iconv_t’ {aka ‘long int’} from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
  349 |   static iconv_t handle = NULL;
      |                           ^~~~

Update README hash:
- v6.8:
  - Update the copyright from 2024 to 2025.
- v6.7:
  - Update the supported braille devices lists.
  - Add support for the HIMS eMotion.
  - Add support for HT's Activator Pro models.
  - Add support for the KGS Next Touch 40.
  - Change the copyright from 2023 to 2024.
  - Document that HT's Basic Braille Plus models are supported.

Release notes:
https://github.com/brltty/brltty/blob/BRLTTY-6.8/Documents/ChangeLog

[1] https://github.com/brltty/brltty/commit/8f7d65569ef77eec8b8e4b97e68cb5689cf57ef9
Signed-off-by: Dario Binacchi <dario.binacchi@amarulasolutions.com>
Signed-off-by: Julien Olivain <ju.o@free.fr>