package/tbb: fix nios2 build
Fix the following build failure on nios2 raised since bump to version
2021.5.0 in commit 3c66ac07a0783b21f95e699b3762edd15e27bdf9:

In file included from /home/giuliobenetti/autobuild/run/instance-2/output-1/build/tbb-2021.5.0/src/tbb/tools_api/ittnotify_static.c:17,
                 from /home/giuliobenetti/autobuild/run/instance-2/output-1/build/tbb-2021.5.0/src/tbb/itt_notify.cpp:43:
/home/giuliobenetti/autobuild/run/instance-2/output-1/build/tbb-2021.5.0/src/tbb/tools_api/ittnotify_config.h: In function 'long int __itt_interlocked_increment(volatile long int*)':
/home/giuliobenetti/autobuild/run/instance-2/output-1/build/tbb-2021.5.0/src/tbb/tools_api/ittnotify_config.h:348:12: error: '__TBB_machine_fetchadd4' was not declared in this scope
  348 |     return __TBB_machine_fetchadd4(ptr, 1) + 1L;
      |            ^~~~~~~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/2b55d1d171f21030be8312f984ea02ec8c8348a8

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>