package/libuhttpd: fix build with wolfssl
Fix the following build failure with wolfssl raised since bump to
version 3.12.1 in commit 4d85defa7103aadc74223868fb83ed0bed144f4d:

/tmp/instance-4/output-1/build/libuhttpd-3.12.1/src/ssl/openssl.c: In function 'ssl_context_new':
/tmp/instance-4/output-1/build/libuhttpd-3.12.1/src/ssl/openssl.c:174:33: error: 'tls13_ciphersuites' undeclared (first use in this function)
  174 |     SSL_CTX_set_ciphersuites(c, tls13_ciphersuites);
      |                                 ^~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/25db1e999950bbee069ba7364a228184a6a77808

Note: we have a reference to a pull request on the 'ssl' repository,
because it is a git submodule of libuhttpd.

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[yann.morin.1998@free.fr: explain the reference to ssl/pull/1]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>