configs/imx8mpevk: select BR2_TARGET_UBOOT_NEEDS_OPENSSL
Select BR2_TARGET_UBOOT_NEEDS_OPENSSL to fix the following build
error:

include/image.h:1394:12: fatal error: openssl/evp.h: No such file or directory
 1394 | #  include <openssl/evp.h>

Fixes: https://gitlab.com/buildroot.org/buildroot/-/jobs/5858180070
Signed-off-by: Fabio Estevam <festevam@gmail.com>
Tested-By: Sébastien Szymanski <sebastien.szymanski@armadeus.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit bce4fe6d1bc8a71918e3d862ebf85d342bf535b0)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>