configs/beelink_gs1: bump to linux 5.15, atf 2.5 and u-boot 2021.10
U-boot libfdt fails to compile on CI.
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status

https://gitlab.com/buildroot.org/buildroot/-/jobs/2021478208

As this fix has been already upstreamed just bump U-boot package.

Let's also bump Kernel and ATF as the board is properly supported upstream.

Signed-off-by: Clément Péron <peron.clem@gmail.com>
Reviewed-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>