package/freescale-imx/imx-gpu-viv: declare as a libgbm provider
Interestingly, only the aarch64 blobs provide libgbm support. This
will help in fixing an issue that exists today, where ARM32 +
imx-gpu-viv + wayland + qt5 fails to build, because qt5 is told that
libgbm is available, i.e the following configuration:

 BR2_arm=y
 BR2_cortex_a9=y
 BR2_ARM_ENABLE_VFP=y
 BR2_TOOLCHAIN_EXTERNAL=y
 BR2_TOOLCHAIN_EXTERNAL_BOOTLIN=y
 BR2_INIT_NONE=y
 BR2_SYSTEM_BIN_SH_NONE=y
 # BR2_PACKAGE_BUSYBOX is not set
 BR2_PACKAGE_QT5=y
 BR2_PACKAGE_QT5BASE_GUI=y
 BR2_PACKAGE_QT5BASE_EGLFS=y
 BR2_PACKAGE_FREESCALE_IMX=y
 BR2_PACKAGE_FREESCALE_IMX_PLATFORM_IMX6Q=y
 BR2_PACKAGE_IMX_GPU_VIV=y
 BR2_PACKAGE_IMX_GPU_VIV_OUTPUT_WL=y
 # BR2_TARGET_ROOTFS_TAR is not set

fails to build during the qt5base configure step with:

ERROR: Feature 'gbm' was enabled, but the pre-condition 'libs.gbm' failed.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>