package/nginx: zone modules need libatomic_ops
ngx_{http,stream}_upstream_zone_module need libatomic_ops since their
addition in commit 621ec32677082d901806338e6f50f03349dceb76 and
https://github.com/nginx/nginx/commit/cf31347ee84fdaa02f768e641d1a2f1352b6a56a
https://github.com/nginx/nginx/commit/79a03b3ff6d950e60a06c6d979bd7a909709e82d:

src/core/ngx_rwlock.c:125:2: error: #error ngx_atomic_cmp_set() is not defined!
  125 | #error ngx_atomic_cmp_set() is not defined!
      |  ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/f7f6be00029d430dc575bc5b3e3e2031cea0460c

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit fb3fbb261b809cf8ce2d9b16984f0dffbc0c1147)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>