package/libwebsockets: fix build without threads
Fix the following build failure without threads raised since bump to
version 4.3.1 in commit 3a9cf51ab38b6a3a095241b8e87eab7e5b5bd617 and
https://github.com/warmcat/libwebsockets/commit/8eca7e17f27c8588170c5fa5fa3e6b14eb90e35d:

In file included from /nvmedata/autobuild/instance-1/output-1/build/libwebsockets-4.3.1/lib/plat/unix/unix-caps.c:28:
/nvmedata/autobuild/instance-1/output-1/build/libwebsockets-4.3.1/lib/core/./private-lib-core.h:68:11: fatal error: pthread.h: No such file or directory
   68 |  #include <pthread.h>
      |           ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/5d011b65e530339eb3f4d06a08caabc6a73b403b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>