qt5base: fix eglfs x11 header related compile failure
Add egl config and QT_EGL_NO_X11 define (as all other eglfs project
files do) to src/plugins/platforms/eglfs/eglfs-plugin.pro.

Fixes ([1]):

  In file included from .../host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot/usr/include/EGL/egl.h:39:0,
                   from ../../../../include/QtEglSupport/5.8.0/QtEglSupport/private/../../../../../src/platformsupport/eglconvenience/qt_egl_p.h:63,
                   from ../../../../include/QtEglSupport/5.8.0/QtEglSupport/private/qt_egl_p.h:1,
                   from api/qeglfsglobal_p.h:56,
                   from api/qeglfsintegration_p.h:54,
                   from qeglfsmain.cpp:41:
  .../host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot/usr/include/EGL/eglplatform.h:119:22: fatal error: X11/Xlib.h: No such file or directory
  compilation terminated.
  Makefile.eglfs-plugin:1024: recipe for target '.obj/qeglfsmain.o' failed
  make[2]: *** [.obj/qeglfsmain.o] Error 1
  make[2]: Leaving directory '.../qt5base-5.8.0/src/plugins/platforms/eglfs'
  Makefile:71: recipe for target 'sub-eglfs-plugin-pro-make_first-ordered' failed
  make[1]: *** [sub-eglfs-plugin-pro-make_first-ordered] Error 2

[1] http://lists.busybox.net/pipermail/buildroot/2017-March/186158.html

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Acked-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
(cherry picked from commit 5840e8bd505cef8846ed4f8fc769f306165ee174)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>