package/glog: needs gcc >= 6
C++14 is mandatory since bump to version 0.7.0 in commit
2e9f161d4a7a68a041860e5855e98bee9d3a1498 and
https://github.com/google/glog/commit/674283420118bb919f83ceb3d9dee31ef43ff3aa
and
https://github.com/google/glog/commit/42a185cd888439d500a35191cd31a605b7c5bd20
resulting in the following build failure with gcc 5:

In file included from /home/buildroot/autobuild/run/instance-2/output-1/build/glog-0.7.0/src/demangle.cc:43:0:
/home/buildroot/autobuild/run/instance-2/output-1/build/glog-0.7.0/src/utilities.h:210:22: error: enclosing class of constexpr non-static member function 'google::glog_internal_namespace_::FileDescriptor::operator bool() const' is not a literal type
   constexpr explicit operator bool() const noexcept {
                      ^

Fixes: 2e9f161d4a7a68a041860e5855e98bee9d3a1498
 - http://autobuild.buildroot.org/results/8d5e105283ead1057545b46726385f4ba4dff29e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>