configs/freescale_imx7dsabresd: Apply upstream U-Boot fix
NXP U-Boot tree has the following build issue:

  MKIMAGE u-boot-dtb.imx
Error: No BOOT_FROM tag in board/freescale/mx7dsabresd/imximage.cfg.cfgtmp
arch/arm/imx-common/Makefile:91: recipe for target 'u-boot-dtb.imx' failed
make[2]: *** [u-boot-dtb.imx] Error 1
Makefile:877: recipe for target 'u-boot-dtb.imx' failed

This issue has been fixed by commit  f916757300c1  ("imx: Create
distinct pre-processed mkimage config files"), so backport this
commit to the NXP U-Boot tree in order to fix the build error.

Fixes:
https://gitlab.com/buildroot.org/buildroot/-/jobs/136980027

Reported-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>

Signed-off-by: Fabio Estevam <festevam@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 98524e573c3d2533d558e042f860c02839e4f6cc)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>