package/freerdp: fix libressl build
Fix the following build failure with libressl raised since bump to
version 2.10.0 in commit 03bab7117d232c9dcd784a74eefc0e48ea51ee53:

/home/thomas/autobuild/instance-3/output-1/build/freerdp-2.10.0/libfreerdp/crypto/crypto.c: In function 'crypto_cert_get_signature_alg':
/home/thomas/autobuild/instance-3/output-1/build/freerdp-2.10.0/libfreerdp/crypto/crypto.c:980:8: error: 'NID_sha3_224' undeclared (first use in this function)
   case NID_sha3_224:
        ^~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/e96848576ac292799636abe7485c37aa54196a2c

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>