package/sg3_utils: bump to version 1.47
- Drop patch (already in version) and so autoreconf
- Update hash of COPYING (upodate in date and author's email:
  https://github.com/doug-gilbert/sg3_utils/commit/f0195003bb0c66ba55084b2f7e0fe982f08c5675)
- Fix the following build failure raised on musl since bump to version
  1.46 in commit a00ed30780819c72174ae959bdd6f15ed961e938:

sg_dd.c: At top level:
sg_dd.c:179:28: error: storage size of 'drand' isn't known
  179 | static struct drand48_data drand;/* opaque, used by srand48_r and mrand48_r */
      |                            ^~~~~

https://github.com/doug-gilbert/sg3_utils/blob/r1.47/ChangeLog

Fixes:
 - http://autobuild.buildroot.org/results/adc20fd52052daadfe1f16ee3f62c30e518cbd16

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>