package/libgcrypt: fix musl build
Fix the following musl build failure raised since bump to version 1.10.0
in commit d96b9ed0738bae270c479bdaf21eebd4c1f9930d:

In file included from ./jitterentropy.h:98,
                 from ./jitterentropy-base.c:32,
                 from ./rndjent.c:88:
./jitterentropy-base-user.h: In function 'jent_get_cachesize':
./jitterentropy-base-user.h:191:8: warning: implicit declaration of function 'open'; did you mean 'popen'? [-Wimplicit-function-declaration]
  191 |   fd = open(file, O_RDONLY);
      |        ^~~~
      |        popen
./jitterentropy-base-user.h:191:19: error: 'O_RDONLY' undeclared (first use in this function)
  191 |   fd = open(file, O_RDONLY);
      |                   ^~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/f6182fca6a4e2ba29a89f770f17df691d7861f8d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>