package/frr: fix elf_py TLS section handling
Fix the following build failure raised on mipsel, or1k, powerpc raised
since bump to version 8.1 in commit
ca2753fd47d47e5ad0eec16ea62f7b7f096331b6:

struct.error: unpack requires a buffer of 20 bytes

Fixes:
 - http://autobuild.buildroot.org/results/74f39c6f14e3f60babdcabceb5e42656f69cdaa7

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>