package/python-cryptography: add host-python-six dependency
Fix the wrong assumption that six is not a dependency with python3 made
in commit 95a63a34ac9204c4fe069154783bd97ed48c3ae2 to avoid the
following build failure with ca-certificates:

Traceback (most recent call last):
  File "/home/buildroot/autobuild/instance-2/output-1/build/ca-certificates-20211016/mozilla/certdata2pem.py", line 31, in <module>
    from cryptography import x509
  File "/home/buildroot/autobuild/instance-2/output-1/host/lib/python3.9/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency
  File "/home/buildroot/autobuild/instance-2/output-1/host/lib/python3.9/site-packages/cryptography/x509/certificate_transparency.py", line 10, in <module>
    import six
ModuleNotFoundError: No module named 'six'

Fixes:
 - http://autobuild.buildroot.org/results/2b6872eec31362bf3edf88c69b67d681b2f016aa

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: James Hilliard <james.hilliard1@gmail.com>
Tested-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>