configs/armadeus_apf51: bump Linux version to 5.10.215
Since the switch to binutils 2.41 as default version [1], the arm Linux
kernel build is broken with:

  arch/arm/mm/proc-v7.S: Assembler messages:
  arch/arm/mm/proc-v7.S:640: Error: junk at end of line, first unrecognized character is `#'

A similar issue has already be fixed for qemu m68k [2].

Bump to the latest kernel 5.10 that already include the backport
of 790756c7e022 ("ARM: 8933/1: replace Sun/Solaris style flag on section directive")

Select BR2_LINUX_KERNEL_NEEDS_HOST_OPENSSL=y to fix the following
build error:

  scripts/extract-cert.c:21:25: fatal error: openssl/bio.h: No such file or directory
  #include <openssl/bio.h>

[1] e88225ed8820881970ec33de7a15a1e0d50443da
[2] a1ce9474e40f731f327035d8c0962abb16f00ff7

Fixes: https://gitlab.com/buildroot.org/buildroot/-/jobs/6655119389

Signed-off-by: Julien BOIBESSOT <julien.boibessot@armadeus.com>
[Romain:
  - improve commit log
  - Select BR2_LINUX_KERNEL_NEEDS_HOST_OPENSSL
]
Signed-off-by: Romain Naour <romain.naour@smile.fr>