package/softhsm2: needs threads
softhsm2 needs threads since the addition of the package in commit
53873b6daecd2a97740833cae7c5b4cdb185a6b2 to avoid the following build
failure:

osmutex.cpp:240:2: error: #error "There are no mutex implementations for your operating system yet"
  240 | #error "There are no mutex implementations for your operating system yet"
      |  ^~~~~

While at it, fix a typo in comment

Fixes:
 - http://autobuild.buildroot.org/results/40a8c2d9f58fbe490b6832754fdf8ac4ee0804fc

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>