package/fluent-bit: bump to version 3.1.3
- Rebase second patch
- This bump will fix the following build failure with gcc >= 14 thanks to
  https://github.com/fluent/fluent-bit/commit/1f8a672dbd8121ff5fbbd955dfbdda7cf4357fd7:

  In file included from /home/autobuild/autobuild/instance-12/output-1/build/fluent-bit-3.0.4/src/tls/flb_tls.c:24:
  /home/autobuild/autobuild/instance-12/output-1/build/fluent-bit-3.0.4/src/tls/openssl.c: In function 'tls_context_server_alpn_select_callback':
  /home/autobuild/autobuild/instance-12/output-1/build/fluent-bit-3.0.4/src/tls/openssl.c:220:40: error: passing argument 1 of 'SSL_select_next_proto' from incompatible pointer type [-Wincompatible-pointer-types]
    220 |         result = SSL_select_next_proto(out,
        |                                        ^~~
        |                                        |
        |                                        const unsigned char **

https://fluentbit.io/announcements/v3.1.3/
https://fluentbit.io/announcements/v3.1.2/
https://fluentbit.io/announcements/v3.1.1/
https://fluentbit.io/announcements/v3.1.0/
https://fluentbit.io/announcements/v3.0.7/
https://fluentbit.io/announcements/v3.0.6/
https://fluentbit.io/announcements/v3.0.5/

Fixes:
 - http://autobuild.buildroot.org/results/8f9fcc0ec9c915a40fe402d7c643fa83f7f6a261

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>