package/qemu: add patches to fix host libc-2.37 compile
- add two upstream patches to fix host libc-2.37 compile
  (see [1], [2] for details)

Fixes:

  In file included from /usr/include/linux/btrfs.h:29,
                   from ../linux-user/syscall.c:163:
  /usr/include/linux/fs.h:50:8: error: redefinition of ‘struct file_clone_range’
     50 | struct file_clone_range {
        |        ^~~~~~~~~~~~~~~~
  ../linux-user/syscall.c:129:8: note: originally defined here
    129 | struct file_clone_range {
        |        ^~~~~~~~~~~~~~~~

[1] https://lists.openembedded.org/g/openembedded-core/message/177322
[2] https://lore.kernel.org/qemu-devel/20230110174901.2580297-1-berrange@redhat.com/

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Reviewed-by: Romain Naour <romain.naour@smile.fr>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit eac0e9cf82b7189b6bb2f2449a68abbcee2651d2)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>