package/x11r7/xdriver_xf86-video-ati: update to the new API/ABI introduced in xserver > 21.0
Fixes:
In file included from radeon_textured_video.c:37:
radeon.h: In function ‘radeon_master_screen’:
radeon.h:187:15: error: ‘struct _Screen’ has no member named ‘current_master’
  187 |     if (screen->current_master)
      |               ^~

The API/ABI have changed in xserver 21.0 due to "some badly named variables/APIs" [1].

[1] https://gitlab.freedesktop.org/xorg/xserver/-/commit/ea47af87f692b291a988834c6f14d73a08cb1d75

Signed-off-by: Romain Naour <romain.naour@gmail.com>
Cc: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>