package/taglib: needs gcc >= 7
Fixes a build error caught by the Gitlab pipelines:

/builds/bkuhls/buildroot/br-test-pkg/bootlin-aarch64-glibc-old/build/taglib-2.3/taglib/mpeg/mpegfile.cpp:113:10:
 error: expected primary-expression before ‘const’
       if(const Header header(&file, headerOffset + i, true); header.isValid()) {

which was introduced by code format changes in upstream commit
https://github.com/taglib/taglib/commit/dfe2aa52532fc9f73a67499dd17fb527a856a22f
which was first released with taglib 2.0, added to buildroot with commit
9cd3464afa13fd0190fb3e94fd850cc8063cf297.

This "init-statement" C++17 language feature was described in proposal
P0305R1, and according to
https://en.cppreference.com/cpp/compiler_support/17, this feature was
only supported in gcc starting from gcc 7.x.

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit d16e4939ca7ca8e0e464230e0b2edbea843e3e3e)
Signed-off-by: Raphaël Mélotte <raphael.melotte@mind.be>