package/libostree: needs headers >= 5.4
linux/fsverity.h is only available since kernel 5.4 and
https://github.com/torvalds/linux/commit/085771ec14b9bdb843fe9283d4703ced395d1b0b
resulting in the following build failure since bump to version 2023.5 in
commit c64a3e9767757f6bab0ecf2df35871508003f39e and
https://github.com/containers/composefs/commit/d3b4b1a2599e74757a3ada47a88645b363067a0a:

composefs/libcomposefs/lcfs-writer-erofs.c:37:10: fatal error: linux/fsverity.h: No such file or directory
   37 | #include <linux/fsverity.h>
      |          ^~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/045987a09cf9061dae80db6ada1f912b2867db26

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>