package/sscep: requires des support in openssl
Enable des in openssl to fix the following build failure raised
since the addition of the package in commit
72fa60dc102679f51b228336ec38f5af78ff7646:

src/sscep.c: In function 'get_cipher_alg':
src/sscep.c:119:32: warning: implicit declaration of function 'EVP_des_ede3_cbc'; did you mean 'NID_des_ede3_cbc'? [-Wimplicit-function-declaration]
  119 |                         return EVP_des_ede3_cbc();
      |                                ^~~~~~~~~~~~~~~~
      |                                NID_des_ede3_cbc

Fixes:
 - http://autobuild.buildroot.net/results/34bd76e8e5e7df0db31918d610a0dadf531f369d

Signed-off-by: Dario Binacchi <dario.binacchi@amarulasolutions.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>