package/frr: disable cunit
Disable cunit to avoid the following build failure raised since bump to
version 8.1 in commit ca2753fd47d47e5ad0eec16ea62f7b7f096331b6 and
https://github.com/FRRouting/frr/commit/749714731ee9a59ae39be77e7db3915ce3ad0bd8:

In file included from pceplib/test/pcep_utils_counters_test.c:33:
./pceplib/pcep_utils_counters.h:112:2: error: unknown type name 'time_t'
  112 |  time_t start_time;
      |  ^~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/b68d3e369e2925938bde39508988aa9b701f1045

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>