package/gdbm: needs wchar
wchar is a mandatoy dependency since bump to version 1.21 in commit
60add404db424e2652673a7b6a3ba2bc80380b42 and
https://git.savannah.gnu.org/cgit/gdbm.git/commit/src/datconv.c?id=0019677be7b751eb2d9b7e9ab25994cb696c7822

datconv.c:18:10: fatal error: wctype.h: No such file or directory
   18 | #include <wctype.h>
      |          ^~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/b35ccdf734a02f0866fba7d86d44a8b452601607

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>