package/gnupg2: bump version to 2.3.8
Brings a number of fixes: https://dev.gnupg.org/T6106

Add patch 0001 to fix undefined reference to `ks_ldap_free_state'
backported from commit 7011286ce6e1fb56c2989fdafbd11b931c489faa

Signed-off-by: Michael Fischer <mf@go-sys.de>
[Peter: add changelog info]
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 73f04f7f0cb5ab7b4df0f2e8c706d73e6d12b793)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>