package/rtl8192eu: bump to 2025-10-13 version on branch 5.11.2.1
This version allows to build with Linux 6.18.

Fixes:

    In file included from core/crypto/sha256.c:11:
    core/crypto/sha256.h:16:5: error: conflicting types for 'hmac_sha256'; have 'int(const u8 *, size_t,  const u8 *, size_t,  u8 *)' {aka 'int(const unsigned char *, long unsigned int,  const unsigned char *, long unsigned int,  unsigned char *)'}

Build failure still not occured in autobuilders.

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
[Julien: add details about the error being fixed]
Signed-off-by: Julien Olivain <ju.o@free.fr>
(cherry picked from commit 9ec337489a399f65df66dbad11317e35e44ef30d)
Signed-off-by: Thomas Perale <thomas.perale@mind.be>