package/davfs2: needs glibc
davfs2 unconditionally uses fstab.h since
https://git.savannah.nongnu.org/cgit/davfs2.git/commit/?id=6e2053cd7f44b0ca58af09905c044c178df34497
resulting in the following build failure since bump to version 1.7.0 in
commit 76423bd3a657f0ca197e2301bbb21e4fc9eee992:

mount_davfs.c:78:10: fatal error: fstab.h: No such file or directory
   78 | #include <fstab.h>
      |          ^~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/793c71e4f731a18e203d6eaa3ac8b6e2a9620c27

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>