package/tar: fix NLS build
Fix the following build failure raised since bump to version 1.35 in
commit d4d483451f0a305781b94b96c15a6cf4b489cd84:

/home/thomas/autobuild/instance-1/output-1/host/lib/gcc/xtensa-buildroot-linux-uclibc/12.3.0/../../../../xtensa-buildroot-linux-uclibc/bin/ld: buffer.o: in function `bufmap_reset':
buffer.c:(.text+0xe8): undefined reference to `libintl_gettext'

Fixes:
 - http://autobuild.buildroot.org/results/99b05d4b495b6337c6a48ea5a551a3a84c6d2e6b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>