package/gtkiostream: fix build with alsa-lib
Select BR2_PACKAGE_ALSA_LIB_MIXER if needed to fix the following build
failure with alsa-lib raised since the addition of the package in commit
fab48302865e5c0c98d91b696bc90e75e38189bb:

In file included from ../include/ALSA/MixerElement.H:20,
                 from ../include/ALSA/Mixer.H:20,
                 from ../include/ALSA/ALSA.H:56,
                 from ALSAControlMonitor.C:19:
../include/ALSA/MixerElementTypes.H:26:5: error: 'snd_mixer_selem_channel_id_t' does not name a type
   26 |     snd_mixer_selem_channel_id_t channel; ///< The ALSA channel ID
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: fab48302865e5c0c98d91b696bc90e75e38189bb
 - http://autobuild.buildroot.org/results/6be71c9fbdccbdf4f5e540bafa748dda833aeedb

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>