package/paxtest: disable on microblaze
Disable paxtest on microblaze to avoid the following build failure:

shlibtest.c:9:1: error: requested alignment '65536' exceeds object file maximum 32768
    9 | char shbss[PAGE_SIZE_MAX] __pagealigned;
      | ^~~~

Updating second patch to set PAGE_SIZE_MAX to 32768 will raise another
build failure:

/tmp/cccMSYDr.s: Assembler messages:
/tmp/cccMSYDr.s: Error: PC relative branch to label buf which is not in the instruction space

Fixes:
 - http://autobuild.buildroot.org/results/aba489143b4017617f67c1012bba1f4687708380

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit abfca98ea223397ed502640d6171845f331614a3)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>