package/multipath-tools: fix path to kernel headers
With change 6b7d47be3b23 ("multipath-tools: Makefiles: simplify code for
include dirs") the Makefile variable 'LINUX_HEADERS_INCDIR' has been replaced
with 'kernel_incdir'.

fpin_handlers.c:355:32: note: each undeclared identifier is reported only once for each function it appears in
fpin_handlers.c:360:37: error: ‘ELS_DTAG_LNK_INTEGRITY’ undeclared (first use in this function)
  360 |                         if (dtag == ELS_DTAG_LNK_INTEGRITY) {
      |                                     ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [../Makefile.inc:116: fpin_handlers.o] Error 1

Fixes:

  http://autobuild.buildroot.net/results/e0f56ef924c13d6b1535fdc350ad8ecc06ea0a58

Signed-off-by: Alexander Egorenkov <egorenar-dev@posteo.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>