package/libostree: needs headers >= 5.8
libostree unconditionally uses loop_config since bump to version 2023.5
in commit c64a3e9767757f6bab0ecf2df35871508003f39e and
https://github.com/containers/composefs/commit/d7f24100c932cd0da9c315de7c7d44fe7a5005cd
which is only available with kernel >= 5.8 and
https://github.com/torvalds/linux/commit/3448914e8cc550ba792d4ccc74471d1ca4293aae
resulting in the following build failure:

composefs/libcomposefs/lcfs-mount.c: In function 'setup_loopback':
composefs/libcomposefs/lcfs-mount.c:273:16: error: variable 'loopconfig' has initializer but incomplete type
  273 |         struct loop_config loopconfig = { 0 };
      |                ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/25d9d4f256861628ddd8e8ce659a39655d27b457
 - http://autobuild.buildroot.org/results/5c7e1e47c6eb43f7832ef7820ec2b5ac0f3c3696

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit aa10975643f6d779ad21ab6ac9595762a93a70f9)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>