package/sconeserver: select libxcrypt if needed
Fix the following build failure raised since bump of glibc to version
2.39 in commit b5680f53d60acf8ff6010082f873438a39bd5d97:

In file included from /home/buildroot/instance-0/output-1/build/sconeserver-8d1935919a2013358993a8e9dfa992cbde56e503/sconex/ScriptBase.h:25,
                 from /home/buildroot/instance-0/output-1/build/sconeserver-8d1935919a2013358993a8e9dfa992cbde56e503/http/AuthRealm.h:26,
                 from /home/buildroot/instance-0/output-1/build/sconeserver-8d1935919a2013358993a8e9dfa992cbde56e503/http/AuthRealm.cpp:23:
/home/buildroot/instance-0/output-1/build/sconeserver-8d1935919a2013358993a8e9dfa992cbde56e503/sconex/sconex.h:124:12: fatal error: crypt.h: No such file or directory
  124 | #  include <crypt.h>
      |            ^~~~~~~~~

Fixes: b5680f53d60acf8ff6010082f873438a39bd5d97
 - http://autobuild.buildroot.org/results/24461bdb0a5d9a062b682ae3aeefa73c0408040b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>