package/cpuload: fix build with gcc >= 14
Fix the following build failure with gcc >= 14:

read_cpu_stat.c: In function 'cpudata_new':
read_cpu_stat.c:49:17: error: implicit declaration of function 'error'; did you mean 'perror'? [-Wimplicit-function-declaration]
   49 |                 error("too many cpus");
      |                 ^~~~~
      |                 perror

Fixes:
 - http://autobuild.buildroot.org/results/3bca2659011d123d7b7a0ca19c4e868643d45766

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit d3e1821cc6496bfab19e4fe3be9fe6223e8f8176)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>