package/s6-linux-utils: fix build with glibc < 2.25
Fix the following build failure with glibc < 2.25 raised since bump to
version 2.6.0.0 in commit 5aac1d0105a73133fd886acc6c5195ca28f7e17f and
https://github.com/skarnet/s6-linux-utils/commit/ad5973028c42d947440cdae5e4f106152c3dda28:

src/minutils/rngseed.c:15:24: fatal error: sys/random.h: No such file or directory
 #include <sys/random.h>
                        ^

Fixes:
 - http://autobuild.buildroot.org/results/214bcecfc389cb412b68627c831300478d614a3a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>
(cherry picked from commit 863811974e04b3332c4959c07a20e3e97050835c)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>