package/duktape: can't be built with BR2_OPTIMIZE_FAST
duktape can't be used with BR2_OPTIMIZE_FAST resulting in the following
build failure in polkit:

In file included from /nvmedata/autobuild/instance-27/output-1/host/aarch64_be-buildroot-linux-gnu/sysroot/usr/include/duktape.h:202,
                 from ../src/polkitbackend/polkitbackendduktapeauthority.c:28:
/nvmedata/autobuild/instance-27/output-1/host/aarch64_be-buildroot-linux-gnu/sysroot/usr/include/duk_config.h:2893:2: error: #error __FAST_MATH__ defined, refusing to compile
 2893 | #error __FAST_MATH__ defined, refusing to compile
      |  ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/587485bcfd85dfd974608aa00b9bd0c42a3a61d8

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit c1dcf18c8d227067bea58e12d30324515e29193b)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>