package/openocd: fix build with libgpiod2
openocd is not compatible with libgpiod2 resulting in the following
build failure since the addition of libgpiod2 in commit
57391fad2e619395340b81957ddceab1b1df2e20:

src/jtag/drivers/linuxgpiod.c: In function 'helper_get_line':
src/jtag/drivers/linuxgpiod.c:283:19: error: 'GPIOD_LINE_REQUEST_DIRECTION_INPUT' undeclared (first use in this function); did you mean 'GPIOD_LINE_DIRECTION_INPUT'?
  283 |         int dir = GPIOD_LINE_REQUEST_DIRECTION_INPUT, flags = 0, val = 0, retval;
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   GPIOD_LINE_DIRECTION_INPUT

Fixes: 57391fad2e619395340b81957ddceab1b1df2e20
 - http://autobuild.buildroot.org/results/7195e8b76350f26ab3b963702d88b254512e6928

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit be3252fe01f39f8ac21d611861bd0c5dda58b09f)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>