package/tpm2-openssl: bump version to 1.3.0
https://github.com/tpm2-software/tpm2-openssl/releases/tag/1.3.0

Update license hash due to copyright year bump:
https://github.com/tpm2-software/tpm2-openssl/commit/3fb3a5ff7fcd9921ad6e933aed8f34e8e63d46db

Pass -Wno-error to make sure warnings are not treated as errors, to
workaround the fact that -Werror is pasedd by the build system since
upstream commit
https://github.com/tpm2-software/tpm2-openssl/commit/c3a8758cad1520d36d6cb87aa87ff8012f3283d8
first included in this release.

This fixes a build error seen with the Gitlab pipelines for
bootlin-aarch64-glibc-old:

src/tpm2-provider-encoder.c:
 In function ‘tpm2_rsa_encoder_encode_SubjectPublicKeyInfo_der’:
 src/tpm2-provider-encoder.c:86:71: error: the comparison will always  evaluate as ‘true’ for the address of ‘tpm2_rsa_encode_public_
SubjectPublicKeyInfo_der’ will never be NULL [-Werror=address]

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>