package/fbv: fix build with giflib and gcc >= 10
Fix the following build failure with giflib and gcc >= 10:

/nvmedata/autobuild/instance-30/output-1/per-package/fbv/host/bin/../lib/gcc/powerpc-buildroot-linux-uclibc/11.3.0/../../../../powerpc-buildroot-linux-uclibc/bin/ld: gif.o: in function `fh_gif_load':
gif.c:(.text+0x338): undefined reference to `m_rend_gif_decodecolormap'

Fixes:
 - http://autobuild.buildroot.org/results/dca603a61b1fd0558992b4a40152d23b5b9c0049

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 9eeb5cd96dcfb6b579eb745ee5f7e76fcdc51251)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>