package/libp11: select BR2_PACKAGE_LIBOPENSSL_ENGINES
libp11 unconditionally calls the (deprecated) ENGINE_* logic in
libopenssl resulting in a build failure when
!BR2_PACKAGE_LIBOPENSSL_ENGINES since commit
623d3bbe43e9193aa8e3395367d01af59071b859:

eng_front.c:25:2: error: #error did not get engine.h
   25 | #error did not get engine.h
      |  ^~~~~

Fixes: 623d3bbe43e9193aa8e3395367d01af59071b859
 - http://autobuild.buildroot.org/results/b03cc27a60f9e6794b3341517196fbf8dc3ec2d4

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>