package/opensc: requires RIPEMD160 in openssl
Enable RIPEMD160 in openssl to avoid the following build failure raised
since the addition of the package in commit
8aaa7ecbce1d10cbcd880c3da5e429988f96176a:

/nvmedata/autobuild/instance-17/output-1/host/lib/gcc/sparc-buildroot-linux-uclibc/10.3.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: pkcs11_tool-pkcs11-tool.o: in function `sign_verify_openssl.constprop.0':
pkcs11-tool.c:(.text+0x6b00): undefined reference to `EVP_ripemd160'

Fixes:
 - http://autobuild.buildroot.org/results/6dc5baa2cfb037431b9ede9f2e0c5705957ee3bf

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>