package/gensio: link with -latomic if needed
Link with -latomic if needed to avoid the following build failure since
bump to version 2.0.1 in commit 0f8d4a6ecd874770ce677b617b2c7f459eb1505d
and
https://github.com/cminyard/gensio/commit/5528267b54ac5a8ac0ecd7fd9ba481d654b0e92b:

/tmp/instance-0/output-1/per-package/gensio/host/opt/ext-toolchain/bin/../lib/gcc/sparc-buildroot-linux-uclibc/9.3.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: ../lib/.libs/libgensio.so: undefined reference to `__atomic_fetch_add_4'

Fixes:
 - http://autobuild.buildroot.org/results/2114f9cb3d820fc620932e793f53341a0c1f10bc
 - http://autobuild.buildroot.org/results/c1b397eea1c2eda19149844cec4a87d55651862d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 92f367b474e4bb6e9d2222abe631ee43465f8780)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>