package/drbd-utils: drbdmon needs sync_1
Buildroot commit 99585db1e896d7a75e204335af86f0725a30d357 bumped the
package from version 9.21.4 to 9.33.0.

Upstream added std::atomic to drbdmon with commit
https://github.com/LINBIT/drbd-utils/commit/3baf945732fc144043822b50a2a03daad0994d44
to version 9.25.0 causing build errors:

/home/autobuild/autobuild/instance-2/output-1/per-package/drbd-utils/host/bin/../lib/gcc/microblazeel-buildroot-linux-uclibc/14.3.0/../../../../microblazeel-buildroot-linux-uclibc/bin/ld:
 MessageLogNotification.o: in function `MessageLogNotification::query_log_changed()':
 (.text+0xe8): undefined reference to `__atomic_exchange_1'

Fixes:
https://autobuild.buildroot.net/results/741/741606000c26bc994f243b0b865d26ff25592caa/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>