package/icu: needs gcc >= 4.9 and host gcc >= 4.9
icu uses std::max_align_t since version 67-1 and
https://github.com/unicode-org/icu/commit/a3078fb8c89b61c35ccebb04cf6b189bc81093b3

This raises the following build failure with gcc 4.8:

utext.cpp:572:5: error: 'max_align_t' in namespace 'std' does not name a type
     std::max_align_t    extension;
     ^

This build failure is due to GCC bug 56019:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56019

Instead of adding BR2_TOOLCHAIN_HAS_GCC_BUG_56019, just bumps gcc
dependency from 4.8 to 4.9

As this issue also affects host-icu, add a host gcc >= 4.9 dependency

Fixes:
 - http://autobuild.buildroot.org/results/6d2658a3c165c99df3eae87b2970e738bd386245
 - http://autobuild.buildroot.org/results/d204f1a528765d1440620a1eed8c29cbb5ec93c3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>