package/python-sentry-sdk: drop asyncio files for python 2.x to fix pycompile issue
sentry-sdk has a set of optional "integrations", some of which use asyncio.

pycompile unfortunately errors out on these files when running under Python
2.x:

../scripts/pycompile.py ..
error:   File "/usr/lib/python2.7/site-packages/sentry_sdk/integrations/sanic.py", line 64
    async def sentry_handle_request(self, request, *args, **kwargs):
            ^
SyntaxError: invalid syntax

As a workaround, simply drop the unusable files from TARGET_DIR if building
for python 2.x.

Fixes:
http://autobuild.buildroot.net/results/9e4/9e47ee2a56153379e4e7bc839be5972a2302ba9f/

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit d62f0042e85c8a39608dc7ad6a491460791dfbfa)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>