package/espflash: bump v3.1.1
Fix the following error:

error[E0282]: type annotations needed for `Box<_>`

The issue came from the `time` library depedency of espflash
(see https://github.com/time-rs/time/issues/693).
The `time` library has been bumped in the following commit
https://github.com/esp-rs/espflash/commit/233490736646ca7bc29463a98df98d7ccf53439d

Fixes:
  - https://autobuild.buildroot.org/results/321/321598baef543b84ce82c09a88e51ad745a15dfd/

Signed-off-by: Thomas Perale <thomas.perale@mind.be>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>