package/pcsc-lite: needs gcc >= 4.9
gcc >= 4.9 is needed since bump to version 1.9.6 in commit
b02f13cd54912f3dffd0e0863378050104430d77 and
https://github.com/LudovicRousseau/PCSC/commit/d56ed18dbebc4423506ce7f61d3e3bcf4bdc4cb0:

In file included from winscard_clnt.c:123:0:
readerfactory.h:101:3: error: unknown type name '_Atomic'
   _Atomic DWORD dwEventStatus; /**< Recent event that must be sent */
   ^

Fixes:
 - http://autobuild.buildroot.org/results/189f030a2252f17abf8b819feec0003815c66e79

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>