package/diffutils: bump version to 3.12
Release notes:
Version 3.12 - https://lists.gnu.org/archive/html/info-gnu/2025-04/msg00005.html
Version 3.11 - https://lists.gnu.org/archive/html/info-gnu/2025-02/msg00003.html

Fix the following error seen during cross-compilation error by assuming that
strcasecmp function is always available.
- "configure: error: cannot run test program while cross compiling"

Signed-off-by: Kadambini Nema <kadambini.nema@gmail.com>
Signed-off-by: Julien Olivain <ju.o@free.fr>