package/sscep: requires blowfish support in openssl
Enable blowfish in openssl to fix the following build failure raised
since the addition of the package in commit
72fa60dc102679f51b228336ec38f5af78ff7646:

src/sscep.c: In function 'get_cipher_alg':
src/sscep.c:123:24: warning: implicit declaration of function 'EVP_bf_cbc'; did you mean 'EVP_sm4_cbc'? [-Wimplicit-function-declaration]
  123 |                 return EVP_bf_cbc();
      |                        ^~~~~~~~~~
      |                        EVP_sm4_cbc

Fixes:
 - http://autobuild.buildroot.org/results/55d2c481d8c148fb3bb61c1331340bcd71274553

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Dario Binacchi <dario.binacchi@amarulasolutions.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>