package/tftpd: bump to latest git commit
Fixes the following error when compiled against GCC 14.x:

tftp.c: In function ‘tftp_sendfile’:
tftp.c:88:5: error: implicit declaration of function ‘bsd_signal’; did
you mean ‘ssignal’? [-Wimplicit-function-declaration]
   88 |     bsd_signal(SIGALRM, timer);
      |     ^~~~~~~~~~
      |     ssignal
tftp.c:88:5: warning: nested extern declaration of ‘bsd_signal’ [-Wnested-externs]
main.c: In function ‘main’:
main.c:308:5: error: implicit declaration of function ‘bsd_signal’;
did you mean ‘ssignal’? [-Wimplicit-function-declaration]
  308 |     bsd_signal(SIGINT, intr);
      |     ^~~~~~~~~~
      |     ssignal
main.c:308:5: warning: nested extern declaration of ‘bsd_signal’ [-Wnested-externs]

Remove an upstreamed patch.

tftpd/tftpd.c has changed, hence, change its checksum.

Signed-off-by: Yegor Yefremov <yegorslists@googlemail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>
(cherry picked from commit ee2b57e0c98acf1d02cf66a38c9ec82bd69bcbeb)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>