package/strace: needs headers >= 5.1
Buildroot commit aa5e3eec6384cb73d902a4de3fffc279683ea5a5 bumped the
package to version 7.0 which includes commit
https://github.com/strace/strace/commit/33b950714a966bde816a1f1e75c127c3d3ae53cd
that adds an include of linux/time_types.h.

This header file was added in linux kernel version 5.1:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=ca5e9aba753ed15d173c7a7b88e4d402b7ca8121

Fixes build errors:

In file included from ../bundled/linux/include/uapi/linux/cgroupstats.h:20:0,
                 from netlink_nlctrl.c:11:
../bundled/linux/include/uapi/linux/taskstats.h:21:30: fatal error:
 linux/time_types.h: No such file or directory

detected by the Gitlab pipelines with the following defconfigs:
- br-arm-full-static
- bootlin-aarch64-glibc-old

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>