package/samba4: needs libxcrypt
Since the bump of Samba to version 4.21.4 in commit
716461af945e89af56eea4a3936c4a2adc7fdb4d, <crypt.h> is needed, due to
upstream comit 0dccda38f27b3bbda5d2a4de588a333ff554651a. Since
<crypt.h> is no longer provided by glibc, a dependency on libxcrypt is
needed, to avoid the following build failure:

../../lib/util/util_crypt.c:5:10: fatal error: crypt.h: No such file or directory
    5 | #include <crypt.h>
      |          ^~~~~~~~~
compilation terminated.

This has not been detected by the autobuilders, presumably because a
lot of glibc configurations end up having libxcrypt selected by other
packages, but the issue is reproducible by building:

BR2_arm=y
BR2_cortex_a9=y
BR2_ARM_ENABLE_VFP=y
BR2_TOOLCHAIN_EXTERNAL=y
BR2_TOOLCHAIN_EXTERNAL_BOOTLIN=y
BR2_PACKAGE_SAMBA4=y

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>