package/gzip: add upstream patch to fix build for aarch64
Since Buildroot commit [1] (package/gzip: bump version to 1.15),
gzip fails at build time for Aarch64 with the error:

  In file included from gzip.c:61:
  gzip.h:120:21: error: expected ')' before '+' token
    120 | #  define head (prev+WSIZE)  /* hash head (see deflate.c) */
        |                     ^

The issue was introduced by upstream commit [2], included in
gzip 1.15.

This commit fixes the issue by adding the patch
0001-build-avoid-failure-to-build-on-linux-aarch64.patch
from upstream commit [3], not yet included in a
gzip release.

Fixes:
https://autobuild.buildroot.org/results/3795b23407021e9fbaaf44c9319085c30d7511c1/

[1] https://gitlab.com/buildroot.org/buildroot/-/commit/fe21a5fe307239c842f5a095fe4f8e53c5c3e352
[2] https://cgit.git.savannah.gnu.org/cgit/gzip.git/commit/?id=ede0a8888a4d3d0750e1651e01f198e2faab5d59
[3] https://cgit.git.savannah.gnu.org/cgit/gzip.git/commit/?id=b4ed8e73401968bcad749afb0e636dd3ec205ca7

Reported-by: Waldemar Brodkorb <wbx@openadk.org>
Link: https://lore.kernel.org/buildroot/asJEBMQpD2FYJql2@waldemar-brodkorb.de/
Signed-off-by: Peter Seiderer <ps.report@gmx.net>
[Julien: add info in commit log]
Signed-off-by: Julien Olivain <ju.o@free.fr>