package/libtraceevent: needs dynamic library
Fix the following build failure raised since the addition of the package
in commit 1474f1b34b178defca1d16d18a2446fadda9a12b:

../src/event-plugin.c:10:10: fatal error: dlfcn.h: No such file or directory
   10 | #include <dlfcn.h>
      |          ^~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/7802d1ad00293147edda39683f6d3f614dd48263

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[yann.morin.1998@free.fr: only list first-level inherited deps]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>