package/syslog-ng: needs libopenssl, not libressl
Buildroot commit 51ab6d2290f169f4bb96b8dbbab2d8fb4656766d bumped the
package from version 4.8.3 to 4.11.0. Upstream commit
https://github.com/syslog-ng/syslog-ng/commit/dbe9fb306929168172062a6bc985eb7e38201dab
added the usage of OpenSSL BIO_ functions in version 4.9.0 causing
build errors with LibreSSL:

lib/transport/transport-tls.c: In function 'BIO_s_transport':
lib/transport/transport-tls.c:125:3: error: implicit declaration of
 function 'BIO_meth_set_write_ex'; did you mean 'BIO_meth_set_write'?
 [-Wimplicit-function-declaration]
  125 |   BIO_meth_set_write_ex(meth, _BIO_transport_write);

lib/transport/transport-tls.c:126:3: error: implicit declaration of
 function 'BIO_meth_set_read_ex'; did you mean 'BIO_meth_set_read'?
 [-Wimplicit-function-declaration]
  126 |   BIO_meth_set_read_ex(meth, _BIO_transport_read);

because LibreSSL does not provide these functions.

Fixes:
https://autobuild.buildroot.net/results/117/117b3b38098df075d96167863d9f6b933a97eb64/
https://autobuild.buildroot.net/results/a39/a39ecc88a9342005b75660ee0ac60a1025fa6fc2/
https://autobuild.buildroot.net/results/6b3/6b3eb910ccdb67827f0c12cea0e3a63c5e6b68af/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>