package/rtty: bump to version 8.1.2
- Drop patch (already in version)
- This bump will fix the following build failure with musl >= 1.2.5
  thanks to
  https://github.com/zhaojh329/rtty/commit/eb6394c3d83a21a8825e47b40659cfe0ead33b6f:

  /home/autobuild/autobuild/instance-22/output-1/build/rtty-8.1.0/src/file.c: In function 'start_upload_file':
  /home/autobuild/autobuild/instance-22/output-1/build/rtty-8.1.0/src/file.c:156:24: error: implicit declaration of function 'basename' [-Werror=implicit-function-declaration]
    156 |     const char *name = basename(path);
        |                        ^~~~~~~~

https://github.com/zhaojh329/rtty/releases/tag/v8.1.2
https://github.com/zhaojh329/rtty/releases/tag/v8.1.1

Fixes:
 - http://autobuild.buildroot.org/results/382405b421a8ea7b5b3beb553f47fa20427fa3c3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit ca742a985cc9acc40fff3539c696e64fa040f1c4)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>