package/gdbm: needs fork
gdbm needs fork since
https://git.savannah.gnu.org/cgit/gdbm.git/commit/?id=9016182fe92dcdfa9103acd144ab01f30463ac72
which will result in the following build failure since bump to version
1.21 in commit 60add404db424e2652673a7b6a3ba2bc80380b42:

/home/buildroot/autobuild/instance-1/output-1/host/opt/ext-toolchain/arm-buildroot-uclinux-uclibcgnueabi/bin/ld.real: ./libgdbmapp.a(gdbmshell.o): in function `shell_handler':
gdbmshell.c:(.text+0x3dc): undefined reference to `fork'

Fixes:
 - http://autobuild.buildroot.org/results/effc22ac47350bdbc19074dd724eab16f53913b8

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>