configs/ls1046a-rdb: linux needs host-openssl
Since Buildroot commit [1] which introduced this defconfig using a
Kernel 6.6.x series, the build can fail with error:

    certs/extract-cert.c:21:10: fatal error: openssl/bio.h: No such file or directory

The issue is generally masked by the build order, as
arm-trusted-firmware selects BR2_TARGET_ARM_TRUSTED_FIRMWARE_FIP=y
which requires host-openssl.

The issue can be reproduced in the Buildroot Docker reference image,
using the commands:

    utils/docker-run
    make ls1046a-rdb_defconfig
    make linux

This commit fixes the issue by explicitly adding
BR2_LINUX_KERNEL_NEEDS_HOST_OPENSSL=y to the defconfig.

[1] https://gitlab.com/buildroot.org/buildroot/-/commit/774035189fc211fccedb856b1718c8836be94387

Signed-off-by: Julien Olivain <ju.o@free.fr>
(cherry picked from commit a83242f131f6b4e130efc1b995e0cc45755b583c)
Signed-off-by: Thomas Perale <thomas.perale@mind.be>