package/catatonit: fix build with kernel < 5.9
Fix the following build failure with kernel < 5.0 raised since the
addition of the package in commit
e3975ec7d4b478ec6c1ba56b63cbb5bccfb9dd09:

catatonit.c:39:11: fatal error: linux/close_range.h: No such file or directory
   39 | # include <linux/close_range.h>
      |           ^~~~~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/ed9a847905083175c7fcb2f2df28f9ac5b9c3313

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>