configs/freescale_imx6{dl, q, sx}*: bump BSP components to lf-6.6.23-2.0.0
Note: configs/freescale_imx6{dl,q,sx}* corresponds to the five:
freescale_imx6dlsabreauto_defconfig
freescale_imx6dlsabresd_defconfig
freescale_imx6qsabreauto_defconfig
freescale_imx6qsabresd_defconfig
freescale_imx6sxsabresd_defconfig

Those i.MX6 Sabre defconfigs have a lot in common. This is why they are
all updated at once in this single commit.

This commit bumps U-Boot and Linux kernel to the NXP BSP
lf-6.6.23-2.0.0 versions. The imx6sabre uboot patch is also rebased on
the new version, and the "Upstream:" tag is added to flag this patch
as Buildroot-specific. The ".checkpackageignore" entry for this patch
is also removed.

While bumping those BSP components, this commit also adds the custom
hashes by enabling BR2_DOWNLOAD_FORCE_CHECK_HASHES=y in those
defconfigs. Hash files are added in the _PATCH_DIR. The
".checkpackageignore" entries for those defconfigs are also removed.

Also, since commit dc0f721 "package/gcc: switch to 13.x as default",
those freescale_imx6{dl,q,sx}* are failing to build the Kernel
with output:

    drivers/ata/libahci.c: In function 'ahci_led_store':
    ././include/linux/compiler_types.h:315:45: error: call to '__compiletime_assert_340' declared with attribute error: BUILD_BUG_ON failed: sizeof(_s) > sizeof(long)
      315 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
          |                                             ^

This commit fixes the issue by bumping components which includes the
needed gcc-13 fixes.

The Kernel DTS names are also updated by adding the new "nxp/imx/"
prefix, to follow the upstream reorganization in [1], first included
in v6.5.

Fixes:
https://gitlab.com/buildroot.org/buildroot/-/jobs/7422089449
https://gitlab.com/buildroot.org/buildroot/-/jobs/7422089451
https://gitlab.com/buildroot.org/buildroot/-/jobs/7422089452
https://gitlab.com/buildroot.org/buildroot/-/jobs/7422089455
https://gitlab.com/buildroot.org/buildroot/-/jobs/7422089456

[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=724ba6751532055db75992fc6ae21c3e322e94a7

Signed-off-by: Julien Olivain <ju.o@free.fr>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>