package/opus: fix build with BR2_OPTIMIZE_FAST
Fixes:
http://autobuild.buildroot.net/results/194/1941e194e1f5ad0bc4982ad39c3e34d266bc49c6/

opus requires that it is configured with --enable-float-approx when
-ffast-math (BR2_OPTIMIZE_FAST) is used, otherwise it errors out at build
time:

celt/arch.h:198:2: error: #error Cannot build libopus with -ffast-math
unless FLOAT_APPROX is defined.  This could result in crashes on extreme
(e.g.  NaN) input

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 43e859d47a5474d8acdaf81a0ea63aa9a909985f)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>