package/binutils: fix change to 2.43 as default version
Commit 360fd01de20eb42aa0e6b5e9f7b37eaa104c6fc9 changed the binutils
package to use 2.43.x as the default version, but got the change wrong
in the BINUTILS_VERSION variable assignment. Indeed we don't support
2.43, but 2.43.1. This issue is causing the following build failure:

  ERROR: No hash found for binutils-2.43.tar.xz

Fixes:

  https://gitlab.com/vjardin/buildroot/-/jobs/9043815781

Signed-off-by: Vincent Jardin <vjardin@free.fr>
[Thomas: proper fix, and improved commit log]
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>