package/liburcu: fix build with gcc 4.8
Fix the following lttng-tools build failure raised since bump of liburcu
to version 0.13.0 in commit 9cedbcf494e647371f92368014d31091848772bb and
https://github.com/urcu/userspace-rcu/commit/109267f653502cf5ef5ada5d098167b9726daa2d:

In file included from ../../../src/common/error.h:16:0,
                 from directory-handle.c:9:
../../../src/common/error.h:44:25: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'struct'
 extern DECLARE_URCU_TLS(struct log_time, error_log_time);
                         ^
This is fixed by upstream
0003-Always-use-__thread-for-Thread-local-storage-except-on-MSVC.patch.
Also include upstream 0002-fix-don-t-use-C-thread_local-on-MacOs.patch
to avoid conflicts.

Fixes:
 - http://autobuild.buildroot.org/results/70d645593c9e164d0d044da1b0128cda9c96e830

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>