package/botan: disable neon with arm soft float
Disable neon with soft float to fix the following build failure raised
at least since version 2.19.1:

In file included from build/include/botan/internal/simd_32.h:27,
                 from src/lib/block/aes/aes_vperm/aes_vperm.cpp:15:
/home/thomas/autobuild/instance-1/output-1/host/lib/gcc/arm-buildroot-linux-musleabi/10.4.0/include/arm_neon.h:31:2: error: #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softfp or -mfloat-abi=hard"
   31 | #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softfp or -mfloat-abi=hard"
      |  ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/6b311e97484db2b0f8adbda140320d696713b1e0
 - http://autobuild.buildroot.org/results/c309940ea6db0845d8221fb51611d0254222c644

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 48c5053576334d9349180349e58240ea02753188)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>