package/net-tools: fix build with linux 7.1
Fixes build error

rose.c:41:10: fatal error: linux/rose.h: No such file or directory
   41 | #include <linux/rose.h>

caused by the upstream removal of the ax25 and amateur radio (hamradio)
subsystem:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-7.1.y&id=dd8d4bc28ad7252610d8e79c1313a2d1e3499a51

which was added to buildroot with commit
9530d74ddb04d5fc81f9054ec0e76fbcb2a1e7d2.

For details see https://github.com/ecki/net-tools/issues/69

Fixes:
https://autobuild.buildroot.net/results/6c7/6c7783e3b6dad01b5dd725141ebed2b84242051e/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Fiona Klute <fiona.klute@gmx.de>