package/kodi: add upstream patch to fix build on s390, mark unavailable on m68k
Build errors were found by the Gitlab pipelines with these defconfigs:

- bootlin-m68k-68040-uclibc
  CMake Error at cmake/scripts/linux/ArchSetup.cmake:50 (message):
    Unknown CPU: m68k

- bootlin-s390x-z13-glibc
  CMake Error at cmake/scripts/linux/ArchSetup.cmake:50 (message):
    Unknown CPU: s390x

Backport an upstream commit from the upcoming Piers branch to fix the
restriction in ArchSetup.cmake.

This caused a different build error on m68k later on:

/builds/bkuhls/buildroot/br-test-pkg/bootlin-m68k-68040-uclibc/build/kodi-21.3-Omega/xbmc/utils/MathUtils.h:142:5:
 error: unknown register name ‘st’ in ‘asm’
  142 |     __asm__ __volatile__ (

because m68k is not part of the list of archs to disable asm code:
https://github.com/xbmc/xbmc/blob/Omega/xbmc/utils/MathUtils.h#L26

Upstream rejected to add m68k there:
https://github.com/xbmc/xbmc/pull/22519
https://github.com/xbmc/xbmc/pull/22357#issuecomment-1368358471

so we disable m68k in BR2_PACKAGE_KODI_ARCH_SUPPORTS.

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>