package/rtl8821au: bump to version 2025-12-13
With Kernel >= 6.18 introduced in [1] rtl8821au fails at build
time with error:

    core/rtw_security.c:2008:13: error: conflicting types for 'sha256_init'; have 'void(struct sha256_state_rtk *)'

Fixes:
https://autobuild.buildroot.org/results/bc0ec5fe3acb37740b54eb1af1fe5d9284c87cf2/

[1] https://gitlab.com/buildroot.org/buildroot/-/commit/a06d79862a60d3c8d5ddd6a9ab12b5ccdd91984c

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
[Julien: add details in commit log]
Signed-off-by: Julien Olivain <ju.o@free.fr>
(cherry picked from commit d75b8c5b7501c4b9a4b85df531d6e19c159a7934)
Signed-off-by: Thomas Perale <thomas.perale@mind.be>