package/dump1090: fix dependencies
dump1090 needs threads and gcc >= 4.9 since bump to version 7.2 in
commit e80c99e1519dafc2cf88ab4672eecda88359ecb1 to avoid the following
build failures:

In file included from dump1090.c:50:
dump1090.h:69:10: fatal error: pthread.h: No such file or directory
   69 | #include <pthread.h>
      |          ^~~~~~~~~~~

In file included from dump1090.c:50:0:
dump1090.h:68:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^

Fixes:
 - http://autobuild.buildroot.org/results/a8993d9a09c79231358f50d2c1eb2e08cf7d5fd6
 - http://autobuild.buildroot.org/results/7367abae7dc8187e4a2aae5397618c6e1b7aa521

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>