package/localedef: fix gcc-10.0.1 compile
Fixes build with gcc-10, by backporting an upstream patch:

  programs/ld-ctype.c:855:18: error: array subscript 0 is outside the bounds of an interior zero-length array ‘unsigned char[0]’ [-Werror=zero-length-bounds]
    855 |  replace[0].bytes[0] = '?';
        |  ~~~~~~~~~~~~~~~~^~~

Fixes: #12711

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
[yann.morin.1998@free.fr: slight reword in commit log]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit 13cc36dcfee5bdbd963fe335d19a2dc8f3486e62)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>