package/libglvnd: needs __sync_*_4 intrinsics
Fix the following build failure raised since the addition of the package
in commit 0378e2e5d9ce9d5676975dfbff501360094fdc1a:

/tmp/instance-1/output-1/host/opt/ext-toolchain/bin/../lib/gcc/sparc-buildroot-linux-uclibc/10.3.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: src/EGL/libEGL.so.1.1.0.p/libegl.c.o: in function `AtomicIncrement':
libegl.c:(.text+0x614): undefined reference to `__sync_add_and_fetch_4'

Fixes:
 - http://autobuild.buildroot.org/results/a204953020a714057ec6690e63a3ad8ac621acd5

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>