package/qt5/qt5base: fix build on sparc v8
Fix the following build failure on sparc v8 raised since commit
5770a645a3a49a3f0f02972131a4ff5283b4c11e:

ERROR: detected a std::atomic implementation that fails for function pointers.
Please apply the patch corresponding to your Standard Library vendor, found in
  qtbase/config.tests/atomicfptr

Fixes:
 - http://autobuild.buildroot.org/results/5a2/5a20e984a5536165056b3fbd93b8712e8ddbeed4/build-end.log

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit ee6d734f08e772202320841208f11a1a239ea49b)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>