package/mono: fix build with autoconf >= 2.70
For an unknown reason, the following build failure is raised on one of
the autobuilder with host gcc 6.3.0 since bump of autoconf to version
2.71 in commit ecd54b65c1f998a7ccd91f7c523e4ff38c4781da:

icall.c: In function 'mono_create_icall_signatures':
icall.c:9513:20: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
   gsize_a *types = (gsize*)(sig + 1);
                    ^

Add an upstream patch to fix it.

Fixes:
 - http://autobuild.buildroot.org/results/1d1d82b505abd16d014d754b6a4a48fb1271e3b6

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>