package/python-{treq, twisted}: add a comment to use the same version
As reported by [1], python-twisted and python-treq must use the same
version because its the same project:

https://github.com/twisted/twisted
https://github.com/twisted/treq

We have to update python-treq to version 22.2.0 [2] otherwise we have
a runtime issue:

Traceback (most recent call last):
  File "/root/sample_python_treq.py", line 2, in <module>
    import treq
  File "/usr/lib/python3.10/site-packages/treq/__init__.py", line 5, in <module>
  File "/usr/lib/python3.10/site-packages/treq/api.py", line 5, in <module>
  File "/usr/lib/python3.10/site-packages/treq/client.py", line 11, in <module>
ImportError: cannot import name '_PY3' from 'twisted.python.compat' (unknown
location)

The comment should avoid forgeting one of them while upgrading or
backporting version bump.

[1] http://lists.busybox.net/pipermail/buildroot/2022-February/637505.html
[2] https://github.com/twisted/treq/releases/tag/release-22.2.0
[3] https://gitlab.com/buildroot.org/buildroot/-/jobs/2179206653

Signed-off-by: Romain Naour <romain.naour@gmail.com>
Cc: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>