package/vlc: disable on riscv32
vlc unconditionally uses __NR_futex resulting in the following build
failure on riscv32:

linux/thread.c:53:20: error: '__NR_futex' undeclared (first use in this function)
   53 |     return syscall(__NR_futex, addr, op, val, to, addr2, val3);
      |                    ^~~~~~~~~~

A patch that fixes this was submitted upstream, but rejected [1].

Fixes:
 - http://autobuild.buildroot.org/results/be0f2243919d7a052b33118d8a901c922f8d88e7

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>

[1] https://patches.videolan.org/patch/30581/

(cherry picked from commit cc86b866ac8ddfe41679334526040f5426fa25b1)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>