package/rauc: fix build
Fix the following build failure raised since bump to version 1.5 in
commit 41bbe8df540e2c630ad04f8db7383a7e7705f368 and
https://github.com/rauc/rauc/commit/be55282d71d967dcc0cf48303f8245cbc8fff053:

In file included from /nvmedata/autobuild/instance-22/output-1/host/bin/../sparc-buildroot-linux-uclibc/sysroot/usr/include/glib-2.0/glib.h:62,
                 from src/verity_hash.c:26:
src/verity_hash.c: In function 'verify_zero':
src/verity_hash.c:69:55: error: expected ')' before 'PRIu64'
   69 |    g_message("Spare area is not zeroed at position %" PRIu64 ".",
      |                                                       ^~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/1a093c0e194a061836884419d2f50506105db01e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit ea79360907ffd8fff11828a0fbda213979b15247)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>