package/netsnmp: add upstream patches to fix musl build
The bump of netsnmp to version 5.9.4 with buildroot commit
1799cfebfd5ea1312cce74b3807d4aad044bce67 broke musl builds:

../include/net-snmp/net-snmp-config.h:1614:30: error: unknown type name 'unknown'; did you mean 'union'?

due to broken detection of __fd_mask introduced in 5.9.4 by upstream
commit https://github.com/net-snmp/net-snmp/commit/97df191ff8b16bdc53ba95d2a1c064d2a4666ae6

Added two upstream patches for __fd_mask detection to fix musl builds.

Fixes:
https://autobuild.buildroot.net/results/9d7/9d75061ca917689381c3b32f3e01640701d833a7/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>