package/openvpn: fix pam build with musl and libressl
Fix the following musl build failure raised with pam and libressl:

auth-pam.c: In function 'pam_server':
auth-pam.c:894:23: error: 'PATH_MAX' undeclared (first use in this function); did you mean 'AF_MAX'?
  894 |     char ac_file_name[PATH_MAX];
      |                       ^~~~~~~~
      |                       AF_MAX
auth-pam.c:894:23: note: each undeclared identifier is reported only once for each function it appears in
auth-pam.c:894:10: warning: unused variable 'ac_file_name' [-Wunused-variable]
  894 |     char ac_file_name[PATH_MAX];
      |          ^~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/c8834fa5ddcac6fd22fc9406e10221e64cdb8856

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit b79cefcb007d8d3279208f27d46426262f105c04)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>