package/lttng-modules: bump to version 2.13.10
This bump will fix the following build failures with kernel >= 6.3.0
thanks to
https://github.com/lttng/lttng-modules/commit/f3559e5b06b24ad0336211950792fa97398c5e9a
and
https://github.com/lttng/lttng-modules/commit/939200ef160c95c8a9d71fd80c99f42a1de0a9f0:

In file included from /home/buildroot/autobuild/instance-1/output-1/build/lttng-modules-2.13.7/./src/lttng-ring-buffer-client.h:16,
                 from /home/buildroot/autobuild/instance-1/output-1/build/lttng-modules-2.13.7/./src/lttng-ring-buffer-client-discard.c:16:
/home/buildroot/autobuild/instance-1/output-1/build/lttng-modules-2.13.7/./src/../include/lttng/events-internal.h:292:9: error: unknown type name ‘uuid_le’
  292 |         uuid_le uuid;                   /* Trace session unique ID (copy) */
      |         ^~~~~~~

[...]

/home/thomas/autobuild/instance-3/output-1/build/lttng-modules-2.13.7/./src/lib/ringbuffer/ring_buffer_mmap.c: In function ‘lib_ring_buffer_mmap_buf’:
/home/thomas/autobuild/instance-3/output-1/build/lttng-modules-2.13.7/./src/lib/ringbuffer/ring_buffer_mmap.c:116:23: error: assignment of read-only member ‘vm_flags’
  116 |         vma->vm_flags |= VM_DONTEXPAND;
      |                       ^~

https://github.com/lttng/lttng-modules/blob/v2.13.10/ChangeLog

Fixes:
 - http://autobuild.buildroot.org/results/7b8f57262a02cd9aaa953a9d8666646bae1cc655

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>