package/mono: needs NPTL
mono unconditionally uses pthread_attr_get_np and so needs NTPL since
version 4.0.1.43 and
https://github.com/mono/mono/commit/748fefa1d7199f008c6e56499ba482fb17fe1583:

mono-threads-linux.c: In function 'mono_threads_platform_get_stack_bounds':
mono-threads-linux.c:26:15: error: implicit declaration of function 'pthread_getattr_np'; did you mean 'pthread_attr_init'? [-Werror=implicit-function-declaration]
   26 |         res = pthread_getattr_np (pthread_self (), &attr);
      |               ^~~~~~~~~~~~~~~~~~
      |               pthread_attr_init

Fixes:
 - http://autobuild.buildroot.org/results/6534ee4ae699c17ee98f6f89a8a1212936e04481

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>