package/petitboot: fix NLS build
Fix the following NLS build failure on musl raised commit
bf9583a50276f52edbc37d9f85df5f2cc7fdb5dc:

/home/autobuild/autobuild/instance-4/output-1/host/lib/gcc/mips64el-buildroot-linux-musl/13.2.0/../../../../mips64el-buildroot-linux-musl/bin/ld: discover/pb_discover-pb-discover.o: undefined reference to symbol 'libintl_textdomain'

Fixes:
 - http://autobuild.buildroot.org/results/6d440d96e811674041b5a1fdae96d4c377824c2a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Laurent Vivier <laurent@vivier.eu>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit 5159c5c730dc490aced7bc17477f951786f4c405)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>