package/libnl: fix build with kernel < 4.15
Buildroot commit 0f2e9cc8784715bdf18e72c433fe9bece4537f85 bumped the
package from 3.11.0 to 3.12.0. This bump includes upstream commit
https://github.com/thom311/libnl/commit/9f8945251da404fb59778edc74be5775091e1f44
which added the usage of enums not present in older kernel versions.

The Gitlab pipelines caught the build errors with the defconfig
bootlin-aarch64-glibc-old:

lib/route/nh_encap_ila.c:50:19: error: ‘ILA_ATTR_IDENT_TYPE’ undeclared
 (first use in this function)
lib/route/nh_encap_ila.c:53:19: error: ‘ILA_ATTR_HOOK_TYPE’ undeclared
 (first use in this function)

Both enums were added to the Linux kernel in version 4.15:
https://github.com/torvalds/linux/commit/fddb231ebe647749782a9ebf11106a81f7168ba7
https://github.com/torvalds/linux/commit/70d5aef48a421a68bd9d1bf8f8267af406681580

Add upstream commit to fix the problem.

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>