package/libressl: fix powerpc64 build
Fix the following build failure with powerpc64 raised since bump to
version 3.8.2 in commit 21eca49ed5110872407b76ab9337d2877c4cda24:

In file included from /home/autobuild/autobuild/instance-23/output-1/build/libressl-3.8.4/crypto/rc4/rc4_enc.c:61:
/home/autobuild/autobuild/instance-23/output-1/build/libressl-3.8.4/crypto/../include/openssl/rc4.h:75:9: error: unknown type name 'RC4_INT'
   75 |         RC4_INT x, y;
      |         ^~~~~~~

Fixes: 21eca49ed5110872407b76ab9337d2877c4cda24
 - http://autobuild.buildroot.org/results/2533f8f642f435b40ce687b6df482c51a3fa0250

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit ee00cfd09e4ffa97019c4e9384cc761995912e28)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>