package/fluent-bit: bump to 4.0.9
News:
 - https://fluentbit.io/announcements/v4.0.4/
 - https://fluentbit.io/announcements/v4.0.5/
 - https://fluentbit.io/announcements/v4.0.6/
 - https://fluentbit.io/announcements/v4.0.7/
 - https://fluentbit.io/announcements/v4.0.8/
 - https://fluentbit.io/announcements/v4.0.9/

Fixes:
 - https://autobuild.buildroot.org/results/770/770e9106a0c92f02e0f699505e69b35ac0e6cd41/build-end.log

   /home/buildroot/instance-0/output-1/build/fluent-bit-4.0.3/plugins/out_cloudwatch_logs/cloudwatch_api.c:1540:66: error: implicit declaration of function 'strcasestr'; did you mean 'strcasecmp'? [-Wimplicit-function-declaration]

   Fix commit: https://github.com/fluent/fluent-bit/pull/10452

Signed-off-by: Thomas Devoogdt <thomas@devoogdt.com>
Signed-off-by: Julien Olivain <ju.o@free.fr>