package/gnutls: add host support for pkcs11
Future U-Boot 2026.07 will build mkeficapsule with pkcs11 support. [1]

This causes link errors with Buildroot, such as the following one:

   mkeficapsule.c:(.text.startup+0xcd3): undefined reference to `gnutls_pkcs11_init'

(Other symbols the linker complains about are: gnutls_pkcs11_add_provider,
gnutls_pkcs11_obj_list_import_url4, gnutls_x509_crt_import_pkcs11 and
gnutls_pkcs11_deinit.)

The following example commands can be used to reproduce the issue:

     make qemu_aarch64_ebbr_defconfig
     echo 'BR2_TARGET_UBOOT_CUSTOM_VERSION_VALUE="2026.07-rc3"' >>.config
     echo 'BR2_TARGET_UBOOT_NEEDS_GNUTLS=y' >>.config
     echo '# BR2_DOWNLOAD_FORCE_CHECK_HASHES is not set' >>.config
     make olddefconfig
     make uboot

This commit adds the pkcs11 support for host-gnutls.

In Buildroot, since host-gnutls is currently only needed by uboot
(and other uboot derivatives such as uboot-tools) the pkcs11 support
is added unconditionally to host-gnutls.

Link: https://github.com/u-boot/u-boot/commit/0c716a157be460006a4b762625de329b5e36dbf9 [1]
Signed-off-by: Vincent Stehlé <vincent.stehle@arm.com>
Signed-off-by: Fiona Klute <fiona.klute@gmx.de>