package/libspdm: fix build due to missing macro definition
Commit 967ba5386 "package/libspdm: bump version to 3.5.0" [1]
incorrectly removed the "0" to the LIBSPDM_ENABLE_CAPABILITY_MEL_CAP
macro definition.

This results to libspdm build failure with errors like:

    In file included from /build/libspdm-3.5.0/include/internal/libspdm_common_lib.h:20,
                     from /build/libspdm-3.5.0/library/spdm_common_lib/libspdm_com_context_data.c:7:
    /build/libspdm-3.5.0/include/hal/library/responder/measlib.h:154:38: error: #if with no expression
      154 | #if LIBSPDM_ENABLE_CAPABILITY_MEL_CAP
          |                                      ^

This commit fixes the issue by adding back this missing "0".

Fixes:
https://autobuild.buildroot.org/results/88cb77a2e6b46028f9fb7f0325348a1b1b8fd931

[1] https://gitlab.com/buildroot.org/buildroot/-/commit/967ba5386d4e15102db88a9faae1845b3e69dc6f

Reviewed-by: Alistair Francis <alistair.francis@wdc.com>
Signed-off-by: Julien Olivain <ju.o@free.fr>