package/trinity: fix musl build
Fix the following build failure on musl:

In file included from /nvmedata/autobuild/instance-17/output-1/host/powerpc64-buildroot-linux-musl/sysroot/usr/include/asm/ioctl.h:12,
                 from /nvmedata/autobuild/instance-17/output-1/host/powerpc64-buildroot-linux-musl/sysroot/usr/include/linux/ioctl.h:5,
                 from /nvmedata/autobuild/instance-17/output-1/host/powerpc64-buildroot-linux-musl/sysroot/usr/include/linux/fs.h:14,
                 from ioctls/vfs.c:3:
ioctls/vfs.c:109:35: error: 'loff_t' undeclared here (not in a function); did you mean 'off_t'?
  109 |  { .name = "FIOQSIZE", .request = FIOQSIZE, },
      |                                   ^~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/b7f46072751a8d70fa02f1c625c5279f70bec853

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit a8614ffc07993feca1a3094c1488a11913cb4e87)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>