configs/kontron_smarc_sal28: bump u-boot and linux
The old u-boot version doesn't build anymore because of the following
error:

  ModuleNotFoundError: No module named 'pkg_resources'

Bump it to the latest version 2026.04. While at it, also bump linux to
the latest LTS kernel (6.18). The new kernel grew in size, thus we also
have to enlarge the rootfs image.

Fixes: https://gitlab.com/buildroot.org/buildroot/-/jobs/13858936681
Signed-off-by: Michael Walle <mwalle@kernel.org>
Signed-off-by: Julien Olivain <ju.o@free.fr>