package/gawk: add upstream fix for systems without MPFR and GMP
Fixes build error with host-gcc-final:

options.cc:27216:2: error: #error 0Wabsolute-value does not have a Var() flag
27216 | #error 0Wabsolute-value does not have a Var() flag

$ head -n1 output/build/host-gcc-final-16.2.0/build/gcc/options.cc
  /* This file is auto-generated by optc-gen.awk.  */

introduced by the bump of gawk to 5.4.1 with buildroot commit
aa3db5b4e15c8dd67914d58c8d03ae2df3c92cab.

Fixes:
https://autobuild.buildroot.net/results/672/6727e71716af3df8e2175a50740388bc669e5462/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>