package/exim: fix libressl build
Fix the following libressl build failure raised since bump to version
4.97 in commit faec3ca30e358575f70a036879029f63f7da9b29 and
https://git.exim.org/exim.git/commit/6bf0021993572586f031ac7d973ca33358c2dac8:

In file included from tls.c:473:
tls-openssl.c: In function 'tls_client_stapling_cb':
tls-openssl.c:2652:11: error: invalid use of incomplete typedef 'OCSP_BASICRESP' {aka 'struct ocsp_basic_response_st'}
 2652 |         bs->certs
      |           ^~

Fixes: faec3ca30e358575f70a036879029f63f7da9b29
 - http://autobuild.buildroot.org/results/869fde62128d7b0c65e0ac596a3a3f69b332583d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit dc59cbe4674f9d0f953857edff11cd93d570f360)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>