package/libcli: fix build with gcc >= 14
Fix the following build failure with gcc >= 14:

libcli.c: In function 'cli_register_command':
libcli.c:430:27: error: 'calloc' sizes specified with 'sizeof' in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
  430 |   if (!(c = calloc(sizeof(struct cli_command), 1))) return NULL;
      |                           ^~~~~~
libcli.c:430:27: note: earlier argument should specify number of elements, later size of each element

Fixes:
 - http://autobuild.buildroot.org/results/a170d27689e069cf58f830bdd74f604364ee503b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit a5466a4303d7652c217139bf0dc0b1eb9d6ba0c5)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>