package/frr: bump to version 8.1
- host-elfutils is mandatory since version 8.0 and
  https://github.com/FRRouting/frr/commit/5609b3af497c44d980aad2bc7d6332dedd7974e7
- This bump is needed to fix the following build failure since bump of
  libyang to version 2.0.112 in commit
  2a3edc5e00b38f4f927894d0911990c9060e4415:

In file included from lib/northbound.c:20:
lib/northbound.c: In function 'nb_node_check_config_only':
lib/northbound.c:97:22: error: dereferencing pointer to incomplete type 'const struct lys_node'
   97 |  if (CHECK_FLAG(snode->flags, LYS_CONFIG_R)) {
      |                      ^~

- Update indentation in hash file (two spaces)

https://github.com/FRRouting/frr/releases/tag/frr-8.0
https://github.com/FRRouting/frr/releases/tag/frr-8.1

Fixes:
 - http://autobuild.buildroot.org/results/bd779ee960ba2181bc60313569c77c1e60b4e726

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>