package/lesstif: remove package
lesstif received its last release in 2009, the homepage was last
updated in 2013: https://lesstif.sourceforge.net

The last update on the project trackers was in 2015:
https://sourceforge.net/projects/lesstif/support

Debian removed lesstif in 2013:
https://wiki.debian.org/lesstif2motifTransition

The package is causing build errors since the default version of gcc was
bumped to 14.x with buildroot commit 1e1fafa1f0f5069418e92f702c2a66db6408a634:

CutPaste.c:1031:25: error: assignment to 'long int *' from incompatible
 pointer type 'char *' [-Wincompatible-pointer-types]

Instead of fixing an unmaintained package we remove it from buildroot,
no other package depends on it.

Fixes:
https://autobuild.buildroot.net/results/798/798ccab7b69754fb9b73b84e31d91bece8e7a2b4/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Arnout Vandecappelle <arnout@rnout.be>