package/gr-osmosdr: add missing host-python-six dependency to python support
Osmosdr failed to build docs when python support is enabled.
[ 41%] Copying osmosdr docstring templates as pybind headers ...
Traceback (most recent call last):
  File "/home/martb/Schreibtisch/DiscoSAT/satos/output/build/gr-osmosdr-0.2.4/docs/doxygen/update_pydoc.py", line 22, in <module>
    from doxyxml import DoxyIndex, DoxyClass, DoxyFriend, DoxyFunction, DoxyFile
  File "/home/martb/Schreibtisch/DiscoSAT/satos/output/build/gr-osmosdr-0.2.4/docs/doxygen/doxyxml/__init__.py", line 69, in <module>
    from .doxyindex import DoxyIndex, DoxyFunction, DoxyParam, DoxyClass, DoxyFile, DoxyNamespace, DoxyGroup, DoxyFriend, DoxyOther
  File "/home/martb/Schreibtisch/DiscoSAT/satos/output/build/gr-osmosdr-0.2.4/docs/doxygen/doxyxml/doxyindex.py", line 31, in <module>
    from .generated import index
  File "/home/martb/Schreibtisch/DiscoSAT/satos/output/build/gr-osmosdr-0.2.4/docs/doxygen/doxyxml/generated/index.py", line 13, in <module>
    from . import compound
  File "/home/martb/Schreibtisch/DiscoSAT/satos/output/build/gr-osmosdr-0.2.4/docs/doxygen/doxyxml/generated/compound.py", line 15, in <module>
    from . import compoundsuper as supermod
  File "/home/martb/Schreibtisch/DiscoSAT/satos/output/build/gr-osmosdr-0.2.4/docs/doxygen/doxyxml/generated/compoundsuper.py", line 15, in <module>
    import six
ModuleNotFoundError: No module named 'six'
make[2]: *** [python/bindings/CMakeFiles/osmosdr_docstrings.dir/build.make:73: python/bindings/docstring_status] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:332: python/bindings/CMakeFiles/osmosdr_docstrings.dir/all] Fehler 2

Fixes:

  http://autobuild.buildroot.net/results/b60e339e52fbc7ed7607a94381aaab6ec64b7a99/

Signed-off-by: Martin Böh <contact@martb.dev>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit cfda1f0b87ebfb7686b82f319c531d4d28fdfd67)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>