package/python-watchdog: needs python3
python3 is needed to avoid the following build failure since bump to
version 2.1.6 in commit a1f7597b4dcd60e8373040739d7abbc0f45dd5f5 and
https://github.com/gorakhargosh/watchdog/commit/86b983aa5f7bf2a65314b5dfb7ff8c1b930c10c4:

Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    import importlib.util
ImportError: No module named util

Fixes:
 - http://autobuild.buildroot.org/results/9d4/9d4abcb029f4e44a9cb454faa8416d8ebccb5b2e/build-end.log

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>