package/augeas: bump to version 1.14.1
This bump will fix the following build failure with gcc >= 14 thanks to
https://github.com/hercules-team/augeas/commit/792fb220a31a42043de6962fac6a1f6c030d67c5:

internal.c: In function 'xstrerror':
internal.c:436:12: error: returning 'int' from a function with return type 'const char *' makes pointer from integer without a cast [-Wint-conversion]
  436 |     return strerror_r(errnum, buf, len);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

https://github.com/hercules-team/augeas/blob/release-1.14.1/NEWS

Fixes:
 - http://autobuild.buildroot.org/results/65014642966721115ae4050c23b083a7f39e1300

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 321e065516a64198f586632bd83411767d98fe6c)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>