package/pipewire: fix NLS build
Fix the following build failure raised since bump to version 0.3.39 in
commit d9796f2db9866060b916487784b046bb6b76f9b6 and
https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/ddfbd684e78e2b8b9ad40bedb4612ea0197d231a:

/home/giuliobenetti/autobuild/run/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/sh4-buildroot-linux-uclibc/9.3.0/../../../../sh4-buildroot-linux-uclibc/bin/ld: src/pipewire/libpipewire-0.3.so.0.339.0.p/pipewire.c.o: in function `i18n_ntext':
pipewire.c:(.text+0x3ec): undefined reference to `libintl_dngettext'

Indeed, since that time, pipewire uses the new meson intl dependency API
which has been added in version 0.59.0 with
https://github.com/mesonbuild/meson/commit/2c6ccfe4c40741ae1f15f073f7d7bc8c398a1648

This new intl dependency API is broken (which is not so surprising based
on my experience of meson). Don't even try to fix it as meson is not
very prone to merge our pull requests:
https://github.com/mesonbuild/meson/issues/6108
https://github.com/mesonbuild/meson/pull/6629

Fixes:
 - http://autobuild.buildroot.org/results/435d59d40209cc1028cee8e2a71a69cd3769ab56

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>