package/fontconfig: add pthread as a dependency of a static lib
Fixes:
http://autobuild.buildroot.net/results/d2d/d2d73f3c7075ca6e9782b9bb591dae40ab56b6a2/

ffmpeg configure prints: "ERROR: fontconfig not found using pkg-config"

Please note that the ffmpeg build error was reproducible but with a
different error message in ffbuild/config.log:

  sysroot/usr/lib/libfontconfig.a(fccache.o): in function `lock_cache':
  fccache.c:(.text+0xcd8): undefined reference to `pthread_mutex_init'

  arm-buildroot-linux-gnueabi/bin/ld: fccache.c:(.text+0xcf8):
  undefined reference to `pthread_mutex_destroy'

  arm-buildroot-linux-gnueabi/bin/ld: fccache.c:(.text+0xd00):
  undefined reference to `pthread_mutex_lock'

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit a5d70b2a0356ee3cf55ef6ae5c2718342fd24a87)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>