package/mdadm: disable -Werror
Disable -Werror by setting CWFLAGS to ""
This will avoid the following build failure raised since bump to version
4.2 in commit b03fc7974536378ba102418451ba7e9801bc6251:

mdadm.c: In function 'main':
mdadm.c:156:28: error: this statement may fall through [-Werror=implicit-fallthrough=]
  154 |    if (mode == ASSEMBLE || mode == BUILD ||
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/c0f216b7aadb794110409d03dcef7fa58e833cd4

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>