package/dmraid: fix musl build
dmraid is a very old package from 2010 with an awkward configure script
which doesn't honor CFLAGS:

 ac_cv_env_CFLAGS_set=set
 ac_cv_env_CFLAGS_value='-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os -g0 '

[...]

 ## ----------------- ##
 ## Output variables. ##
 ## ----------------- ##

 AWK='gawk'
 CC='/home/autobuild/autobuild/instance-3/output-1/host/bin/sh4a-buildroot-linux-musl-gcc'
 CFLAGS='-O2'

resulting in the following build failure with musl >= 1.2.4 and
https://github.com/bminor/musl/commit/25e6fee27f4a293728dd15b659170e7b9c7db9bc
because _LARGEFILE64_SOURCE is not set:

/home/autobuild/autobuild/instance-3/output-1/host/lib/gcc/sh4a-buildroot-linux-musl/12.3.0/../../../../sh4a-buildroot-linux-musl/bin/ld: misc/file.o: in function `rw_file':
file.c:(.text+0x150): undefined reference to `lseek64'

To fix this issue, pass TARGET_CONFIGURE_OPTS through DMRAID_MAKE_OPTS

Fixes:
 - http://autobuild.buildroot.org/results/5c7c82959ce92db908d3ca20e2c1137509c2f981

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>
(cherry picked from commit de6415ad9c35b2013af1f1821bcac12ba3959674)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>