package/uftrace: needs NPTL
uftrace needs NPTL since its addition in commit
09c97972d9f90b69cfc36f9ffe9e22c13daf9307 and
https://github.com/namhyung/uftrace/commit/543fe53c256ceaef2d4d7cc44925bf1ad5a068a8:

buildroot/build/uftrace-0.10/buildroot/build/uftrace-0.10/cmds/record.c:670: undefined reference to `pthread_setname_np'

Fixes:
 - http://autobuild.buildroot.org/results/8f884efb9d45f9145a4799981157c9226390b423

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit a3475c5c69b371c4fe8f74b253d868869eee12c6)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>