package/rt-tests: needs kernel >= 4.5
rt-tests unconditionally uses CGROUP2_SUPER_MAGIC since
https://git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git/commit/?id=47e857d4bf77440cb59d17c6ed7882a48514f18d
which is only available since kernel 4.5 and
https://github.com/torvalds/linux/commit/67e9c74b8a873408c27ac9a8e4c1d1c8d72c93ff
resulting in the following build failure since bump to version 2.3 in
commit a952b016263cb9ae5f116dac0b3da4ad93a4c55f:

src/sched_deadline/cyclicdeadline.c:381:29: error: 'CGROUP2_SUPER_MAGIC' undeclared (first use in this function)
  ret = mounted(CGROUP_PATH, CGROUP2_SUPER_MAGIC);
                             ^

Fixes:
 - http://autobuild.buildroot.org/results/74766c215a6cc19cd02faec6181ccd5de49c15cf

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>