package/apr-util: requires DES in openssl
Enable DES in openssl to avoid the following build failure raised since
commit a83d41867c8d69a77d5cd0a665aa216af5340359:

crypto/apr_crypto_openssl.c: In function 'crypto_cipher_mechanism':
crypto/apr_crypto_openssl.c:385:27: error: implicit declaration of function 'EVP_des_ede3_cbc'; did you mean 'NID_des_ede3_cbc'? [-Wimplicit-function-declaration]
  385 |             key->cipher = EVP_des_ede3_cbc();
      |                           ^~~~~~~~~~~~~~~~
      |                           NID_des_ede3_cbc

Fixes: a83d41867c8d69a77d5cd0a665aa216af5340359
 - http://autobuild.buildroot.org/results/4b1088a705f8564f85e629316f5cfc92953f0047

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>
(cherry picked from commit 8bb67c230b9d32d91bc85e5563f3453cb50d7a38)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>