package/ocrad: fix static build
Fix the following static build failure raised since bump to version 0.28
in commit 1b677db703dc0b976a707942bbc94ecd3f7b4b4b:

/home/buildroot/autobuild/run/instance-2/output-1/host/opt/ext-toolchain/bin/../lib/gcc/arm-buildroot-linux-uclibcgnueabi/9.3.0/../../../../arm-buildroot-linux-uclibcgnueabi/bin/ld: /home/buildroot/autobuild/run/instance-2/output-1/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libpng.a(png.o): in function `png_reset_crc':
png.c:(.text+0x738): undefined reference to `crc32'

Note that the custom, hand-rolled configure script inserts the LIBS we
pass on the command line, in front of the hard-coded LIBS, which
currently is just LIBS=-lpng, so we end up with a final LIBS set to:
    LIBS=-L.../sysroot/usr/lib -lpng16 -lz -lpng

... the latter -lpng being redundant and unnecessary, but innocuous.

Fixes:
 - http://autobuild.buildroot.org/results/97543d8df5c40818e05622490e4aad60b48934a6

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[yann.morin.1998@free.fr: split multi-line one item per line]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>