package/cryptodev-linux: fix build with kernel >= 6.7
Fix the following build failure with kernel >= 6.7:

/home/buildroot/autobuild/instance-0/output-1/build/cryptodev-linux-1.13/./cryptlib.c: In function ‘cryptodev_hash_init’:
/home/buildroot/autobuild/instance-0/output-1/build/cryptodev-linux-1.13/./cryptlib.c:384:28: error: implicit declaration of function ‘crypto_ahash_alignmask’; did you mean ‘crypto_aead_alignmask’? [-Werror=implicit-function-declaration]
  384 |         hdata->alignmask = crypto_ahash_alignmask(hdata->async.s);
      |                            ^~~~~~~~~~~~~~~~~~~~~~
      |                            crypto_aead_alignmask

Fixes:
 - http://autobuild.buildroot.org/results/466360c7baec2edf42dc6f0ad9a8d757dd471c88

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 15ec07403f3abcd42441cde7186a451de8a458dc)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>