package/lttng-modules: needs CONFIG_KPROBES
Fix the following build failure:

/nvmedata/autobuild/instance-18/output-1/build/lttng-modules-2.13.1/./src/wrapper/kallsyms.c:20:3: error: #error "LTTng-modules requires CONFIG_KPROBES on kernels >= 5.7.0"
   20 | # error "LTTng-modules requires CONFIG_KPROBES on kernels >= 5.7.0"
      |   ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/a733056d59f15573698c191562afced3f7a331ee

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 2c05de430eaff1d2839e15465ba821eea968a858)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>