package/liburing: needs MMU
liburing needs MMU since its addition in commit
03ca6f4e39874583060317e7e15e9e360220877e:

setup.c: In function 'io_uring_ring_dontfork':
setup.c:119:8: warning: implicit declaration of function 'madvise'; did you mean 'raise'? [-Wimplicit-function-declaration]
  119 |  ret = madvise(ring->sq.sqes, len, MADV_DONTFORK);
      |        ^~~~~~~
      |        raise

Fixes:
 - http://autobuild.buildroot.org/results/33f3c58e98daab07139b4f400b85f87c0e314240

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit b5f07f62eb0392c3bddd63ac16d12adec7e98812)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>