configs/imx8mmpico: uboot needs openssl
Commit 78e8f383 "configs/imx8mmpico: bump bsp components to version
tn-kirkstone_5.15.71-2.2.0" bumped components, but forgot to add
BR2_TARGET_UBOOT_NEEDS_OPENSSL=y.

This commit adds it to the defconfig to fix the build.

Fixes:
- https://gitlab.com/buildroot.org/buildroot/-/jobs/5858180248

    In file included from tools/imagetool.h:24,
                     from tools/aisimage.c:7:
    include/image.h:1166:12: fatal error: openssl/evp.h: No such file or directory
     1166 | #  include <openssl/evp.h>
          |            ^~~~~~~~~~~~~~~

Signed-off-by: Julien Olivain <ju.o@free.fr>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>