package/uclibc: prevent config with unsupported RISC-V float ABI
uClibc currently supports RISC-V with a soft-float or 64-bit
hard-float ABI, but not 32-bit hard-float. Selecting
BR2_RISCV_ABI_LP64F results in a build failure:

./include/sys/asm.h:42:4: error: #error unsupported FLEN
   42 | #  error unsupported FLEN
      |    ^~~~~

Change the conditions for BR2_PACKAGE_UCLIBC_ARCH_SUPPORTS
accordingly.

Fixes:

  http://autobuild.buildroot.net/results/ac6e2c4369df46bad9a2ad46ce073e3f15f22ee6/

Signed-off-by: Ben Hutchings <ben.hutchings@mind.be>
[Thomas: instead of !BR2_RISCV_ABI_LP64F, use BR2_RISCV_ABI_LP64 ||
BR2_RISCV_ABI_LP64D]
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 9a51381cedc16e6d70cb85e1144f6e0fa89af69a)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>