package/batman-adv: needs linux kernel libcrc32c support
Fixes:

  ERROR: modpost: "crc32c" [.../build/batman-adv-2021.0/net/batman-adv/batman-adv.ko] undefined!

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit 6754f656dede40d380f56086849fdd4092b15846)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>