package/gstreamer1/gst1-plugins-good: fix build with gcc 4.8
Fix the following build failure with gcc 4.8 raised since bump to
version 1.20.0 in commit 34317969278d7b6d923d4889fb4235f112b2b201:

../ext/soup/gstsouploader.c: In function 'gst_soup_load_library':
../ext/soup/gstsouploader.c:219:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (guint i = 0; i < len; i++) {
   ^

Fixes:
 - http://autobuild.buildroot.org/results/21792a9839d9722815075569123df8747fc450e3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>