package/rt-tests: needs __sync_*_4 intrisics
rt-tests needs __sync_*_4 intrisics since bump to version 1.9 in commit
32be34427956a590d07d12e965f97fa9d2110ae9 and
https://git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git/commit/?id=c86dec5765e1ad0bd1d0c429ca7c138c11da2c80:

oslat.c:(.text+0x1034): undefined reference to `__sync_add_and_fetch_4'

Fixes:
 - http://autobuild.buildroot.org/results/9b065ee7611db3a404863b85161f46a2e9e8ddad

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit 24d2bc3b1c747fbeb100fa79dfcd9f3645b98dd3)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>