package/dieharder: drop rgb_operm
Fix the following build failure:

/home/autobuild/autobuild/instance-7/output-1/host/lib/gcc/m68k-buildroot-linux-uclibc/11.2.0/../../../../m68k-buildroot-linux-uclibc/bin/ld: dieharder-add_ui_rngs.o:(.data+0xd8): undefined reference to `rgb_operm'

Fixes:
 - http://autobuild.buildroot.org/results/7be339674291b39f8eddb8ad065f0988128ecfe9

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit d0ffdb2bdd22432f6f269a43ceaf7f1e51d535b5)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>