package/dmenu-wayland: fix uclibc build
Set -std=gnu99 to fix the following uclibc build failure raised since
the addition of the package in commit
2f6b1b8e6893003efcc72185cd468dcb0b088b2d:

../draw.c:37:23: error: 'CLOCK_REALTIME' undeclared (first use in this function)
   37 |         clock_gettime(CLOCK_REALTIME, &ts);
      |                       ^~~~~~~~~~~~~~

Fixes: 2f6b1b8e6893003efcc72185cd468dcb0b088b2d
 - http://autobuild.buildroot.org/results/4b9db67fb444ec35d741e5d3e74263ac0c4d4a7d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>