package/sslh: fix build with gcc 4.8
Fix the following build failure raised since bump to version 1.22c in
commit 5b9c58531e97b012a8a11c6ae5145b16dcfb8f74:

sslh-select.c: In function 'udp_timeouts':
sslh-select.c:480:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (int i = 0; i < fd_info->max_fd; i++) {
     ^

Fixes:
 - http://autobuild.buildroot.org/results/aaaac2beb16730747b4265e81d09cb5e072c7267

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>