package/cryptodev-linux: fix build with linux >= 6.4
Fix the following build failure with linux >= 6.4:

/home/autobuild/autobuild/instance-15/output-1/build/cryptodev-linux-1.13/./ioctl.c:1249:18: error: ‘struct ctl_table’ has no member named ‘child’
 1249 |                 .child          = verbosity_ctl_dir,
      |                  ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/ecbf426f6b0ff920a51c1674b080c35edf5db859

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit f5eba2ef3a5930cd05ad33741b83af02c1dbf42e)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>