package/samba4: needs iconv.h
samba4 needs iconv.h since bump to version 4.15.3 in commit
d33ad03e75b89feb97a7edeba3156fa2ac417b06 and
https://gitlab.com/samba-team/samba/-/commit/fc51b38ed8b7ff239db82d4d2d52f6332910ca97:

../../source3/lib/netapi/examples/common.c:13:10: fatal error: iconv.h: No such file or directory
   13 | #include <iconv.h>
      |          ^~~~~~~~~

Strangely enough, there is no autobuilder failures.

Fixes:
 - https://bugs.buildroot.org/show_bug.cgi?id=14821

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>