package/batman-adv: fix build failures with Linux >= 6.12
The first two patches fix:

/home/autobuild/autobuild/instance-5/output-1/build/batman-adv-2024.2/net/batman-adv/distributed-arp-table.c:10:10: fatal error: asm/unaligned.h: No such file or directory

Which is a fallout out from Linux kernel upstream commit
5f60d5f6bbc12e782fac78110b0ee62698f3b576 that got merged in Linux
6.12.

Patch 0003 is needed due to the removal of NETIF_F_LLTX in upstream
Linux kernel commit 00d066a4d4edbe559ba6c35153da71d4b2b8a383 that got
merged in Linux 6.12.

Patch 0004 is needed due to the removal of NETIF_F_NETNS_LOCAL in
upstream Linux kernel commit 05c1280a2bcfca187fe7fa90bb240602cf54af0a
that got merged in Linux 6.12.

Fixes:

  https://autobuild.buildroot.org/results/4ac369f7fe9cd62de431fa02bc982465e8d1f806/

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
Signed-off-by: Julien Olivain <ju.o@free.fr>