package/zlog: disable -Werror
Set WARNINGS="" to disable -Werror and fix the following build failure
raised since bump to version 1.2.17 in commit
53779570e50307482d095ff6ef95582cac2a0165 and
https://github.com/HardySimpson/zlog/commit/b8d9634a1a9fb6c60ec2a23b0cb4b5e29e6e3502:

event.c: In function 'zlog_event_new':
event.c:94:72: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
   94 |         a_event->tid_hex_str_len = sprintf(a_event->tid_hex_str, "%x", (unsigned int)a_event->tid);
      |                                                                        ^
cc1: all warnings being treated as errors

Fixes:
 - http://autobuild.buildroot.org/results/21e9212dbb3d77108b45f755890a8e66b23d2407

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>