package/avro-c: fix build with gcc 14
Fix the following build failure with gcc 14:

In file included from /home/autobuild/autobuild/instance-6/output-1/build/avro-c-1.11.3/src/avro/legacy.h:33,
                 from /home/autobuild/autobuild/instance-6/output-1/build/avro-c-1.11.3/src/avro/io.h:31,
                 from /home/autobuild/autobuild/instance-6/output-1/build/avro-c-1.11.3/src/avro/consumer.h:30,
                 from /home/autobuild/autobuild/instance-6/output-1/build/avro-c-1.11.3/src/avro.h:28,
                 from /home/autobuild/autobuild/instance-6/output-1/build/avro-c-1.11.3/examples/quickstop.c:18:
/home/autobuild/autobuild/instance-6/output-1/build/avro-c-1.11.3/examples/quickstop.c: In function 'print_person':
/home/autobuild/autobuild/instance-6/output-1/build/avro-c-1.11.3/examples/quickstop.c:123:61: error: passing argument 3 of 'first_value.iface->get_string' from incompatible pointer type [-Wincompatible-pointer-types]
  123 |                         avro_value_get_string(&first_value, &p, &size);
      |                                                             ^~
      |                                                             |
      |                                                             int32_t ** {aka int **}

Fixes:
 - http://autobuild.buildroot.org/results/fdbc6a888ba8bb51f4e076a450919477d1378eb3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit b39dfdde338bb254b958fbfbe6c7f0fb4e447e34)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>