configs/olimex_a20_olinuxino_lime_legacy: use gcc 6.x and not the default version
The old 3.4 Linux kernel used by this defconfig doesn't build with gcc 7.x:

include/linux/compiler-gcc.h:106:1: fatal error: linux/compiler-gcc7.h: No such file or directory

So let's use gcc 6.x for the time being.

Long term, we should use a newer or different kernel source for this
defconfig, or get rid of the defconfig entirely if there's no updated
kernel with a fix.

Fixes:

  https://gitlab.com/buildroot.org/buildroot/-/jobs/123771091

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 88928bbd6ebf2e56ea3b0caf45d6f4cc0db53646)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>