package/gensio: fix libressl build
Fix the following libressl build failure raised since bump to version
2.5.5 in commit 8f67d23af11510b447d9d0e1a71249f97e655305 and
https://github.com/cminyard/gensio/commit/12c94a29808e930a660142013c518468ca14ea62:

gensio_filter_certauth.c: In function 'v3_certauth_add_challenge_rsp':
gensio_filter_certauth.c:735:44: error: 'EVP_PKEY_ED25519' undeclared (first use in this function); did you mean 'EVP_PKEY_DSA1'?
  735 |     if (EVP_PKEY_base_id(sfilter->pkey) == EVP_PKEY_ED25519) {
      |                                            ^~~~~~~~~~~~~~~~
      |                                            EVP_PKEY_DSA1

Fixes:
 - http://autobuild.buildroot.org/results/a0348df9bf9c7ccfd576f607abb6b186da384ad9

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>