package/python-pillow: fix legal info
Commit dfaa34ddd3398f22718f7361d617d98d53b51630 forgot to update hash of
LICENSE file:

ERROR: LICENSE has wrong sha256 hash:
ERROR: expected: e706384c6f299d1b6fa782ae657740b372b4bd7938a1a318bf94ac249114758a
ERROR: got     : cf234c27a3f275f5a050f4df3946f8855704226fe4e7ca8b33928cbcecbced37

LICENSE file has been updated to clean up authors and contributors:
https://github.com/python-pillow/Pillow/commit/4197263dff19a79f13cd86f6cdc9a0ec6c06da92

Fixes: dfaa34ddd3398f22718f7361d617d98d53b51630
 - http://autobuild.buildroot.org/results/5a35d83c73367e1b20534b1bc7f2f564cf653a38

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit b8a86f5a8fcf2930b17a165ead7274618b7aba75)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>