package/strace: bump version to 6.18
Release notes: https://github.com/strace/strace/blob/v6.18/NEWS

Buildroot commit a06d79862a60d3c8d5ddd6a9ab12b5ccdd91984c bumped the
linux kernel to version 6.18 which broke the build of strace.

The issue can be reproduced with commands:

    cat >.config <<EOF
    BR2_aarch64=y
    BR2_PACKAGE_STRACE=y
    EOF
    make olddefconfig
    make strace

The build is failing with error:

    listmount.c: In function 'print_mnt_id_req':
    listmount.c:39:16: error: 'struct mnt_id_req' has no member named 'spare'
       39 |         if (req.spare) {
          |                ^

Fixes:
https://autobuild.buildroot.org/results/8e3de892a1c4aa176a8b3a5defba48aa9830bc89/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
[Julien:
 - update pgp key comment in hash file
 - add commands to reproduce the issue and error log
 - add autobuilder failure log
]
Signed-off-by: Julien Olivain <ju.o@free.fr>