package/systemd: now needs target and host gcc >= 8
Since the bump of systemd from 254.13 to 256.4, systemd no longer
builds with gcc <= 7:

../src/basic/mountpoint-util.c: In function ‘fstype_is_api_vfs’:
../src/basic/macro.h:385:79: error: expected ‘}’ before ‘__VA_OPT__’
         for (typeof(entry) _va_sentinel_[1] = {}, _entries_[] = { __VA_ARGS__ __VA_OPT__(,) _va_sentinel_[0] }, *_current_ = _entries_; \
                                                                               ^

This first error is due to upstream commit
dc571cccd75db7be49b2aada64baf92e3a498c39 ("macro: terminate the
temporary VA_ARGS_FOREACH() array with a sentinel"), which was made to
support GCC 14.x. If we revert this commit, then this particular issue
goes away with GCC 7.x, but then it fails with another fairly similar
issue elsewhere:

../src/shared/varlink-idl.h:110:41: error: implicit declaration of function ‘__VA_OPT__’; did you mean ‘__TA_IBIT__’? [-Werror=implicit-function-dec
laration]
                 .fields = { __VA_ARGS__ __VA_OPT__(,) {}},              \
                                         ^

This code was added by upstream commit
e50b2a93d66eff9b41999d38b8ed5eb647e2d74c ("varlink: add
IDL/introspection logic").

Upstream commit dc571cccd75db7be49b2aada64baf92e3a498c39 first
appeared in v256, while e50b2a93d66eff9b41999d38b8ed5eb647e2d74c first
appeared in v255.

Considering systemd usual policies with the support of "old" things,
it's fairly unlikely that they will care about building with older gcc
versions. They even document in
https://github.com/systemd/systemd/blob/main/README that they need gcc
>= 8.4, so let's follow that.

Fixes:

  http://autobuild.buildroot.net/results/53c1a79c391e3cc7c230017853ba935202c8d20d/

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>