package/nvme: needs dynamic library
Buildroot commit f75faf43506e5090857eb4a9d876d430ff34a972 bumped nvme
from 1.12 to 2.15 which depends on dynamic library:

../libnvme-wrap.c:8:10: fatal error: dlfcn.h: No such file or directory
    8 | #include <dlfcn.h>

Fixes:
https://autobuild.buildroot.net/results/5bc/5bccbbd7ad4ce4a6898f6bcfd0a92c09e61324ca/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>