package/matchbox-panel: add patch fixing GCC 14.x build issue
Fixes:

mb-applet-launcher.c: In function ‘get_launch_window’:
mb-applet-launcher.c:269:18: error: implicit declaration of function ‘time’ [-Wimplicit-function-declaration]
  269 |   time_t stime = time(NULL);
      |                  ^~~~

No autobuilder failures, it was hidden by other failures.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit d5bb2902ec53070ac2db82f77f45f1e0fc3ab160)
Signed-off-by: Thomas Perale <thomas.perale@mind.be>