package/seatd: daemon needs MMU
Fix the following build failure raised since bump to version 0.6.2 in
commit c54f85ca0d2ba7b73c899a27e62c67d3389617b8 and
https://github.com/kennylevinsen/seatd/commit/1e98727ae9dfdb23316249a4f32b3169d956e417:

/home/buildroot/autobuild/instance-2/output-1/host/opt/ext-toolchain/arm-buildroot-uclinux-uclibcgnueabi/bin/ld.real: seatd-launch.p/seatd-launch_seatd-launch.c.o: in function `main':
seatd-launch.c:(.text.startup+0x8a): undefined reference to `fork'

Fixes:
 - http://autobuild.buildroot.org/results/5219b6dac714886c7fa4d3687a13b9dff8338df2

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>