package/swupdate: fix musl build
Fix the following musl build failure raised since bump to version
2023.05 in commit b86542085df87da91057017b17f261a213bfd918 and
https://github.com/sbabic/swupdate/commit/8228b1390632195158f4387d7aae659ebd6f1469:

In file included from core/bootloader.c:9:
include/util.h:210:23: error: unknown type name 'mode_t'
  210 | int mkpath(char *dir, mode_t mode);
      |                       ^~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/e545f294c7f032fd7434fdb91aa18a38b2e19038

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>