package/libpwquality: fix build with python 3.12
Switch from distutils to setuptools to avoid the following build failure
raised since bump of python to version 3.12.1 in commit
36e635d2d5c0166476858aa239ccbe78e8f2af14:

Traceback (most recent call last):
  File "/home/fabrice/buildroot/output/build/libpwquality-1.4.5/python/setup.py", line 9, in <module>
    from distutils.core import setup, Extension
ModuleNotFoundError: No module named 'distutils'

Fixes: 36e635d2d5c0166476858aa239ccbe78e8f2af14
No autobuilder failures (yet)

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>