package/python-aiohttp: fix async_timeout 4.0.0 compatibility
We need to backport an upstream patch adding async_timeout 4.0.0
compatibility since we are still on aiohttp version 3.7.4.post0.

Fixes:
>>> import aiohttp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/aiohttp/__init__.py", line 6, in <module>
  File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 35, in <module>
  File "/usr/lib/python3.9/site-packages/aiohttp/http.py", line 7, in <module>
  File "/usr/lib/python3.9/site-packages/aiohttp/http_parser.py", line 15, in <module>
  File "/usr/lib/python3.9/site-packages/aiohttp/helpers.py", line 667, in <module>
TypeError: function() argument 'code' must be code, not str

Signed-off-by: James Hilliard <james.hilliard1@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>