package/iproute2: bump to version 6.13.0
Changelog - https://github.com/iproute2/iproute2/compare/v6.12.0...v6.13.0

Drop 0001-Fix-implicit-declaration-of-function-htobe64-in-gcc-.patch
Upstream commit - https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=c8b3ecc22ed0edaf0259eaf7d1a5c04f300ad6e4

Drop 0002-Fix-implicit-declaration-of-function-basename-in-gcc.patch
Upstream commit - https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=fa3949b792e275f75d7d6200dc2036ef7fff8816

Note: Since commit [1] "package/iproute2: bump to version 6.12.0",
iproute2 can fail to build with musl libc with error:

    iplink.c: In function 'iplink_parse':
    iplink.c:663:43: error: 'PATH_MAX' undeclared (first use in this function); did you mean 'AF_MAX'?
      663 |                                 char path[PATH_MAX];
          |                                           ^~~~~~~~

This is fixed with iproute2 commit [2] included in this 6.13.0 version.

Fixes:
- https://autobuild.buildroot.org/results/029493e02f5c2858fc987ba7a4c8fe53deb27017/
- and many others...

[1] https://gitlab.com/buildroot.org/buildroot/-/commit/4d40998db891e9967f85fc1e6dd3c2c740ea7b08
[2] https://github.com/iproute2/iproute2/commit/7e23da91fca6e5dedeb32a7d308cf20982e897c3

Signed-off-by: Akhilesh Nema <nemaakhilesh@gmail.com>
[Julien: add a commit log comment about the fixed build failures]
Signed-off-by: Julien Olivain <ju.o@free.fr>