package/fluxbox: fix build with gcc 11
Fix the following build failure with gcc 11:

util/fluxbox-remote.cc: In function 'int main(int, char**)':
util/fluxbox-remote.cc:76:32: error: ordered comparison of pointer with integer zero ('unsigned char*' and 'int')
   76 |             && text_prop.value > 0
      |                ~~~~~~~~~~~~~~~~^~~

Fixes:
 - http://autobuild.buildroot.org/results/6e718bb662aa4961ea264eb81e4b7e7b20485e30

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit b1fce2f871c472de1acf25ae2a663e61f4e921f1)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>