package/iwd: fix musl build
Fix the following build failure with musl raised since bump to version
1.18 in commit 1a7be12e1e10cc09e3a28a8d04a352bbbb63ba3a:

src/netconfig.c: In function 'netconfig_ipv6_to_string':
src/netconfig.c:188:18: error: 'struct in6_addr' has no member named '__in6_u'; did you mean '__in6_union'?
  188 |  memcpy(in6_addr.__in6_u.__u6_addr8, addr, 16);
      |                  ^~~~~~~
      |                  __in6_union

Fixes:
 - http://autobuild.buildroot.org/results/2c4e6cf22e6fb5582470930241904878070f1144

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>