package/agentpp: fix build when BR2_PACKAGE_SNMPPP_SNMPV3 disabled
Agent++ 4.3.1 does not build if SNMPv3 is disabled due to incorrect #ifdef
clauses, esulting in errors such as:

  ../include/agent_pp/notification_originator.h:232:39: error: 'snmpCommunityEntry' has not been declared
           void set_snmp_community_entry(snmpCommunityEntry* communityEntryRef) {
                                         ^
  ../include/agent_pp/notification_originator.h:296:32: error: 'nlmLogEntry' has not been declared
           void set_nlm_log_entry(nlmLogEntry* nlmLogEntryRef) {
                                  ^
  ../include/agent_pp/notification_originator.h:321:9: error: 'nlmLogEntry' does not name a type
           nlmLogEntry*            _nlmLogEntry;
           ^

Fixes:
  http://autobuild.buildroot.net/results/d7a5fa5ba4ab6c9da23fcc93bf766be9ca630af3/
  http://autobuild.buildroot.net/results/40ce9bc4bed267dc762a0282a8da0ad1514ad7a8/
  ...

Fixes: 88355e967fef ("package/agentpp: bump version to 4.3.1")
Signed-off-by: Luca Ceresoli <luca@lucaceresoli.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>