package/s390-tools: disable cargo
Set HAVE_CARGO=0 to avoid the following build failures raised since bump
to version 2.29.0 in commit 68df20336664d4d0b1a9d8d0285d23eba631845a and
https://github.com/ibm-s390-linux/s390-tools/commit/e6add997ebbcd967734391da8a8987c7926e168f:

error: could not compile `pvsecret` (bin "pvsecret") due to previous error

[...]

ERROR: architecture for "/usr/bin/pvsecret" is "AArch64", should be "IBM S/390"

Fixes: 68df20336664d4d0b1a9d8d0285d23eba631845a
 - http://autobuild.buildroot.org/results/22035cb4d8e251f9930a7d529b91b128919252bb
 - http://autobuild.buildroot.org/results/99be6d3b2bab7c952ce02853f54924c5219aecc1

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 120cb19056dc22b11d921714dc4e2ac94b84242f)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>