package/postgresql: fix build without NPTL
Fix the following build failure without NPTL raised since bump to
version 14.1 in commit c9bd02911565819789120370178e82da5dfbacc0 and
https://github.com/postgres/postgres/commit/44bf3d5083e151d772c5d6f656e3e162f573dced:

In file included from pthread_barrier_wait.c:16:
../../src/include/port/pg_pthread.h:31:3: error: conflicting types for 'pthread_barrier_t'
   31 | } pthread_barrier_t;
      |   ^~~~~~~~~~~~~~~~~
In file included from /home/autobuild/autobuild/instance-11/output-1/host/arc-buildroot-linux-uclibc/sysroot/usr/include/bits/uClibc_stdio.h:114,
                 from /home/autobuild/autobuild/instance-11/output-1/host/arc-buildroot-linux-uclibc/sysroot/usr/include/stdio.h:71,
                 from ../../src/include/c.h:59,
                 from pthread_barrier_wait.c:14:
/home/autobuild/autobuild/instance-11/output-1/host/arc-buildroot-linux-uclibc/sysroot/usr/include/bits/pthreadtypes.h:135:3: note: previous declaration of 'pthread_barrier_t' was here
  135 | } pthread_barrier_t;
      |   ^~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/70acbe121236ef0905c4466d4f7a0839723d2c49

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>