package/zip: fix musl compile
For musl toolchain timezone.c needs time.h include.

Fixes:
  http://autobuild.buildroot.net/results/77346a2cdb9eeef661527fb9566019f3cd1b82c9

  In file included from util.c:28:
  timezone.c: In function 'mktime':
  timezone.c:644:18: error: dereferencing pointer to incomplete type 'struct tm'
       save_isdst = tm->tm_isdst;

  timezone.c:661:11: warning: implicit declaration of function 'localtime'; did you mean 'dostime'? [-Wimplicit-function-declaration]
       ltm = localtime(&then);

  timezone.c:661:9: warning: assignment to 'struct tm *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
       ltm = localtime(&then);

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 376d2e8564822cc9bea8644859532949b2f87b05)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>