package/igt-gpu-tools: depends on little endian
Buildroot commit f9a91bf60e35617157b950eea05fc6f6144d650c bumped
igt-gpu-tools to 2.3 which includes upstream commit
https://gitlab.freedesktop.org/drm/igt-gpu-tools/-/commit/ff3b7435bc56e34cf8b97c44ff32b7a1cc5dab7a
which limits the package to little endian archs causing build errors
on big endian archs:

In file included from ../lib/igt_panthor.c:5:
../lib/igt_panthor.h:61:2: error: #error "big endian not supported"
   61 | #error "big endian not supported"

Fixes:

  https://autobuild.buildroot.org/results/e3faeba1bff3d0e781032ddc9a760f34a9bf5714/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>