package/diffutils: Fix build on ppc32 with musl
sigsegv.c: In function 'sigsegv_handler':
 sigsegv.c:225:75: error: 'mcontext_t' has no member named 'uc_regs';
 did you mean 'gregs'?

  ((ucontext_t *) ucp)->uc_mcontext.uc_regs->gregs[1]

Musl defines pt_regs differently to glibc. Backport a patch from
upstream gnulib (the source for this file in diffutils).

Fixes:

 http://autobuild.buildroot.net/results/1b40146436eb2b3500d0d8faef96b3374f8e5cda/

Signed-off-by: Joel Stanley <joel@jms.id.au>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 2bee0f34598d64a983a30ab7999bf4305f957377)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>