package/cegui: fix build with libxml2 >= 2.12
Fix the following build failure raised since bump of libxml2 to version
2.12.1 in commit d8ac52108c12f0fcc9641b63e7922009270f96c6:

/home/buildroot/autobuild/instance-1/output-1/build/cegui-00b4e1fe174da53b7ed726ab5970ba51bd5b5ee0/cegui/src/XMLParserModules/Libxml2/XMLParser.cpp: In member function 'virtual void CEGUI::LibxmlParser::parseXML(CEGUI::XMLHandler&, const CEGUI::RawDataContainer&, const CEGUI::String&, bool)':
/home/buildroot/autobuild/instance-1/output-1/build/cegui-00b4e1fe174da53b7ed726ab5970ba51bd5b5ee0/cegui/src/XMLParserModules/Libxml2/XMLParser.cpp:111:40: error: invalid conversion from 'const xmlError*' {aka 'const _xmlError*'} to 'xmlError*' {aka '_xmlError*'} [-fpermissive]
  111 |         xmlError* err = xmlGetLastError();
      |                         ~~~~~~~~~~~~~~~^~
      |                                        |
      |                                        const xmlError* {aka const _xmlError*}

Fixes: d8ac52108c12f0fcc9641b63e7922009270f96c6
 - http://autobuild.buildroot.org/results/b239b7b03542311e311e4612e9b811c154302a6e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>