package/gstreamer1/gst1-plugins-bad: explicitly enable _GNU_SOURCE for festival/glibc 2.18
festival fails to built with glibc 2.18 due to fopen and the h_addr field in
struct hostent:

../gst/festival/gstfestival.c: In function 'gst_festival_chain':
../gst/festival/gstfestival.c:273:3: warning: implicit declaration of function 'fdopen' [-Wimplicit-function-declaration]
   fd = fdopen (f, "wb");
   ^
../gst/festival/gstfestival.c:273:6: warning: assignment makes pointer from integer without a cast [enabled by default]
   fd = fdopen (f, "wb");
      ^
../gst/festival/gstfestival.c: In function 'festival_socket_open':
../gst/festival/gstfestival.c:367:45: error: 'struct hostent' has no member named 'h_addr'
     memmove (&serv_addr.sin_addr, serverhost->h_addr, serverhost->h_length);
                                             ^

Both of which are hidden behind _GNU_SOURCE in glibc 2.18, so enable that to
fix this build issue.

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>