package/python3-cffi: bump version to 1.14.6
- the last version bump of package/python-cffi (790c10d) ignored
  the comment 'Please keep in sync with package/python3-cffi/python3-cffi.mk',
  so catch up now

Fixes:

  ERROR: No hash found for cffi-1.14.2.tar.gz

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 777b1f91353ddae3a32d2dccfdbbfca853bf30f9)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>