package/flashrom: fix libftdi build
flashrom depends on libftdi1 since bump to version 1.3.0 in commit
073b0fc9c1fe9945eccf4b792b948633aae9a9b8:

Dependency libftdi1 found: no
[...]
/home/autobuild/autobuild/instance-7/output-1/host/lib/gcc/mips64el-buildroot-linux-gnu/12.3.0/../../../../mips64el-buildroot-linux-gnu/bin/ld: libflashrom.a(ft2232_spi.o): in function `send_buf':
ft2232_spi.c:(.text+0x20): undefined reference to `ftdi_write_data'

Fixes:
 - http://autobuild.buildroot.org/results/11fae0933b38d82f15fec37e78298df232321bcd

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>