package/libcamera-apps: bump to version 1.5.0
- Use official tarball
- Switch to meson-package
- libcamera-apps unconditionally uses linux/dma-heap.h since version
  1.3.0 and
  https://github.com/raspberrypi/rpicam-apps/commit/11338687635cc5564c348c2f60c8c58c5779151d
  which is only available since kernel >= 5.5 and
  https://github.com/torvalds/linux/commit/a69b0e855d3fd278ff6f09a23e1edf929538e304
- This bump will fix the following build failure raised since bump of
  libcamera to version 0.3.0 in commit
  82efc2faa923e8881748738963be1fbe3cb2bb45:

/workdir/instance-1/output-1/build/libcamera-apps-1.2.1/core/libcamera_app.cpp: In member function 'void LibcameraApp::ConfigureViewfinder()':
/workdir/instance-1/output-1/build/libcamera-apps-1.2.1/core/libcamera_app.cpp:327:25: error: 'class libcamera::CameraConfiguration' has no member named 'transform'
  327 |         configuration_->transform = options_->transform;
      |                         ^~~~~~~~~

It shall be noted that upstream changed its name from libcamera-apps to
rpicam-apps perhaps the package shall also be renamed on buildroot side

Fixes: 82efc2faa923e8881748738963be1fbe3cb2bb45
 - http://autobuild.buildroot.org/results/18bb6d9c88c1a813a350658b251293744e161916

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>