package/lmdb: fix static build
Fix the following static build failure raised since the addition of the
package in commit eb60c4054c25129d78651a66d1e7554aff04767f:

__uClibc_main.c:(.text+0x15c): undefined reference to `__fini_array_start'

Fixes: eb60c4054c25129d78651a66d1e7554aff04767f
 - http://autobuild.buildroot.org/results/e2bc8c35a10b6513c5605954e93b5b8a1ec7654b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[yann.morin.1998@free.fr:
  - s/LMBD/LMDB/
  - drop LMBD_MAKE_OPTS, directly pass ILIBS
]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>