package/hiawatha: disable ASM if needed
Disable ASM as already done in mbedtls package to avoid the following
build failure raised since commit
4e36e8f2081a66f477dd038793082045876d65ee:

In file included from /home/buildroot/autobuild/instance-2/output-1/build/hiawatha-11.1/mbedtls/library/bignum.c:41:
/home/buildroot/autobuild/instance-2/output-1/build/hiawatha-11.1/mbedtls/library/bignum.c: In function 'mpi_mul_hlp':
/home/buildroot/autobuild/instance-2/output-1/build/hiawatha-11.1/mbedtls/library/bn_mul.h:86:13: error: the register 'hi' cannot be clobbered in 'asm' for the current target
   86 | #define asm __asm
      |             ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/5436b44777c5d417ae427b99602f516fd8f9489d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>