package/python-setuptools-scm-git-archive: drop package
python-setuptools-scm-git-archive is obsolete as
python-setuptools-scm >= 7.0.0 supports Git archives by itself.

Moreover, it raises the following build failure without pip since its
addition in commit 9359325c6081df89ff57667cb49e0d12cd553b97:

/nvmedata/autobuild/instance-3/output-1/per-package/host-python-setuptools-scm-git-archive/host/bin/python: No module named pip
Traceback (most recent call last):
  File "/nvmedata/autobuild/instance-3/output-1/per-package/host-python-setuptools-scm-git-archive/host/lib/python3.10/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/nvmedata/autobuild/instance-3/output-1/per-package/host-python-setuptools-scm-git-archive/host/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nvmedata/autobuild/instance-3/output-1/per-package/host-python-setuptools-scm-git-archive/host/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpaxobatcs', '--quiet', 'typing-extensions']' returned non-zero exit status 1.

Fixes:
 - http://autobuild.buildroot.org/results/d05e412170c427e4f210da164c783b3527f15892
 - http://autobuild.buildroot.org/results/50f80cfabccbe5c75cd889ce6af2b418e376d4e5

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>