package/bitcoin: broken on m68k
Buildroot commit a3a88ff1c85ba0067af1028bc232f8f61b628979 bumped bitcoin
to version 26.0 which includes upstream commit
https://github.com/bitcoin/bitcoin/commit/b8401c3281978beed6198b2f9782b6a8dd35cbd7
causing an assertion on m68k:

/home/thomas/autobuild/instance-7/output-1/build/bitcoin-30.0/src/support/allocators/pool.h:92:36:
 error: static assertion failed: Units of size ELEM_SIZE_ALIGN need to
 be able to store a ListNode
   92 |     static_assert(sizeof(ListNode) <= ELEM_ALIGN_BYTES, "Units
      |                   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
 of size ELEM_SIZE_ALIGN need to be able to store a ListNode");

/home/thomas/autobuild/instance-7/output-1/build/bitcoin-30.0/src/support/allocators/pool.h:92:36:
 note: the comparison reduces to '(4 <= 2)'

To fix the problem we disable bitcoin on m68k.

Fixes:
30.0: https://autobuild.buildroot.net/results/268/2688e4a2aa8dc34343f0218fd6727d0ae3adb132/
26.0: https://autobuild.buildroot.net/results/fb0/fb05401c7de289e0f87f5c9e3a7f92f5589b590b/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>