package/libglib2: fix atomic handling
Correctly fix atomic handling to avoid the following build failure with
all users of libglib2 (e.g. gdk-pixbuf) raised since bump to version
2.76.1 in commit 3f9622fe3d85b4d9f734b879abc1d485afea19b2:

/usr/lib/libglib-2.0.a(gthread-posix.c.o): in function `g_mutex_trylock':
gthread-posix.c:(.text+0xda8): undefined reference to `__atomic_compare_exchange_4'

Fixes:
 - http://autobuild.buildroot.org/results/24a358869b98d83ab374c7c3a185ced450064d35

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 929bffbf4bf8fcb91bda446777f907f32c782656)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>