package/ibrcommon: fix build with gcc 11
Fix the following build failure with gcc 11:

In file included from ../../ibrcommon/data/BLOB.h:25,
                 from BLOB.cpp:22:
../../ibrcommon/thread/Mutex.h:43:40: error: ISO C++17 does not allow dynamic exception specifications
   43 |                 virtual void trylock() throw (MutexException) = 0;
      |                                        ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/7a9a4319916efe8cd7e04b8686a9ae0b233b017a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 867e7a040ce1907cdc74d2040845ef155ede57d1)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>