package/systemd: fix build with gcc >= 13
Fix the following build failure with gcc >= 13:

In file included from ../src/basic/macro.h:446,
                 from ../src/basic/alloc-util.h:10,
                 from ../src/shared/install.c:12:
../src/shared/install.c: In function ‘install_changes_dump’:
../src/shared/install.c:444:64: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
  444 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, unit %s does not exist.",
      |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/e0d6b7d41fefec539a17a3ef5c89c192ce29fd04

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>
(cherry picked from commit 066c3e67d7f117f7810597e1ab36e2346fe8f7c2)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>