package/python-aenum: fix pyc compilation error
_py2.py uses syntax not compatible with Python3. Remove _py2.py
to avoid the following compilation error:

error:   File "/usr/lib/python3.10/site-packages/aenum/_py2.py", line 5
    raise exc, None, tb
             ^
SyntaxError: invalid syntax

Signed-off-by: Yegor Yefremov <yegorslists@googlemail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit d7db5af34f25cf9f3e8577c75ff290495c5724c6)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>