package/log4cxx: fix build without wchar
Fix the following build failure without wchar raised since bump to
version 0.12.0 in commit 83a0e8dea203dc37c6c207a36b3f46160578dcc2:

/home/buildroot/autobuild/instance-0/output-1/build/log4cxx-0.12.0/src/main/include/log4cxx/helpers/transcoder.h:113:33: error: 'wstring' in namespace 'std' does not name a type
  113 |   static void decode(const std::wstring& src, LogString& dst);
      |                                 ^~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/7d0297b071df06bc312b9927396021aa6fe401f4

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>