package/librelp: select BR2_PACKAGE_LIBOPENSSL_ENGINES
librelp unconditionally calls the (deprecated) ENGINE_* logic in
libopenssl resulting in a build failure when
!BR2_PACKAGE_LIBOPENSSL_ENGINES since commit
623d3bbe43e9193aa8e3395367d01af59071b859:

tcp.c: In function 'relpTcpExitTLS_ossl':
tcp.c:1992:17: error: implicit declaration of function 'ENGINE_cleanup'; did you mean 'EVP_PBE_cleanup'? [-Wimplicit-function-declaration]
 1992 |                 ENGINE_cleanup();
      |                 ^~~~~~~~~~~~~~
      |                 EVP_PBE_cleanup

Fixes: 623d3bbe43e9193aa8e3395367d01af59071b859
 - http://autobuild.buildroot.org/results/68a1e94e077d8d57690a2543e557ba3f2974b03e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>