package/mdevd: fix build with glibc >= 2.43
Buildroot commit 227378b5930b681c79a13476ae60a98753a98a03 bumped glibc
to 2.43 causing a build error in mdevd:

src/mdevd/mdevd.c: In function 'act_on_event':
src/mdevd/mdevd.c:797:36: error: assignment of read-only location
 '*(const char *)strchr(ud->devname, 10)'
  797 |         *strchr(ud->devname, '\n') = 0 ;

Add upstream commit to fix the problem.

Fixes:
https://autobuild.buildroot.net/results/92b/92b9b307996a44b66dc3f7f7d35dd74816b62480/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>