package/brcm-patchram-plus: bump to latest git commit
This bump will fix the following build failure with gcc >= 14:

main.c: In function 'read_event':
main.c:715:25: error: implicit declaration of function 'read'; did you mean 'fread'? [-Wimplicit-function-declaration]
  715 |         while ((count = read(fd, &buffer[i], len)) < len) {
      |                         ^~~~
      |                         fread

Fixes:
 - http://autobuild.buildroot.org/results/67965a5245c3d98d683e2c788352bf7c1cf4f00e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit a0ebcac06b76c4f3c6b7c2d2382ddfeee85d5c1d)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>