package/postgresql: bump version to 18.1
Release notes:
https://www.postgresql.org/docs/release/18.0/
https://www.postgresql.org/docs/release/18.1/

Please note that upgrading a PostgreSQL server to a newer major version
requires a manual upgrade not provided by buildroot:
https://www.postgresql.org/docs/18/upgrading.html

Removed configure options for spinlocks:
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=e25626677f8076eb3ce94586136c5464ee154381

Upstream removed support for toolchains not providing atomics support:
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=81385261362962deb9861b39b509aeffe213721d

Added dependency to !BR2_sparc to disable build with defconfig
bootlin-sparc-uclibc to fix a build error:

../src/include/port/atomics.h:99:2: error:
 #error "could not find an implementation of pg_atomic_uint32"

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>