package/libevent: fix build with libressl >= 3.5.0
Fix the following build failure with libressl raised since bump to
version 3.5.2 in commit 8b216927db080b38fdbf1f8b025b6f90a89d4bc2:

In file included from bufferevent_openssl.c:68:
bufferevent_openssl.c: In function 'bio_bufferevent_free':
openssl-compat.h:44:28: error: invalid use of incomplete typedef 'BIO' {aka 'struct bio_st'}
   44 | #define BIO_get_init(b) (b)->init
      |                            ^~
bufferevent_openssl.c:124:7: note: in expansion of macro 'BIO_get_init'
  124 |   if (BIO_get_init(b) && BIO_get_data(b))
      |       ^~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/273f9aa354a08ef3af6140b8dec086408bf5d574

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>