package/igt-gpu-tools: needs NPTL threads
With classic thread library, the build fails with:

../lib/igt_kmod.c:1090:21: error: implicit declaration of function 'pthread_mutexattr_setrobust'; did you mean 'pthread_mutexattr_settype'? [-Werror=implicit-function-declaration]

igt-gpu-tools needs NPTL threads.

Fixes:

  http://autobuild.buildroot.net/results/85311ce68ae1fff771ca00b434be1c4f8453d357/

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
Signed-off-by: Julien Olivain <ju.o@free.fr>
(cherry picked from commit 80e0f643e88afeccb69b679fe55677d8065445d8)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>