package/libfreefare: bump to latest git commit
This bump will fix the following build failure with gcc >= 14 thanks to
https://github.com/nfc-tools/libfreefare/commit/494233d33b3a9d21da1bb0f1c59606820afe4691

mifare_desfire_crypto.c: In function 'cmac':
mifare_desfire_crypto.c:139:23: error: implicit declaration of function 'malloc' [-Wimplicit-function-declaration]
  139 |     uint8_t *buffer = malloc (padded_data_length (len, kbs));
      |                       ^~~~~~
mifare_desfire_crypto.c:69:1: note: include '<stdlib.h>' or provide a declaration of 'malloc'
   68 | #include "freefare_internal.h"
  +++ |+#include <stdlib.h>
   69 |

Fixes:
 - http://autobuild.buildroot.org/results/778be216f62b8c2e05aba1b3e297dab0c6c6ccd0

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>