package/qt5/qt5webkit: fix WebCore compatibility issue with updated libxml2
qt5webkit build currently breaks on the following error:

XSLStyleSheetLibxslt.cpp:148:129: error: invalid conversion from ‘void (*)(void*, xmlError*)’ {aka ‘void (*)(void*, _xmlError*)’} to ‘xmlStructuredErrorFunc’ {aka ‘void (*)(void*, const _xmlError*)’} [-fpermissive]
  148 |     XMLDocumentParserScope scope(cachedResourceLoader(), XSLTProcessor::genericErrorFunc, XSLTProcessor::parseErrorFunc, console);
      |                                                                                                                                 ^
      |                                                                                                                                 |
      |                                                                                                                                 void (*)(void*, xmlError*) {aka void (*)(void*, _xmlError*)}

This error is due to an API update in libxml2, enforcing const on more
struct in version 2.12.0 (see [1]). Buildroot now tracks v2.12.5.
Upstream Webkit project has already issued the corresponding fix ([2]),
which updates corresponding internal prototypes depending on libxml2
version, but the qt5webkit version tracked in buildroot does not integrate
the corresponding Webkit version.

Fix this build issue by bringing the upstream patch "as is" from Webkit

No autobuilder references because this build error was hidden by
another build error fixed in a previous patch.

[1] https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.12.0
[2] https://github.com/WebKit/WebKit/commit/1bad176b2496579d760852c80cff3ad9fb7c3a4b

Signed-off-by: Alexis Lothoré <alexis.lothore@bootlin.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit e24a11738896118870037d89ccd64d2fa331e15e)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>