package/rng-tools: fix musl build
Fix the following musl build failure raised since bump to version 6.14
in commit 5292d1cf9ad0605cc264fedc75c1b9a169aa183b:

/home/buildroot/autobuild/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/i586-buildroot-linux-musl/9.3.0/../../../../i586-buildroot-linux-musl/bin/ld: rngd-rngd_jitter.o: in function `rngd_notime_start':
rngd_jitter.c:(.text+0xdc2): undefined reference to `pthread_attr_setaffinity_np'

Fixes:
 - http://autobuild.buildroot.org/results/3ec7df86856aa9bee2f18a8faa44fd58bc8a6657

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit d94e2b6dd4f291a77bbfd06eabb7ce85c9bb6aa9)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>