package/lxc: fix systemd build
Fix the following systemd build failure raised since bump to version
5.0.1 in commit db19998035701d08bf1b5fd366e0b5aa9adb8e57:

../src/lxc/cgroups/cgfsng.c: In function 'unpriv_systemd_create_scope':
../src/lxc/cgroups/cgfsng.c:1234:104: error: incompatible type for argument 10 of 'sd_bus_call_method_asyncv'
 r = sd_bus_call_method_asyncv(bus, NULL, DESTINATION, PATH, INTERFACE, "Subscribe", NULL, NULL, NULL, NULL);
                                                                                                       ^~~~

Fixes:
 - https://gitlab.com/buildroot.org/buildroot/-/jobs/3282261449

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>