board/octavo: Fix Linux compilation
Since commit dc0f7215c604e ("package/gcc: switch to 13.x as default"),
the Linux kernel is failing to build with this output:

In file included from ./include/linux/kernel.h:10,
                 from drivers/ata/libahci.c:35:
drivers/ata/libahci.c: In function ‘ahci_led_store’:
./include/linux/compiler.h:348:45: error: call to ‘__compiletime_assert_1154’ declared with attribute error: BUILD_BUG_ON failed: sizeof(_s) > sizeof(long)
   348 |         _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)

Fix it by importing Linux upstream patch.

Signed-off-by: Kory Maincent <kory.maincent@bootlin.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>