package/cloop: fix build with gcc >= 9
Fix the following build failure with gcc >= 9 (and -std=c++17):

./file.h:70:43: error: ISO C++17 does not allow dynamic exception specifications
   70 | bool file_exists(const std::string& file) throw (error);
      |                                           ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/8320edd448cd1f7c14a65734f63a2df5d4b0d442

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit 7e147e778fc3397cd2a069c8127fa4d2cc6c0355)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>