package/trace-cmd: needs NPTL
trace-cmd needs NPTL since bump to version 2.9.1 in commit
0e1231a3c0719269ab3546defe4b1fb0f1f5d7d2 and
https://git.kernel.org/pub/scm/utils/trace-cmd/trace-cmd.git/commit/?id=08b9d5076455c93c997376c8089ee12b9071785b:

/nvmedata/autobuild/instance-24/output-1/host/lib/gcc/i586-buildroot-linux-uclibc/10.3.0/../../../../i586-buildroot-linux-uclibc/bin/ld: /nvmedata/autobuild/instance-24/output-1/build/trace-cmd-2.9.7/lib/trace-cmd/libtracecmd.a(trace-timesync.o): in function `tracecmd_tsync_with_host':
trace-timesync.c:(.text+0x12e1): undefined reference to `pthread_setaffinity_np'

Fixes:
 - http://autobuild.buildroot.org/results/9a88aaf92760b34958ef5b1708de83e46ccdb587

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit df3cc4bb1c91114d29e48d8bc8206adcc35e9b9c)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>