package/libgphoto2: fix build with gcc >= 14
The commit adds a backported upstream patch to fix the following build
failure:

jl2005c/jl2005bcd_decompress.c: In function 'jl2005bcd_decompress':
jl2005c/jl2005bcd_decompress.c:161:46: error: passing argument 3 of 'jpeg_mem_dest' from incompatible pointer type [-Wincompatible-pointer-types]
  161 |         jpeg_mem_dest (&cinfo, &jpeg_header, &jpeg_header_size);
      |                                              ^~~~~~~~~~~~~~~~~
      |                                              |
      |                                              long unsigned int *

The same fix was merged in master with commit d2ad5b883342
("package/libgphoto2: fix build with gcc >= 14") for version 2.5.33.
The patch has been adapted to version 2.5.27, where the libjpeg check
lives in configure.ac rather than in gphoto-m4/gp-libjpeg.m4.

Fixes:
- https://autobuild.buildroot.org/results/09f2756d3d26a9e27ef596428c84d37c5d2d5bb2

Signed-off-by: Dario Binacchi <dario.binacchi@amarulasolutions.com>
(alternative to commit d2ad5b883342b92c354c8a110ffbaf1ca7dda20f)
Signed-off-by: Raphaël Mélotte <raphael.melotte@mind.be>