boot/shim: add patch to fix builds with -O3 / -Ofast
Fixes:
https://autobuild.buildroot.net/results/c6ad52a048ba030bb1adc3ee1aeb69ef880cbdad/
https://autobuild.buildroot.net/results/136d1afc2ecacea6a4e12b915073e3eaf5c8ca01/
https://autobuild.buildroot.net/results/a3f293371f6bd0125dc7baa5afb64373e4383f4f/

Shim contains an embedded copy of OpenSSL.  Depending on the optimization
level, an error is triggered from make_kn():

In function 'make_kn',
    inlined from 'make_kn' at crypto/cmac/cmac.c:81:13,
    inlined from 'CMAC_Init' at crypto/cmac/cmac.c:205:9:
crypto/cmac/cmac.c:92:20: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
   92 |         k1[bl - 1] ^= bl == 16 ? 0x87 : 0x1b;
      |         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
crypto/cmac/cmac.c: In function 'CMAC_Init':
crypto/cmac/cmac.c:69:19: note: at offset 2147483647 into destination object 'k1' of size 32
   69 |     unsigned char k1[EVP_MAX_BLOCK_LENGTH];
      |                   ^~

Fix it by including a patch submitted upstream which backports an upstream
OpenSSL change to workaround this.

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
Signed-off-by: Julien Olivain <ju.o@free.fr>
(cherry picked from commit 96408d1313bface05f5dcc9e275eb118fce87fa9)
Signed-off-by: Thomas Perale <thomas.perale@mind.be>