package/libargtable2: Remove package
The last release dates back to 2012[1], no other package depends on
libargtable2 and the successor package libargtable3 is not backward-
compatible: https://www.argtable.org/

Due to build errors with newer gcc

/home/autobuild/autobuild/instance-15/output-1/host/microblazeel-buildroot-linux-musl/sysroot/usr/include/unistd.h:127:5:
 error: conflicting types for 'getopt'; have 'int(int,  char * const*, const char *)'
  127 | int getopt(int, char * const [], const char *);

we remove the package from buildroot.

Fixes:
https://autobuild.buildroot.net/results/e6c/e6c039cb92fecbd93a91d2d1dab68e803875e62c/

[1] https://sourceforge.net/projects/argtable/files/argtable/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>