package/python-pymupdf: add missing python-zlib dependency
It turns out that python-pymupdf doesn't require zlib directly, but it
does require the zlib python module.

This fixes the following runtime error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/fitz/__init__.py", line 22, in <module>
  File "/usr/lib/python3.11/site-packages/fitz/fitz.py", line 3402, in <module>
  File "/usr/lib/python3.11/gzip.py", line 9, in <module>
ModuleNotFoundError: No module named 'zlib'

Signed-off-by: Raphaël Mélotte <raphael.melotte@mind.be>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>