package/libcamera-apps: link with -latomic if needed
Link with -latomic if needed to avoid the following build failure raised
since the addition of the package in commit
7227d005d2435ec7b38995a6247d233ddb5ba365:

/home/buildroot/autobuild/instance-2/output-1/host/opt/ext-toolchain/bin/../lib/gcc/sparc-buildroot-linux-uclibc/10.3.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: CMakeFiles/libcamera-still.dir/libcamera_still.cpp.o: undefined reference to symbol '__atomic_fetch_sub_4@@LIBATOMIC_1.0'

Fixes:
 - http://autobuild.buildroot.org/results/b20465140f3a5281f9b586f442b67fd400e7184a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>