package/gnuradio: fix build with fmt >= 11.x
gnuradio is failing to build since commit 6b86f076c3 "package/fmt: bump
to version 11.0.1" with output:

    /build/gnuradio-3.10.7.0/gr-blocks/lib/message_debug_impl.cc: In member function 'void gr::blocks::message_debug_impl::log(const pmt::pmt_t&)':
    /build/gnuradio-3.10.7.0/gr-blocks/lib/message_debug_impl.cc:65:44: error: 'join' is not a member of 'fmt'
       65 |                                       fmt::join(begin, begin + output_length, " "),
          |                                            ^~~~

This commit adds a backported upstream patch to fix the issue.

Fixes:
https://gitlab.com/buildroot.org/buildroot/-/jobs/7540345284
http://autobuild.buildroot.org/results/4c92949ef74a119d9a70e4fdd55af05a66580b0c/

Signed-off-by: Julien Olivain <ju.o@free.fr>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>