package/stunnel: doesn't build with libressl
Fix the following build failure with libressl:

In file included from tls.c:39:
prototypes.h:774:8: error: unknown type name 'CRYPTO_RWLOCK'
  774 | extern CRYPTO_RWLOCK *stunnel_locks[STUNNEL_LOCKS];
      |        ^~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/c48ba8e71dc917b2e11051088dd252be81b3609f

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit e4032672736614397c803584ba7bb8a20ae1896e)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>