board/qemu/patches/arm-trusted-firmware: add v2.10 hash
Fixes https://gitlab.com/buildroot.org/buildroot/-/jobs/7644930127
ERROR: No hash found for arm-trusted-firmware-v2.10-git4.tar.gz

Commit d037d9c2d63e9cd47b (configs/qemu: Update defconfigs to Linux 6.6.32)
enabled BR2_DOWNLOAD_FORCE_CHECK_HASHES, but forgot to take into
consideration that qemu_aarch64_ebbr_defconfig uses arm-trusted-firmware
v2.10 since commit 73813c56c8bb (configs/qemu_{arm, aarch64}_ebbr: bump
Linux, U-Boot and TF-A).

Add the hash to fix the build.

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>