package/python-pytest: fix dependency on zlib
tests.package.test_python_pytest.TestPythonPy3Pytest runtime tests fails
now with following error:

  ======================================================================
  FAIL: test_run (tests.package.test_python_pytest.TestPythonPy3Pytest.test_run)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/buildroot/support/testing/tests/package/test_python.py", line 137, in test_run
      self.run_sample_scripts()
    File "/buildroot/support/testing/tests/package/test_python_pytest.py", line 18, in run_sample_scripts
      self.assertRunOk(cmd, timeout=self.timeout)
    File "/buildroot/support/testing/infra/basetest.py", line 89, in assertRunOk
      self.assertEqual(
  AssertionError: 1 != 0 :
  Failed to run: python -m pytest sample_python_pytest.py
  output was:
    Traceback (most recent call last):
      File "<frozen runpy>", line 189, in _run_module_as_main
      File "<frozen runpy>", line 148, in _get_module_details
      File "<frozen runpy>", line 112, in _get_module_details
      File "/usr/lib/python3.11/site-packages/pytest/__init__.py", line 5, in <module>
      File "/usr/lib/python3.11/site-packages/_pytest/_code/__init__.py", line 2, in <module>
      File "/usr/lib/python3.11/site-packages/_pytest/_code/code.py", line 36, in <module>
      File "/usr/lib/python3.11/site-packages/pluggy/__init__.py", line 16, in <module>
      File "/usr/lib/python3.11/site-packages/pluggy/_manager.py", line 10, in <module>
      File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 8, in <module>
      File "/usr/lib/python3.11/zipfile.py", line 6, in <module>
    ImportError: libz.so.1: cannot open shared object file: No such file or directory

Fix that by adding BR2_PACKAGE_PYTHON3_ZLIB dependency.

Signed-off-by: Marcin Niestroj <m.niestroj@grinn-global.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit 0dc1213565e76d9c68986489ada3c06b928089d5)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>