package/libdvdcss: needs gcc >= 8
Buildroot commit cd3a2f0ff35346ad5fd6a9867113260addccf127 switched the
build system to meson which depends on c17:
https://code.videolan.org/videolan/libdvdcss/-/commit/9f16597859120b96006415c084039f63efc84b83#line_0cc1139e3_A5

Add the necessary dependency and propagate to reverse dependencies to
fix a build error caught by the Gitlab pipelines:

br-test-pkg/bootlin-aarch64-glibc-old/build/libdvdcss-1.5.0/meson.build:1:0:
 ERROR: None of values ['c17'] are supported by the C compiler. Possible
 values for option "c_std" are ['none', 'c89', 'c99', 'c11', 'gnu89',
 'gnu99', 'gnu11']

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>