package/crun: needs MMU
Fix the following build failure with uclibc but without MMU raised since
commit 223596c75d73a7eb29152235d3c5d9bf53bd58f5:

/home/autobuild/autobuild/instance-6/output-1/host/riscv64-buildroot-linux-uclibc/bin/ld.real: ./.libs/libcrun.a(libcrun_la-container.o): in function `.L0 ':
container.c:(.text+0x4e7c): undefined reference to `fork'

Fixes:
 - http://autobuild.buildroot.org/results/f19482753e9262ec806cf550619170467a144daf

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>