package/jack2: fix build with libexecinfo
Fix the following build failure raised on uclibc and musl since the
addition of libexecinfo package in commit
eea8ba446c10701a273432552108d80fb2224ef4:

/home/peko/autobuild/instance-1/output-1/host/opt/ext-toolchain/bin/../lib/gcc/arm-buildroot-linux-uclibcgnueabi/10.3.0/../../../../arm-buildroot-linux-uclibcgnueabi/bin/ld: dbus/sigsegv.c.17.o: in function `signal_segv':
sigsegv.c:(.text+0x98): undefined reference to `backtrace'

Fixes:
 - http://autobuild.buildroot.org/results/dca49cb9b3e66fac921601560e9358bcce9acffc

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit 930db465d9d9f2fd558e67bd808914309c2d4619)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>