package/libmad: drop GCC's "-fforce-mem" option
The commit fixes the following compilation error:

    i686-buildroot-linux-gnu-gcc.br_real: error: unrecognized command-line option ‘-fforce-mem’

From GCC 4.3 release notes [1]:

    The -fforce-mem option has been removed because it has had no effect
    in the last few GCC releases.

[1] https://gcc.gnu.org/gcc-4.3/changes.html
Signed-off-by: Dario Binacchi <dario.binacchi@amarulasolutions.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>
(cherry picked from commit 89ba9c5a0b05f119d8f748f52244ebcb6a0dd008)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>