package/gcc-bare-metal: fix build with host gcc 16
Fixes:
https://autobuild.buildroot.net/results/3ff/3ff8d6a1d7bbc02be9118afff243709de43d186d/

/home/autobuild/autobuild/instance-16/output-1/build/host-gcc-bare-metal-15.2.0/libcody/cody.hh:
 In member function 'void Cody::Detail::MessageBuffer::Space()':
/home/autobuild/autobuild/instance-16/output-1/build/host-gcc-bare-metal-15.2.0/libcody/cody.hh:113:24:
 error: no matching function for call to 'S2C(const char8_t [2])'
  113 |     Append (Detail::S2C(u8" "));
      |             ~~~~~~~~~~~^~~~~~~
  * there is 1 candidate
    * candidate 1: 'template<unsigned int I> constexpr char Cody::Detail::S2C(const char (&)[I])'
      /home/autobuild/autobuild/instance-16/output-1/build/host-gcc-bare-metal-15.2.0/libcody/cody.hh:51:16:
         51 | constexpr char S2C (char const (&s)[I])
            |                ^~~
      * template argument deduction/substitution failed:
        *   mismatched types 'const char' and 'const char8_t'

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Arnout Vandecappelle <arnout@rnout.be>
(cherry picked from commit 4234bc46d0d955691cab27e925706c42c10ac590)
Signed-off-by: Thomas Perale <thomas.perale@mind.be>