package/google-breakpad: fix build with glibc >= 2.33
Fix the following build failure with glibc >= 2.33:

src/client/linux/handler/exception_handler.cc: In function 'void google_breakpad::{anonymous}::InstallAlternateStackLocked()':
src/client/linux/handler/exception_handler.cc:147:49: error: no matching function for call to 'max(int, long int)'
  147 |   static const unsigned kSigStackSize = std::max(16384, SIGSTKSZ);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/61a89fa954db16a7b5b9fcee55c545e489f8d489

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
(cherry picked from commit 53495c204b84675f5f4b2bd255bfeb1cbcb100e9)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>