package/freeradius-server: set krb5-config
Fix the following libkrb5 build failure raised since the addition of the
package in commit 736c4c1655d93652a9a7e79235bbe726b3d46176:

checking for krb5-config... /bin/krb5-config
checking krb5-config CFLAGS... Failed to find installation architecture
""
checking krb5-config LDFLAGS... Failed to find installation architecture

checking krb5-config reported version... Failed to find installation architecture
 ()
checking krb5-config reported vendor... Failed to find installation architecture

checking canonical API type... HEIMDAL

[...]

In file included from src/modules/rlm_krb5/rlm_krb5.c:32:
src/modules/rlm_krb5/krb5.h:41:9: error: unknown type name 'krb5_verify_opt'
   41 |         krb5_verify_opt options;
      |         ^~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/f173d1600c278d910f4cbeae86dcad1ee0f911f9

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>