package/lsof: fix build without wchar or locale
Fix the following build failure without wchar or locale raised since
bump to version 4.99.3 in commit
1edafc4b483e82b045d3a0cc9cbbd000d6183ac7 and
https://github.com/lsof-org/lsof/commit/898fe0eceec98ca71198de7d9c18e7ce6144ee13:

In file included from common.h:42,
                 from misc.c:31:
../machine.h:415:26: fatal error: wctype.h: No such file or directory
  415 | #    define WIDECHARINCL <wctype.h>
      |                          ^

Fixes:
 - http://autobuild.buildroot.org/results/aa98b10e8eff5cc4fd03b4a64224cdfb6a0324a5

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>