package/faifa: bump to latest git commit
- Drop patches (already in version)
- libevent is mandatory since
  https://github.com/ffainelli/faifa/commit/d2339c2a7680e7c87555650e19123e27e1f12031
- This bump will fix the following build failure with gcc >= 14:

  hpav_cfg.c: In function 'pushbutton_request':
  hpav_cfg.c:256:37: error: passing argument 2 of 'send_vendor_pkt' makes pointer from integer without a cast [-Wint-conversion]
    256 |         return send_vendor_pkt(ctx, mac, HPAV_MMTYPE_MS_PB_ENC,
        |                                     ^~~
        |                                     |
        |                                     uint8_t {aka unsigned char}
  hpav_cfg.c:123:64: note: expected 'const uint8_t *' {aka 'const unsigned char *'} but argument is of type 'uint8_t' {aka 'unsigned char'}
    123 | static int send_vendor_pkt(struct context *ctx, const uint8_t *to,
        |                                                 ~~~~~~~~~~~~~~~^~
  hpav_cfg.c: In function 'main':
  hpav_cfg.c:406:48: error: passing argument 2 of 'pushbutton_request' makes integer from pointer without a cast [-Wint-conversion]
    406 |                 ret = pushbutton_request(&ctx, mac);
        |                                                ^~~
        |                                                |
        |                                                uint8_t * {aka unsigned char *}
  hpav_cfg.c:254:60: note: expected 'uint8_t' {aka 'unsigned char'} but argument is of type 'uint8_t *' {aka 'unsigned char *'}
    254 | static int pushbutton_request(struct context *ctx, uint8_t mac)
        |                                                    ~~~~~~~~^~~

Fixes:
 - http://autobuild.buildroot.org/results/5a65337366e52c6234d8d154b7e9a0296e02f1dd

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>