configs: orangepi_one_defconfig: U-Boot requires OpenSSL
Building U-Boot for OrangePi One now requires host OpenSSL. Select
BR2_TARGET_UBOOT_NEEDS_OPENSSL to fix the following build error:

include/image.h:1383:12: fatal error: openssl/evp.h: No such file or directory
 1383 | #  include <openssl/evp.h>
      |            ^~~~~~~~~~~~~~~

Fixes:
https://gitlab.com/buildroot.org/buildroot/-/jobs/4187707115

Signed-off-by: Sergey Matyukevich <geomatsi@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>