package/python-pyparsing: needs python3
python-pyparsing dropped python2 support since version 3.0.0:
https://github.com/pyparsing/pyparsing/blob/master/docs/whats_new_in_3_0_0.rst#python-2-x-no-longer-supported
resulting in the following build failure since bump to version 3.0.6 in
commit 7affc7827aee0e07ec94d3b4d91c2e23bda8d937:

  File "setup.py", line 8, in <module>
    from pyparsing import __version__ as pyparsing_version
  File "/home/buildroot/autobuild/instance-0/output-1/build/python-pyparsing-3.0.6/pyparsing/__init__.py", line 100
    major: int
         ^
SyntaxError: invalid syntax

Fixes:
 - http://autobuild.buildroot.org/results/8ac5224f4b6c2c59035dbfb53541e76f58b15e47

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>