package/gstreamer1/gstd: fix build with gcc 4.8
Fix the following build failure with gcc 4.8 raised since bump to
version 0.14.0 in commit a334b9a7668ba412cb2da79b75a019cd89985145 and
https://github.com/RidgeRun/gstd-1.x/commit/e83c94920bb33846ff0642dcf070fc5fd124e4f6:

../libgstd/libgstd.c: In function 'gstd_set_ipc':
../libgstd/libgstd.c:119:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (gint ipc_idx = 0; ipc_idx < num_ipcs; ipc_idx++) {
     ^

Fixes:
 - http://autobuild.buildroot.org/results/00ad1b8979000aa10a20228c998389bc913cbbd4

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>