package/python-pyopenssl: add missing dependency for deprecation handling
When commit bbdcb75d7f19 ("package/python-pyopenssl: bump to version
25.0.0") has been added, it has silently introduced a new dependency on
typing_extensions that has not been ported in the corresponding
Config.in, resulting in failures at runtime when trying to import the
module:

ModuleNotFoundError: No module named 'typing_extensions'

The upstream project has indeed introduced the following deprecation
handling snippet with commit 1b2b0ed21986 ("Use type-level deprecations
(#1389)"):

  if sys.version_info >= (3, 13):
      from warnings import deprecated
  elif sys.version_info < (3, 8):
      _T = typing.TypeVar("T")

      def deprecated(msg: str, **kwargs: object) -> Callable[[_T], _T]:
          return lambda f: f
  else:
      from typing_extensions import deprecated

This then breaks systems with pyopenssl >= 25.0.0, python < 3.13, python
>= 3.8, and without typing_extensions.

Fix the missing dependency by adding it explicitely in pyopenssl
Config.in

Signed-off-by: Alexis Lothoré <alexis.lothore@bootlin.com>
Signed-off-by: Thomas Perale <thomas.perale@mind.be>