package/openswan: remove package
last release: Jan 2021
last commit: Feb 2021
open issues: 122 (youngest from Aug 2024)
open PR: 2 (youngest from Feb 2021)

Debian removed the package in 2014:
https://tracker.debian.org/pkg/openswan

Fedora removed the package in 2013:
https://src.fedoraproject.org/rpms/openswan/commits/rawhide
"Obsoleted by libreswan"

https://github.com/libreswan/libreswan
"Libreswan was forked from Openswan 2.6.38"

The Openswan package causes autobuilder errors with gcc 14.x.
The earliest build error to be found dates back to Jul 2024:
https://autobuild.buildroot.net/results/8f1/8f109654affea46a18d42bf494d1f3a83084fcdc/build-end.log

/home/autobuild/autobuild/instance-7/output-1/build/openswan-3.0.0/programs/pluto/crypto.c:99:18:
 error: initialization of 'void (*)(void *, const u_char *, size_t)'
 {aka 'void (*)(void *, const unsigned char *, unsigned int)'} from
 incompatible pointer type 'void (*)(void *, const unsigned char *,
 long unsigned int)' [-Wincompatible-pointer-types]
   99 |     hash_update: osMD5Update,

Fixes:
https://autobuild.buildroot.net/results/bac/bacc1790d17992413503a4d62fe11ec56d0a8edc/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Arnout Vandecappelle <arnout@rnout.be>