configs/chiliboard: uboot needs openssl
Fixes uboot build errors:

  In file included from tools/imagetool.h:24,
                   from tools/aisimage.c:7:
  include/image.h:1383:12: fatal error: openssl/evp.h: No such file or directory
   1383 | #  include <openssl/evp.h>
        |

Signed-off-by: Marcin Niestroj <m.niestroj@grinn-global.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 7ee2bd48f11ec9362f6bdbec29a733296b7a01e7)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>