package/uboot-tools: fix host build without FIT support
Commit [1] "package/uboot-tools: fix host FIT signature support"
slightly changed the logic in which the file
$(@D)/include/generated/autoconf.h is created.

When there is no Kconfig sub-option selected, the file is no longer
created and the build fails with error:

    include/linux/kconfig.h:4:10: fatal error: generated/autoconf.h: No such file or directory

The issue can be reproduced with the with the simple commands:

    cat >.config <<EOF
    BR2_aarch64=y
    BR2_TOOLCHAIN_EXTERNAL=y
    BR2_PACKAGE_HOST_UBOOT_TOOLS=y
    EOF
    make olddefconfig
    make host-uboot-tools

This commit fixes the issue by simply adding a touch of the file
at the beginning to make sure it will always exist.

[1] https://gitlab.com/buildroot.org/buildroot/-/commit/928cc5dc5cb82e6f2cb43f853488309eb806ef89

Cc: James Hilliard <james.hilliard1@gmail.com>
Reported-by: Robert P. J. Day <rpjday@crashcourse.ca>
Tested-by: Robert P. J. Day <rpjday@crashcourse.ca>
Signed-off-by: Julien Olivain <ju.o@free.fr>