package/sunxi-tools: fix build dependencies
This patch fixes the dependency on libfdt for host-sunxi-tools.
Also it fixes the dependency on zlib for sunxi-tools.

Fix the following host build failure raised since commit
2e330dff6a7ce7965ceb0dccdc9dcbcb329167bb

fit_image.c:19:10: fatal error: libfdt.h: No such file or directory
   19 | #include <libfdt.h>
      |          ^~~~~~~~~~
compilation terminated.

Fixes: http://autobuild.buildroot.net/results/2677c69ac34642a7a501230e1dd22b193db0899d/
Signed-off-by: Maksim Kiselev <bigunclemax@gmail.com>
Reviewed-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
Tested-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>