package/gnutls: fix build without threads
Fix the following build failure without threads raised since bump to
version 3.7.3 in commit 212b020bb43f13121d6cde464f871d5d1cf6cfbe:

kx.c: In function '_gnutls_nss_keylog_write':
kx.c:164:33: error: 'keylog_mutex' undeclared (first use in this function); did you mean 'keylog_once'?
  164 |   if (gnutls_static_mutex_lock(&keylog_mutex) < 0) {
      |                                 ^~~~~~~~~~~~
      |                                 keylog_once

Fixes:
 - http://autobuild.buildroot.org/results/e092bc11ce4b5908cb6285aa77a3594b8626eeec

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>