package/bluez5_utils: fix musl build
Fix the following musl build failure raised since commit
6fc5c8e92c1d7997e48b207187d2d3c7ad42819:

In file included from src/shared/queue.c:15:
./src/shared/util.h:106:1: error: unknown type name 'ssize_t'; did you mean 'size_t'?
  106 | ssize_t util_getrandom(void *buf, size_t buflen, unsigned int flags);
      | ^~~~~~~
      | size_t

Fixes:
 - http://autobuild.buildroot.org/results/83eaeb3863040645409f5787fdbdde79385c5257

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit 96ebed1eed6dcd55d8024cbc6fe8bec646d739c6)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>