package/python-tinyrpc: not available for python 2.x
Fixes:
http://autobuild.buildroot.net/results/eef0969bac04800cec51fa27f1e1ecd3a4c8211e/

tinyrpc 1.x is not compatible with python 2.x, leading to errors during the
pycompile step:

error:   File "/usr/lib/python2.7/site-packages/tinyrpc/client.py", line 37
    self, protocol: RPCProtocol, transport: ClientTransport
                  ^
SyntaxError: invalid syntax

As also documented in the README:
The current version will support Python3 only.  Have a look at the 0.9.x
version if you need Python2 support

https://github.com/mbr/tinyrpc/blob/1.0.4/README.rst

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
Reviewed-by: Asaf Kahlon <asafka7@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit 6d87acc19f1cd0bc738bf920b775caf96d7c3c4e)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>