package/botan: fix mips64 build
Disable cc-tests to avoid the following build failure on mips64:

  ERROR: Configured target is mips64 but compiler probe indicates mips32

Fixes:
 - http://autobuild.buildroot.org/results/c44f44f36686268479563afd879db588e15ede7d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit fb9a422eba604cbdcd78826a6d520146c4fffad2)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>