package/libsigsegv: bump to version 2.14
This bump will fix the following build failure on or1k and microblazeel:

In file included from handler.c:20:
handler-unix.c: In function 'sigsegv_handler':
handler-unix.c:194:28: error: 'struct vma_struct' has no member named 'is_near_this'
  194 |                       : vma.is_near_this (addr, &vma))
      |                            ^

https://git.savannah.gnu.org/gitweb/?p=libsigsegv.git;a=blob;f=NEWS;h=4d012f8b6cd9b2c1eccbf266a10aae56b0e79978;hb=9ad117adabd223b79e037575e071855c2b8b35c0
https://git.savannah.gnu.org/gitweb/?p=libsigsegv.git;a=blob;f=ChangeLog;h=c52b227aae190ba9b161282efaa5f33cb4a127f9;hb=9ad117adabd223b79e037575e071855c2b8b35c0

Fixes:
 - http://autobuild.buildroot.org/results/c693fafb8f1f68be30a281313fb1f0890cc08b1e
 - http://autobuild.buildroot.org/results/ecde11129d102e3321b2aaef407697c29311c705

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit c6addf4606c3a41cdad5c6ac4c6508b298b6e92a)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>