package/haveged: fix legal-info
Add hash for COPYING file

Fixes:

$: make haveged-legal-info
 >>> haveged 1.9.4 Collecting legal info
 ERROR: No hash found for COPYING

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 0ae29b98d1293b0e89fa2f5686fe743af1f45c34)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>