package/targetcli-fb: needs python-gobject
Without python-gobject, we get the following runtime error:

   ModuleNotFoundError: No module named 'gi'

Add python-gobject and propagate its dependencies.

While we're at it, split the DEPENDENCIES over several line and sort
them alphabetically.

Signed-off-by: Jeremy J. Peper <jeremy@jeremypeper.com>
Reviewed-by: Adam Duskett <adam.duskett@amarulasolutions.com>
[Arnout: reorder everything alphabeticall, split DEPENDENCIES over
several lines.]
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>
(cherry picked from commit 945b9f8d8e9704fd3d2dbd2579ebf9178ed49d89)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>