configs/beagleboneai: move to u-boot 2025.04 to unbreak build with gcc 14
With the change to default to gcc 14.x with commit 1e1fafa1f0f5
("package/gcc: switch to GCC 14.x as the default"), the old u-boot version
no longer builds:

board/ti/am57xx/board.c:948:17: error: implicit declaration of function 'do_cape_detect'; did you mean 'do_board_detect'? [-Wimplicit-function-declaration]

https://gitlab.com/buildroot.org/buildroot/-/jobs/11570241744

So move to u-boot 2025.04 to fix that.  We still need a small patch as
(early) beagleboneai boards do not have the EEPROM (or eMMC partition)
populated, so include the bb.org patch from

https://github.com/beagleboard/u-boot/commit/0b161f8e89a411fe54059cf1d0ba61354ee1e8a2

The new u-boot version needs both openssl and gnutls on the host, so enable
them.

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
[Julien: remove patch entry in .checkpackageignore to
  fix check-package error
]
Signed-off-by: Julien Olivain <ju.o@free.fr>