package/gtkiostream: disable octave
Disable octave support which was added in commit
fab48302865e5c0c98d91b696bc90e75e38189bb but untested as octave is not
installed to staging and raises the following build failure:

sparc64-linux-g++: ERROR: unsafe header/library path used in cross-compilation: '-I/usr/include/octave-3.8.1'

Fixing those issues is useless, as gtkiostream is not compatible with
latest octave version as it raises a bunch of errors:

Octave.C: In member function 'void Octave::startOctave(const std::vector<std::__cxx11::basic_string<char> >&)':
Octave.C:85:5: error: 'octave_main' was not declared in this scope; did you mean 'octave_map'?
   85 |     octave_main((int)argsIn.size(), (char**)&argsIn[0], embedded);
      |     ^~~~~~~~~~~
      |     octave_map
Octave.C: In member function 'int Octave::setGlobalVariable(const std::string&, Matrix&)':
Octave.C:283:50: error: use of deleted function 'octave::symbol_table::symbol_table()'
  283 |             octave_value ov=octave::symbol_table().global_varval(string(baseName));
      |                                                  ^
In file included from /home/fabrice/buildroot/output/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/octave-9.2.0/octave/octave-config.h:99,
                 from /home/fabrice/buildroot/output/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/octave-9.2.0/octave/parse.h:29,
                 from Octave.C:18:
/home/fabrice/buildroot/output/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/octave-9.2.0/octave/symtab.h:63:39: note: declared here
   63 |   OCTAVE_DISABLE_CONSTRUCT_COPY_MOVE (symbol_table)
      |                                       ^~~~~~~~~~~~
/home/fabrice/buildroot/output/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/octave-9.2.0/octave/oct-conf-post-public.h:354:3: note: in definition of macro 'OCTAVE_DISABLE_CONSTRUCT_COPY_MOVE'
  354 |   X () = delete;                                \
      |   ^
Octave.C:284:34: error: use of deleted function 'octave::symbol_table::symbol_table()'
  284 |             octave::symbol_table().global_assign (string(baseName), setGlobalSubVariable(varNames, m, 0, ov));
      |                                  ^
/home/fabrice/buildroot/output/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/octave-9.2.0/octave/symtab.h:63:39: note: declared here
   63 |   OCTAVE_DISABLE_CONSTRUCT_COPY_MOVE (symbol_table)
      |                                       ^~~~~~~~~~~~
/home/fabrice/buildroot/output/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/octave-9.2.0/octave/oct-conf-post-public.h:354:3: note: in definition of macro 'OCTAVE_DISABLE_CONSTRUCT_COPY_MOVE'
  354 |   X () = delete;                                \
      |   ^
Octave.C:286:34: error: use of deleted function 'octave::symbol_table::symbol_table()'
  286 |             octave::symbol_table().global_assign (string(baseName), m);
      |                                  ^
/home/fabrice/buildroot/output/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/octave-9.2.0/octave/symtab.h:63:39: note: declared here
   63 |   OCTAVE_DISABLE_CONSTRUCT_COPY_MOVE (symbol_table)
      |                                       ^~~~~~~~~~~~
/home/fabrice/buildroot/output/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/octave-9.2.0/octave/oct-conf-post-public.h:354:3: note: in definition of macro 'OCTAVE_DISABLE_CONSTRUCT_COPY_MOVE'
  354 |   X () = delete;                                \
      |   ^
Octave.C: In member function 'octave_map Octave::setGlobalSubVariable(const std::vector<std::__cxx11::basic_string<char> >&, const Matrix&, int, octave_value&)':
Octave.C:302:38: error: 'class string_vector' has no member named 'lookup'
  302 |             whichIdx=base.map_keys().lookup(varNames[index+1]); // map_keys returns a string_vector
      |                                      ^~~~~~

Fixes: fab48302865e5c0c98d91b696bc90e75e38189bb
 - http://autobuild.buildroot.org/results/9cfc420a4e41503635792472176583a8f81bb2a3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>