package/proj: bump to version 9.3.0
- Switch to cmake-package as autotools has been removed since version
  9.0.0
- This bump will fix the following build failure with gcc 13 thanks to
  https://github.com/OSGeo/PROJ/pull/3459/commits/b0b8937c56ced8eb0ffef532b9c691a1a5fc8634:

In file included from proj_json_streaming_writer.cpp:34:
proj_json_streaming_writer.hpp:42:14: error: 'int64_t' in namespace 'std' does not name a type
   42 | typedef std::int64_t GIntBig;
      |              ^~~~~~~

https://github.com/OSGeo/PROJ/blob/9.3.0/NEWS

Fixes:
 - http://autobuild.buildroot.org/results/68416dcbed1ece589a7438b085f57064fc20f87d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>