package/fontconfig: fix build with toolchains without pthread
../test/test-crbug1004254.c:28:10: fatal error: pthread.h: No such file or directory
   28 | #include <pthread.h>
      |          ^~~~~~~~~~~

Commit cef7358 "package/fontconfig: fix compilation on targets without pthread support"
fixed compilation for targets without pthread support, but that was apparently nog enough.

Back then, I tested all the targets by using `./utils/test-pkg -p fontconfig -a`,
but somehow these targets didn't enable the fontconfig tests, so I didn't see this
compile failure. Fix it now by explicitly disabling the fontconfig tests.

Fixes:
 -  https://autobuild.buildroot.org/results/5f0/5f0c716c20788ba49a3a9f185251ded373a764cd/build-end.log

Signed-off-by: Thomas Devoogdt <thomas@devoogdt.com>
[Julien: reword commit log title]
Signed-off-by: Julien Olivain <ju.o@free.fr>