package/bluez5_utils: set BLUEZ5_UTILS_AUTORECONF
Commit 572d08ee4a731b203b2d3aaf720a48f622609371 forgot to set
BLUEZ5_UTILS_AUTORECONF resulting in the following build failure:

/home/peko/autobuild/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/sh4-buildroot-linux-uclibc/10.3.0/../../../../sh4-buildroot-linux-uclibc/bin/ld: gobex/gobex-packet.o: in function `g_obex_packet_set_data':
gobex-packet.c:(.text+0x698): undefined reference to `util_memdup'

It should be noted that previous commit didn't fix any build failure
with libglib >= 2.69. It only fixes the following warning:

profiles/battery/battery.c: In function 'read_initial_battery_level_cb':
profiles/battery/battery.c:162:2: warning: 'g_memdup' is deprecated (declared at /home/buildroot/autobuild/instance-0/output-1/host/bin/../arm-buildroot-linux-gnueabi/sysroot/usr/include/glib-2.0/glib/gstrfuncs.h:257): Use 'g_memdup2' instead [-Wdeprecated-declarations]
  batt->initial_value = g_memdup(value, length);
  ^

So an other option would be to revert this commit.

The 'real' build error that previous commit tried to fix was raised
because rand was replaced by getrandom since
https://git.kernel.org/pub/scm/bluetooth/bluez.git/log/?qt=grep&q=getrandom
but getrandom is not available until glibc 2.25:

plugins/autopair.c:20:24: fatal error: sys/random.h: No such file or directory
 #include <sys/random.h>
                        ^

Fixes:
 - http://autobuild.buildroot.org/results/46f7dbfe1d80c7622d670ba1ac957e9e6077eb9f

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>