package/zchunk: fix build with argp-standalone and NLS
Fix the following build failure with argp-standalone and NLS raised
since commit 5430c8fedd0392e79e0c011825b056fea129980a:

/home/buildroot/autobuild/instance-3/output-1/host/bin/i686-linux-gcc  -o test/zck_cmp_uncomp test/zck_cmp_uncomp.p/zck_cmp_uncomp.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 '-Wl,-rpath,$ORIGIN/../src/lib' -Wl,-rpath-link,/home/buildroot/autobuild/instance-3/output-1/build/zchunk-1.2.2/build/src/lib -Wl,--start-group src/lib/libzck.so.1.2.2 -largp -Wl,--end-group
/home/buildroot/autobuild/instance-3/output-1/host/opt/ext-toolchain/bin/../lib/gcc/i686-buildroot-linux-uclibc/9.3.0/../../../../i686-buildroot-linux-uclibc/bin/ld: /home/buildroot/autobuild/instance-3/output-1/host/i686-buildroot-linux-uclibc/sysroot/usr/lib/libargp.a(argp-help.o): in function `arg':
/home/buildroot/autobuild/instance-3/output-1/build/argp-standalone-1.4.1/argp-help.c:936: undefined reference to `libintl_dgettext'

Fixes:
 - http://autobuild.buildroot.org/results/1242d0b15ceb816e946bfc1b31dd39e68227359f

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>