configs/orangepi_zero_plus2: U-Boot needs pylibfdt
When building U-Boot for this platform:

unable to execute 'swig': No such file or directory
error: command 'swig' failed with exit status 1
scripts/dtc/pylibfdt/Makefile:26: recipe for target 'scripts/dtc/pylibfdt/_libfdt.so' failed

Fixes:

  https://gitlab.com/buildroot.org/buildroot/-/jobs/123771103

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit aab652866018e625814b8d715d8b52578e8cc71a)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>