package/logrotate: fix legal-info
Add hash for COPYING file

Fixes:

$: make logrotate-legal-info
 >>> logrotate 3.15.0 Collecting legal info
 ERROR: No hash found for COPYING

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 38626b4b63bf877c3cfeb356a4b0dc0e79bdbc75)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>