package/freeradius-server: add libxcrypt optional dependency
Fix the following build failure raised since bump of glibc to version
2.39 in commit b5680f53d60acf8ff6010082f873438a39bd5d97:

src/lib/missing.c:31:7: error: conflicting types for 'crypt'; have 'char *(char *, char *)'
   31 | char *crypt(UNUSED char *key, char *salt)
      |       ^~~~~
In file included from src/freeradius-devel/missing.h:60,
                 from src/freeradius-devel/libradius.h:71,
                 from src/lib/missing.c:26:
/home/buildroot/autobuild/instance-2/output-1/host/mipsel-buildroot-linux-gnu/sysroot/usr/include/unistd.h:1162:14: note: previous declaration of 'crypt' with type 'char *(const char *, const char *)'
 1162 | extern char *crypt (const char *__key, const char *__salt)
      |              ^~~~~

Fixes: b5680f53d60acf8ff6010082f873438a39bd5d97
 - http://autobuild.buildroot.org/results/dc45f1291245a0dadd382cea2ad41573ad976d60

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>