package/proj: needs NPTL
NPTL is mandatory since bump to version 9.3.0 in commit
57aba033e6cc81b95d006227c45a15eb3fc77d07 and
https://github.com/OSGeo/PROJ/commit/ce080251225d16e11e139a5ebe07cf608fe022b2:

/home/buildroot/instance-0/output-1/build/proj-9.3.0/src/iso19111/factory.cpp: In member function 'std::shared_ptr<osgeo::proj::io::SQLiteHandle> osgeo::proj::io::SQLiteHandleCache::getHandle(const std::string&, PJ_CONTEXT*)':
/home/buildroot/instance-0/output-1/build/proj-9.3.0/src/iso19111/factory.cpp:622:9: error: 'pthread_atfork' was not declared in this scope; did you mean 'pthread_attr_t'?
  622 |         pthread_atfork(nullptr, nullptr,
      |         ^~~~~~~~~~~~~~
      |         pthread_attr_t

Fixes: 57aba033e6cc81b95d006227c45a15eb3fc77d07
 - http://autobuild.buildroot.org/results/392664375c5bc5f047d39bff31534a226e8ea526

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Maxim Kochetkov <fido_max@inbox.ru>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit 4eeb69c9835450da8af8f55c776a7774914e2102)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>