package/quotatool: bump to version 1.6.4
- Switch site to get latest release
- Send patch upstream
- This bump will fix the following build failure with gcc >= 14:

  src/main.c: In function 'main':
  src/main.c:211:17: error: implicit declaration of function 'quota_reset_grace'; did you mean 'xfs_reset_grace'? [-Wimplicit-function-declaration]
    211 |           if (! quota_reset_grace(quota, (argdata->block_reset ? GRACE_BLOCK : GRACE_INODE)))
        |                 ^~~~~~~~~~~~~~~~~
        |                 xfs_reset_grace

https://github.com/ekenberg/quotatool/blob/v1.6.4/ChangeLog

Fixes:
 - http://autobuild.buildroot.org/results/1855bc61fb231fadab77840dcd7ef75c414fe5be

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>