package/tcf-agent: fix powerpc64 build
Translation of ppc64 to powerpc has been removed since version 1.8.0 and
https://git.eclipse.org/c/tcf/org.eclipse.tcf.agent.git/commit/?id=94fa43963538afffc1fff77623cd1561a05d0e21
resulting in the following build failure since commit
81802e263a12e173e0e1028449d1e1e11b2e5974:

In file included from /home/buildroot/autobuild/instance-0/output-1/build/tcf-agent-1.8.0/agent/system/GNU/Linux/tcf/context-linux.c:58:
/home/buildroot/autobuild/instance-0/output-1/build/tcf-agent-1.8.0/agent/../agent/system/GNU/Linux/tcf/regset.h:25:10: fatal error: tcf/regset-mdep.h: No such file or directory
   25 | #include <tcf/regset-mdep.h>
      |          ^~~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/821049a692d4a64fa45b73e8e18eb48c36d46e6b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>