package/batman-adv: bump to version 2022.2
This bump will fix the following build failure with kernel >= 5.18 thanks to
https://github.com/open-mesh-mirror/batman-adv/commit/f07a0c37ab278fb6a9e95cad89429b1282f1ab59:

/home/buildroot/autobuild/instance-2/output-1/build/batman-adv-2021.4/net/batman-adv/bridge_loop_avoidance.c: In function ‘batadv_bla_send_claim’:
/home/buildroot/autobuild/instance-2/output-1/build/batman-adv-2021.4/net/batman-adv/bridge_loop_avoidance.c:446:9: error: implicit declaration of function ‘netif_rx_any_context’ [-Werror=implicit-function-declaration]
  446 |         netif_rx_any_context(skb);
      |         ^~~~~~~~~~~~~~~~~~~~

Indeed, netif_rx_any_context has been dropped since kernel 5.18:
https://github.com/torvalds/linux/commit/2655926aea9beea62c9ba80c032485456fd848f0

https://github.com/open-mesh-mirror/batman-adv/blob/v2022.2/CHANGELOG.rst

Fixes:
 - http://autobuild.buildroot.org/results/542b7b99da7b7a65e6e11e7c73a26856e3222e89

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>