package/mpg123: force arm mode instead of Thumb mode
Fix the following build failure:
Error: selected processor does not support `smull r3,ip,r2,r10' in Thumb mode

Fixes:
http://autobuild.buildroot.net/results/848/8484fc6be618f3edbf39a13928ab9a4b7b442235/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>