package/matchbox-lib: fix build failure with GCC 15.x
Backport upstream patch fixing:

hash.c:76:6: error: conflicting types for ‘hash_empty’; have ‘void(struct hash *)’
   76 | void hash_empty(struct hash *h)
      |      ^~~~~~~~~~
In file included from hash.c:22:
hash.h:41:6: note: previous declaration of ‘hash_empty’ with type ‘void(void)’
   41 | void hash_empty();
      |      ^~~~~~~~~~

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 2bfdadab434d3f9100b66a783ee317d118b5623c)
Signed-off-by: Thomas Perale <thomas.perale@mind.be>