package/libuwsc: fix wolfssl build
Commit 1567fbd72d4b547f70a7509247bf9abb73ab58e3 didn't fully fix the
wolfssl build failure because the include on wolfssl/options.h was still
missing:

/home/autobuild/autobuild/instance-6/output-1/build/libuwsc-3.3.5/src/ssl.c:62:5: error: unknown type name 'SSL_CTX'
   62 |     SSL_CTX *ctx;
      |     ^~~~~~~

While at it, add upstream tag to patches

Fixes:
 - http://autobuild.buildroot.org/results/edc49cce5b1f456d980841f4c315e7cd784b1561

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit e874fd08e01a8d543520f867d95ae8a6a9fa242e)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>