package/freeradius-server: requires RC4 support in openssl
Fixes:
https://autobuild.buildroot.net/results/5a5/5a57a82800fb7a47731198effc15bd7044133c4d/

    src/modules/rlm_mschap/rlm_mschap.c:1016:54: error: implicit
    declaration of function 'EVP_rc4'; did you mean 'EVP_md4'?

The oldest build error found with a quick search appeared back in July
2024 with freeradius-server 3.2.3 so a backport should be considered:
https://autobuild.buildroot.net/results/e2d/e2d77a52f81b0fea1081417c5c80f7991e27810a/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>
(cherry picked from commit 99c5c21b14e86ef53520868a6bee672d6e249c3b)
Signed-off-by: Thomas Perale <thomas.perale@mind.be>