package/opencv3: bump to version 3.4.19
This bump will fix the following build failure with gcc >= 12:

/home/thomas/autobuild/instance-1/output-1/build/opencv3-3.4.17/modules/core/src/persistence_base64.cpp: In function 'bool base64::base64_valid(const uint8_t*, size_t, size_t)':
/home/thomas/autobuild/instance-1/output-1/build/opencv3-3.4.17/modules/core/src/persistence_base64.cpp:167:31: error: comparing the result of pointer addition '(src + ((sizetype)off))' and NULL [-Werror=address]
  167 |     if (src == 0 || src + off == 0)
      |                     ~~~~~~~~~~^~~~
cc1plus: some warnings being treated as errors

Update hash of LICENSE file (update in year:
https://github.com/opencv/opencv/commit/f6fe5c07f61eb0bc934672200b2bfd453f2fc41d)

https://github.com/opencv/opencv/wiki/ChangeLog#version3419

Fixes:
 - http://autobuild.buildroot.org/results/cb9c120c15c8042e6919858d6885c1cc4d996c0c

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>