package/execline: fix uclibc build
Fix the following uclibc build failure raised since bump to version
2.9.5.1 in commit 42fad03182ed53de8003b66d50e893f42b72145e and
https://github.com/skarnet/execline/commit/6dfe54be869c117676dcc004400ac68096945531:

src/execline/eltest.c: In function 'eltest_run':
src/execline/eltest.c:366:31: error: 'struct stat' has no member named 'st_mtim'; did you mean 'st_mtime'?
  366 |       return timespec_cmp(&st.st_mtim, &st.st_atim) > 0 ;
      |                               ^~~~~~~
      |                               st_mtime

Fixes: 42fad03182ed53de8003b66d50e893f42b72145e
 - http://autobuild.buildroot.org/results/64bf2928f36e07332052854cbaaa7a6f8f347e29

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>