package/gcc: or1k: Only define TARGET_HAVE_TLS when HAVE_AS_TLS
Backport upstream patch to fix build error seens with alsa-lib:
error.c:(.text+0x12c): undefined reference to `__tls_get_addr'

Fixes:
http://autobuild.buildroot.net/results/525ca7fe78015168c186ffda5fa52c0edb2071c9/

The fix is included in gcc 13.x.

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 4ce0dacb60b7fdccf3daabe58e09358da3f09fa2)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>