package/linux-firmware: fix legal info
Commit 9b25246e9b731f167454ba4f8182eed1926f50a6 made a typo in license
filename and forgot to add its hash:

ERROR: No hash found for LICENCE.ivsc

Fixes: 9b25246e9b731f167454ba4f8182eed1926f50a6
 - http://autobuild.buildroot.org/results/144ce581645d78a2d27a59a63130977d0f549db8

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>