package/libcgi: disable tests
Disable tests to avoid the following static build failure on sh4aeb:

In file included from /home/autobuild/autobuild/instance-5/output-1/build/libcgi-1.3.0/test/test_slist.c:20:
/home/autobuild/autobuild/instance-5/output-1/build/libcgi-1.3.0/include/libcgi/cgi.h:81:31: note: expected 'char *' but argument is of type 'const char *'
   81 | extern int slist_delete(char *name, formvars **start, formvars **last);
      |                         ~~~~~~^~~~
/home/autobuild/autobuild/instance-5/output-1/build/libcgi-1.3.0/test/test_slist.c:352:1: error: unable to find a register to spill in class 'FPUL_REGS'
  352 | }
      | ^
/home/autobuild/autobuild/instance-5/output-1/build/libcgi-1.3.0/test/test_slist.c:352:1: error: this is the insn:
(insn 1084 1081 1085 105 (set (reg:SI 4 r4)
        (mem/f:SI (post_inc:SI (reg:SI 76 fr12 [orig:343 ivtmp.286 ] [343])) [0 MEM[base: _414, offset: 0B]+0 S4 A32])) "/home/autobuild/autobuild/instance-5/output-1/build/libcgi-1.3.0/test/test_slist.c":323:3 189 {movsi_ie}
     (expr_list:REG_INC (reg:SI 76 fr12 [orig:343 ivtmp.286 ] [343])
        (nil)))

Fixes:
 - http://autobuild.buildroot.org/results/84a2339568d23b328af2416bfcec1ef41eccdce5

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit 260e7fda6adca10e0341532d03a8e1f4d08e9a10)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>