package/mraa: fix build with musl >= 1.2.5
Fix the following build failure with musl >= 1.2.5 (raised since commit
f7f03445cf320adbbc41270a806b38c911d3454a):

/home/autobuild/autobuild/instance-9/output-1/build/mraa-2.2.0/src/mraa.c: In function 'mraa_count_iio_devices':
/home/autobuild/autobuild/instance-9/output-1/build/mraa-2.2.0/src/mraa.c:341:38: error: implicit declaration of function 'basename'; did you mean 'rename'? [-Werror=implicit-function-declaration]
  341 |     if (fnmatch(IIO_DEVICE_WILDCARD, basename(path), 0) == 0) {
      |                                      ^~~~~~~~
      |                                      rename

Fixes: f7f03445cf320adbbc41270a806b38c911d3454a
 - http://autobuild.buildroot.org/results/1f16df70e49a9f8823a791c0fcc677de07136835

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Pieterjan Camerlynck <pieterjanca@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>