package/libressl: update to 3.9.2
Release notes:
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.9.2-relnotes.txt

Patches 0002/0003 are upstream. 0004 got renamed to 0002.

Disable ASM for PowerPC target, as it fails to link binaries when
enabled:
/home/autobuild/autobuild/instance-15/output-1/host/lib/gcc/powerpc-buildroot-linux-uclibc/13.3.0/../../../../powerpc-buildroot-linux-uclibc/bin/ld:
../../crypto/libcrypto.so.52.0.0: undefined reference to
`bn_mul_add_words'
...

Fixes:
 http://autobuild.buildroot.net/results/ddd/dddd58def99b28c5afa9896622259b652a4287da/

Signed-off-by: Waldemar Brodkorb <wbx@openadk.org>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>