package/strace: bump to version 6.6
- Update hash of COPYING (year updated with
  https://github.com/strace/strace/commit/b45ed94f6926c9a7aae6bfb54f9a47ea313c0646)
- This bump will fix the following build failure with kernel >= 6.6 raised
  since
  https://github.com/torvalds/linux/commit/182741d287fb1ea870ee6ef45aa1915a0b031233
  thanks to
  https://github.com/strace/strace/commit/4eda6d7b61f46d81f7f87afa6fa802dcbe136ca1:

In file included from btrfs.c:51:
xlat/btrfs_key_types.h:167:37: error: 'BTRFS_EXTENT_REF_V0_KEY' undeclared here (not in a function); did you mean 'BTRFS_EXTENT_DATA_KEY'?
  167 | static_assert((unsigned long long) (BTRFS_EXTENT_REF_V0_KEY)
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~
      |                                     BTRFS_EXTENT_DATA_KEY

https://github.com/strace/strace/releases/tag/v6.6

Fixes:
 - http://autobuild.buildroot.org/results/da026b8307a4ef1406d2c90d42564df38a172a50

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>