package/quota: fix build failure due to missing BR2_PACKAGE_LIBTIRPC_RPCDB
Package quota requires libtirpc rpcdb option enabled with non-glibc
toolchains since the bump of libtirpc to version 1.3.7 with buildroot
commit 3f3d6e43de9b4aac7df8545fd811171256f878d3 which includes upstream
commit:
https://git.linux-nfs.org/?p=steved/libtirpc.git;a=commit;h=7cea8ad66aecc21e6caae330b5d31075af399193

These build errors, caused by the forementioned upstream commit, only
occur with non-glibc toolchains:
https://patchwork.yoctoproject.org/comment/30091/
"but I believe it breaks the build with musl"
as shown by our autobuilders:

https://autobuild.buildroot.net/?reason=quota-4.10

Fixes:
https://autobuild.buildroot.net/results/fb0/fb0adbb7687d8db4228e2fc1ce7a7272486fd3ef/
"svc_socket.c:(.text+0x2c): undefined reference to `getrpcbynumber'"

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>