package/s6-linux-init: bump to version 1.0.8.0
This bump will fix the following build failure raised since bump of
skalibs to version 2.12.0.1 in commit
0f7bfc80814e90918b9527cab4cbf6afedd22195 thanks to
https://github.com/skarnet/s6-linux-init/commit/6696cee3bd309f61fc6c945ef747262a845e9267

In file included from src/shutdown/hpr_shutdown.c:8:
src/shutdown/hpr.h:20:40: error: unknown type name 'tain_t'; did you mean 'tain'?
   20 | extern int hpr_shutdown (unsigned int, tain_t const *, unsigned int) ;
      |                                        ^~~~~~
      |                                        tain

Update hash of COPYING (update in year with
https://github.com/skarnet/s6-linux-init/commit/42a91a98b780759257862642c764c2102237fea6)

https://github.com/skarnet/s6-linux-init/blob/v1.0.8.0/NEWS

Fixes:
 - http://autobuild.buildroot.org/results/4382beeb0f94d583ba605c70a47f34b45c76e311

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>