package/qemu: fix uclibc-ng and musl build
Fix the following build failure on uclibc-ng and musl raised since bump
to version 6.1.0 in commit 33c69c02fb4c1176584d1e2dd336b74ed39f5d65:

../block/export/fuse.c: In function 'fuse_fallocate':
../block/export/fuse.c:643:21: error: 'FALLOC_FL_ZERO_RANGE' undeclared (first use in this function)
  643 |     else if (mode & FALLOC_FL_ZERO_RANGE) {
      |                     ^~~~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/6d102f005cfaeba582a78a11460bf38014f56bf9
 - http://autobuild.buildroot.org/results/be24433a429fda681fb66698160132c1c99bc53b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>