package/pipewire: bump version to 1.6.6
Release notes:
https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/1.6.6/NEWS

ffmpeg support needs swscale support:
https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/2cbcdbc579bbffa682088fbedbca10e278e061dd

Renamed configure option 'systemd' to 'libsystemd' due to commit
https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/f2c878a2c175d0bece4571df691a8af02e7a3ab7

Disabled jack2 support for uClibc to fix a build error:

../pipewire-jack/src/pipewire-jack.c:13:10: fatal error: threads.h: No such file or directory
   13 | #include <threads.h>

Removing this include will not fix the problem:

../pipewire-jack/src/pipewire-jack.c:127:20: error: expected ‘;’ before ‘float’
  127 | static thread_local float midi_scratch[MIDI_SCRATCH_FRAMES];

Fixes:
https://autobuild.buildroot.net/results/217/217f4500a7dadf089b90438e1eb06aaa9c50f4c5/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>