package/heirloom-mailx: remove package
Building the package with OpenSSL 4.0.2 is broken:

openssl.c: In function 'ssl_select_method':
openssl.c:223:34: error: implicit declaration of function 'SSLv3_client_method'; did you mean 'SSLv23_client_method'? [-Wimplicit-function-declaration]
  223 |                         method = SSLv3_client_method();
      |                                  ^~~~~~~~~~~~~~~~~~~
      |                                  SSLv23_client_method
openssl.c:223:32: error: assignment to 'const SSL_METHOD *' {aka 'const struct ssl_method_st *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
  223 |                         method = SSLv3_client_method();
      |                                ^
openssl.c:225:34: error: implicit declaration of function 'TLSv1_client_method'; did you mean 'TLS_client_method'? [-Wimplicit-function-declaration]
  225 |                         method = TLSv1_client_method();
      |                                  ^~~~~~~~~~~~~~~~~~~
      |                                  TLS_client_method
openssl.c:225:32: error: assignment to 'const SSL_METHOD *' {aka 'const struct ssl_method_st *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
  225 |                         method = TLSv1_client_method();
      |                                ^
openssl.c: In function 'ssl_check_host':
openssl.c:342:59: error: invalid use of incomplete typedef 'ASN1_IA5STRING' {aka 'struct asn1_string_st'}
  342 |                                                 gen->d.ia5->data);
      |                                                           ^~
openssl.c:344:67: error: invalid use of incomplete typedef 'ASN1_IA5STRING' {aka 'struct asn1_string_st'}
  344 |                                                 (char *)gen->d.ia5->data)

openssl.c: In function 'smime_verify':
openssl.c:610:67: error: invalid use of incomplete typedef 'ASN1_IA5STRING' {aka 'struct asn1_string_st'}
  610 |                                                         gen->d.ia5->data,

Debian removed the package in 2015:
https://tracker.debian.org/news/727466/heirloom-mailx-removed-from-testing/

The last upstream release dates back to 2005:
https://sourceforge.net/projects/nail/files/nail/

Dropped BR2_TOOLCHAIN_HAS_GCC_BUG_101916 because no other uses this
option after the removal of heirloom-mailx.

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Cc: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>