package/tvheadend: fix FTBFS
Fix the folloing build failure raised since commit
04164b81e76e29fb9482245e808b46af2aa67bc6:

src/utils.c: In function 'sha512sum256':
src/utils.c:619:45: error: token " " is not valid in preprocessor expressions
  619 | #if OPENSSL_VERSION_NUMBER >= 0x1010101fL && !defined(LIBRESSL_VERSION_NUMBER)
      |                                             ^

Fixes:
 - http://autobuild.buildroot.org/results/caf0f5e4c6ad0f2764f07d33f594b6121cea87bc

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>