package/python-pyndiff: needs python3
python3 is needed since the addition of the package in commit
1665e0a79b617b4e6315ac5989e9ffa66eb0310f to avoid the following build
failure:

error:   File "/usr/lib/python2.7/site-packages/pyndiff/core.py", line 48
    nmap_service_name = f"{service_name} {service_product} {service_version} {service_extrainfo}".replace(
                                                                                                ^
SyntaxError: invalid syntax

Fixes:
 - http://autobuild.buildroot.org/results/9f283774ca2c89540753bbd62fdbddb1f9d4e392

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>