boot/shim: disable on mips64el
Fix the following build failure on mips64el raised since commit
11b347c03ab0b38389ec11b48f63236a3b4d6547:

In file included from shim.h:47,
                 from shim.c:14:
/nvmedata/autobuild/instance-17/output-1/build/shim-15.4/include/system/stdarg.h:72:2: error: #error what arch is this
   72 | #error what arch is this
      |  ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/74f4f1d010cfde6978fd614195ef0006f0acb45a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 2fd41e56e0e26fd3f3265f0e0015031211e441cf)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>