package/google-breakpad: fix missing include error
src/common/module.cc: In member function ‘bool google_breakpad::Module::AddFunction(Function*)’:
src/common/module.cc:194:52: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  194 |     FunctionSet::iterator existing_function = std::find_if(
      |                                                    ^~~~~~~
      |                                                    find
Makefile:8309: recipe for target 'src/common/tools_mac_dump_syms_dump_syms_mac-module.o' failed

This error is seen on gcc-14.

https://chromium-review.googlesource.com/c/breakpad/breakpad/+/5137658
https://git.openembedded.org/meta-openembedded/tree/meta-oe/recipes-devtools/breakpad/breakpad/0001-Fixed-missing-include-for-std-find_if.patch

Signed-off-by: Kadambini Nema <kadambini.nema@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>