package/openobex: fix static with libusb and libatomic
Force LibUSB_VERSION_1.0 to ON to fix the following static build failure
with libusb and libatomic:

-- Looking for libusb_get_device_list in /nvmedata/autobuild/instance-4/output-1/host/sparc-buildroot-linux-uclibc/sysroot/usr/lib/libusb-1.0.a
-- Looking for libusb_get_device_list in /nvmedata/autobuild/instance-4/output-1/host/sparc-buildroot-linux-uclibc/sysroot/usr/lib/libusb-1.0.a - not found

[...]

/nvmedata/autobuild/instance-4/output-1/build/openobex-1.7.2/lib/transport/usbobex.h:30:10: fatal error: usb.h: No such file or directory
   30 | #include <usb.h>
      |          ^~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/52b0edc4278f65fb4a9671b65c655cc4544a3103

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit d608368e1a98dd7f41d51214669149115a8f73aa)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>