package/tree: fix build with gcc 4.8
Fix the following build failure with gcc 4.8 raised since bump to
version 2.0.2 in commit 11a3989dbf7ac2535fac04b24ab3d959da3686b3:

color.c: In function 'parse_dir_colors':
color.c:103:11: error: redeclaration of 'i' with no linkage
   for(int i=0; i < DOT_EXTENSION; i++) color_code[i] = NULL;
           ^

Fixes:
 - http://autobuild.buildroot.org/results/e05595696727622eaf517944d4ff4414baf66bb2

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>