package/libeXosip2: fix build with libressl
Fix the following build failure with libressl >= 3.4.1 raised since
commit 25ef2c26dabaf1553f1724214a4fa5e3ce48dfc8:

In file included from eXtl_dtls.c:82:
/home/autobuild/autobuild/instance-4/output-1/host/x86_64-buildroot-linux-musl/sysroot/usr/include/openssl/ssl.h:1272:6: note: previous declaration of 'SSL_set0_rbio' was here
 1272 | void SSL_set0_rbio(SSL *s, BIO *rbio);
      |      ^~~~~~~~~~~~~
eXtl_dtls.c: In function 'SSL_set0_rbio':
eXtl_dtls.c:108:17: error: invalid use of incomplete typedef 'SSL' {aka 'struct ssl_st'}
  108 |   BIO_free_all(s->rbio);
      |                 ^~

Fixes:
 - http://autobuild.buildroot.org/results/dfafdbf71b31fbda1b5ba491ac35239af4a20aa2

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>