package/libvirt: disable stack-protector
Set warning_level to 1 instead of the default value of 2 to disable
stack-protector and avoid the following build failure since the addition
of the package in commit ccfc90e1010e42e6529afae3a5ea8bf7226dabc1:

/tmp/instance-5/output-1/host/opt/ext-toolchain/bin/../lib/gcc/i686-buildroot-linux-uclibc/9.3.0/../../../../i686-buildroot-linux-uclibc/bin/ld: tests/commandhelper.p/commandhelper.c.o: in function `printInput':
commandhelper.c:(.text+0xad): undefined reference to `__stack_chk_guard'

Fixes:
 - http://autobuild.buildroot.org/results/a2657eb18b579752c8217ab356adcb52931f6785

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[yann.morin.1998@free.fr:
  - move to a separate assignment
  - add a big fat comment to explain it
]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>