configs/mx53loco: select BR2_TARGET_UBOOT_NEEDS_OPENSSL
Select  BR2_TARGET_UBOOT_NEEDS_OPENSSL to fix the following
build error:

include/image.h:1383:12: fatal error: openssl/evp.h: No such file or directory

Reported-by: Jan-Benedict Glaw <jbglaw@lug-owl.de>
Signed-off-by: Fabio Estevam <festevam@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit 044c38b71d8cda99e893f0bdcfb18992a229d017)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>