package/dmalloc: fix strndup detection
Fix strndup detection as already done for strdup in commit
f9287b263f0808c2f0632aa1560d88e39fbf970b to avoid the following build
failure raised since bump to version 5.6.5 in commit
736932c71552adc4dfa95c5236d1064860900e8a:

In file included from /nvmedata/autobuild/instance-0/output-1/host/mipsel-buildroot-linux-gnu/sysroot/usr/include/string.h:630:0,
                 from append.c:34:
dmalloc.h:396:7: error: expected identifier or '(' before '__extension__'
 char *strndup(const char *string, const DMALLOC_SIZE max_len);
       ^

Fixes:
 - http://autobuild.buildroot.org/results/2164dac43e2607a3570e8f98957a70f579d06cd3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit dcf695206ed3fb61d2828b6e40c91aa7c4c52fe3)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>