package/ntp: needs either mmu or threads
Fixes:
http://autobuild.buildroot.net/results/f2b466853ed296fdc8b4629f36e5a6447658f82d/

Quoting the first error message:
ntp_io.c:3793:9: error: unknown type name 'blocking_child'

ntp needs either fork or threads:
https://bk.ntp.org/ntp-dev/include/ntp_workimpl.h?PAGE=anno&REV=4d6178063mDeaH-s7PteNqw1DDK-Rw

  #if defined(WORK_FORK) || defined(WORK_THREAD)
  # define WORKER
  #endif

to enable the blocking_child code based on the WORKER define:
https://bk.ntp.org/ntp-dev/include/intreswork.h?PAGE=anno&REV=4d617805zzdW7YeB56-WZ4GbGCcXxw

The build error first occured on April 3rd, 2022:
http://autobuild.buildroot.net/results/31b/31bfdac8411ebf043a39e3277f6d7b008fe337b0/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit f2d9118423612818c897bf075bc055fc7252cfc6)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>