package/qemu: fix build with glibc >= 2.41
When host or target qemu is built with glibc >= 2.41 and Linux
user-land emulation (BR2_PACKAGE_QEMU_LINUX_USER=y or
BR2_PACKAGE_HOST_QEMU_LINUX_USER_MODE=y), compilation fails with
output:

    ../linux-user/syscall.c:362:8: error: redefinition of ‘struct sched_attr’
      362 | struct sched_attr {
          |        ^~~~~~~~~~
    In file included from /usr/include/bits/sched.h:63,
                     from /usr/include/sched.h:43,
                     from /usr/include/pthread.h:22,
                     from /home/buildroot/buildroot/output/per-package/host-qemu/host/include/glib-2.0/glib/deprecated/gthread.h:126,
                     from /home/buildroot/buildroot/output/per-package/host-qemu/host/include/glib-2.0/glib.h:115,
                     from /home/buildroot/buildroot/output/build/host-qemu-9.2.0/include/glib-compat.h:32,
                     from /home/buildroot/buildroot/output/build/host-qemu-9.2.0/include/qemu/osdep.h:161,
                     from ../linux-user/syscall.c:20:
    /usr/include/linux/sched/types.h:98:8: note: originally defined here
       98 | struct sched_attr {
          |        ^~~~~~~~~~

For information, the Buildroot glibc package has been bumped in
commit [1]. Also, major distributions are starting to publish updates
to glibc 2.41. See for example Arch Linux update [2].

This commit adds a package patch to solve this issue.

Fixes:
- https://autobuild.buildroot.org/results/e8733bdf78d8e9448988c3d300c43a47f62375d8/
- and many others...

[1] https://gitlab.com/buildroot.org/buildroot/-/commit/6ecab31fad12a494ec0d2a3767c736a55c80a769
[2] https://gitlab.archlinux.org/archlinux/packaging/packages/glibc/-/commit/7cebc144906a0fb68a5f6e75985b386c722ffbd9

Signed-off-by: James Hilliard <james.hilliard1@gmail.com>
[Julien: reworded the commit log]
Signed-off-by: Julien Olivain <ju.o@free.fr>