package/libssh2: fix build with libressl >= 3.5.0
Fix the following build failure with libressl raised since bump to
version 3.5.2 in commit 8b216927db080b38fdbf1f8b025b6f90a89d4bc2:

crypt.c:71:25: error: field 'h' has incomplete type
   71 |     _libssh2_cipher_ctx h;
      |                         ^

Fixes:
 - http://autobuild.buildroot.org/results/47f492ccd4888fe4a150b36e12c88f1e068d46b6

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>