package/flashrom: disable -Werror
Disable -Werror to avoid the following build failure raised since switch
to meson-package in commit 37dded43ae681e8319d7b76f9a612c71991467a9:

../stlinkv3_spi.c: In function 'stlinkv3_spi_init':
../stlinkv3_spi.c:508:12: error: 'stlinkv3_handle' may be used uninitialized [-Werror=maybe-uninitialized]
  508 |         if (!stlinkv3_handle) {
      |            ^
../stlinkv3_spi.c:485:31: note: 'stlinkv3_handle' was declared here
  485 |         libusb_device_handle *stlinkv3_handle;
      |                               ^~~~~~~~~~~~~~~

Fixes: 37dded43ae681e8319d7b76f9a612c71991467a9
 - http://autobuild.buildroot.org/results/eecabbdd0d21344991379a57e605845e73ef679e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>