package/gensio: needs atomic
gensio needs atomic since bump to version 2.0.1 in commit
0f8d4a6ecd874770ce677b617b2c7f459eb1505d and
https://github.com/cminyard/gensio/commit/5528267b54ac5a8ac0ecd7fd9ba481d654b0e92b:

/nvmedata/autobuild/instance-7/output-1/per-package/gensio/host/bin/../lib/gcc/arc-buildroot-linux-uclibc/11.3.0/../../../../arc-buildroot-linux-uclibc/bin/ld: ../lib/.libs/libgensio.a(gensio_osops.o): in function `gensio_addr_dup':
gensio_osops.c:(.text+0x1558): undefined reference to `__atomic_fetch_add_4'

Fixes:
 - http://autobuild.buildroot.org/results/229e4bd1ba1787953899875ab56721c9609f035a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit 41498af0df34a3ab61ce8e4f846c06bc534e6d16)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>