package/shadow: fix NLS build
NLS is an optional dependency since the addition of the package in
commit f78c5cb5cae93a9e63dad4361d78e1787759382f:

/home/autobuild/autobuild/instance-0/output-1/host/lib/gcc/arm-buildroot-linux-musleabi/12.3.0/../../../../arm-buildroot-linux-musleabi/bin/ld: ../lib/.libs/libshadow.a(libshadow_la-alloc.o): in function `xcalloc':
alloc.c:(.text+0x7c): undefined reference to `libintl_gettext'

Fixes: f78c5cb5cae93a9e63dad4361d78e1787759382f
 - http://autobuild.buildroot.org/results/9f604d09745ffa1f4db3bdcfe0326c236effac0c

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit f82384652c0feed99dc07f08fae5ec1646d38dfc)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>