package/sunxi-mali-utgard-driver: bump to version 2025-07-18
The sunxi-mali-utgard-driver at git version 9926236a is failing
to build with kernel 6.15.

The issue has not been seen in autobuilder, but can be reproduced
with commands:

    cat >.config <<EOF
    BR2_aarch64=y
    BR2_TOOLCHAIN_EXTERNAL=y
    BR2_TOOLCHAIN_EXTERNAL_BOOTLIN=y
    BR2_LINUX_KERNEL=y
    BR2_LINUX_KERNEL_LATEST_VERSION=y
    BR2_LINUX_KERNEL_USE_ARCH_DEFAULT_CONFIG=y
    BR2_PACKAGE_SUNXI_MALI_UTGARD=y
    EOF
    make olddefconfig
    make sunxi-mali-utgard-driver

This new version fixes the issue and builds up to Linux 6.15.

Also, _SITE URL has moved to github benetti-engineering-sas so
let's modify accordingly.

Fixes:

    linux/mali_osk_timers.c: In function ‘_mali_osk_timer_del’:
    linux/mali_osk_timers.c:59:9: error: implicit declaration of function ‘del_timer_sync’ [-Wimplicit-function-declaration]

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
[Julien: add commands to reproduce the issue in commit log]
Signed-off-by: Julien Olivain <ju.o@free.fr>