package/aircrack-ng: fix sqlite3 build
Fix the following build failure raised since bump to version 1.2 in
commit 242227dd86efaaec7c785b32a14e8133f2e86dec:

powerpc-buildroot-linux-gnu-gcc: WARNING: unsafe header/library path used in cross-compilation: '-I/usr/include'
In file included from src/aircrack-ng/aircrack-ng.c:54:
/usr/include/math.h:476:21: error: '_Float128' is not supported on this target
  476 | # define _Mdouble_  _Float128
      |                     ^~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/83a114ce197fb6af53a26ed68184cf3bbb30c8a7

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit a8e9b796c990d2aaaa17c711cefef2918b69bc9d)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>