package/uqmi: fix compile error (gcc false error reporting)
Add upstream suggested patch ([1]) to avoid gcc false error reporting.

Fixes:

  - http://autobuild.buildroot.net/results/ce9e2074bb8486d1ee25232b985d47475faefd63

  dev.c:217:23: error: storing the address of local variable 'complete' in '*req.complete' [-Werror=dangling-pointer=]
    217 |         req->complete = &complete;
        |         ~~~~~~~~~~~~~~^~~~~~~~~~~

[1] http://lists.openwrt.org/pipermail/openwrt-devel/2023-March/040633.html

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit b3cf07d8db2ae0283bbac7e4a06f363c7bc39e58)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>