package/python-grpcio: add BR2_PACKAGE_PYTHON_GRPCIO_ARCH_SUPPORTS
Fix the following build failure raised since the addition of the package
in commit ea45b95c0e54866134c63e88e60489a012b3d134:

In file included from third_party/boringssl-with-bazel/src/include/openssl/base.h:78,
                 from third_party/boringssl-with-bazel/src/include/openssl/ssl.h:145,
                 from ./src/core/tsi/ssl/key_logging/ssl_key_logging.h:23,
                 from ./src/core/lib/security/security_connector/ssl_utils.h:42,
                 from ./src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h:36,
                 from ./src/core/ext/xds/certificate_provider_store.h:44,
                 from src/core/ext/xds/certificate_provider_store.cc:21:
third_party/boringssl-with-bazel/src/include/openssl/target.h:62:2: error: #error "Unknown target CPU"
   62 | #error "Unknown target CPU"
      |  ^~~~~

Fixes: ea45b95c0e54866134c63e88e60489a012b3d134
 - http://autobuild.buildroot.org/results/36686aca1b45f0bf692a60e67a48424b561930a3
 - http://autobuild.buildroot.org/results/4f79c7b1b2fc3306f300ae3ec0aa4439725814c1

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>