package/linux-tools: thermal needs threads
tmon needs threads since its addition in kernel 3.13 and
https://github.com/torvalds/linux/commit/94f69966faf8e70bd655ea25f9dd5b9400567b75:

tmon.c:23:10: fatal error: pthread.h: No such file or directory
   23 | #include <pthread.h>
      |          ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/d7b3d15ebf80ca6dbbbd4554af541182c777e4de

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit ff5c1da7f74dbe44afb2454517bffe07cbcb317e)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>