configs/orangepi_pc_defconfig: bump Linux to 5.10.217 to fix gcc 13.x build
The 5.10.9 kernel fails to build with GCC 13.x:

In file included from <command-line>:
drivers/ata/libahci.c: In function ‘ahci_led_store’:
././include/linux/compiler_types.h:315:45: error: call to ‘__compiletime_assert_321’ declared with attribute error: BUILD_BUG_ON failed: sizeof(_s) > sizeof(long)
  315 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |                                             ^
././include/linux/compiler_types.h:296:25: note: in definition of macro ‘__compiletime_assert’
  296 |                         prefix ## suffix();                             \
      |                         ^~~~~~
././include/linux/compiler_types.h:315:9: note: in expansion of macro ‘_compiletime_assert’
  315 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |         ^~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:39:37: note: in expansion of macro ‘compiletime_assert’
   39 | #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
      |                                     ^~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:50:9: note: in expansion of macro ‘BUILD_BUG_ON_MSG’
   50 |         BUILD_BUG_ON_MSG(condition, "BUILD_BUG_ON failed: " #condition)
      |         ^~~~~~~~~~~~~~~~
./include/linux/nospec.h:58:9: note: in expansion of macro ‘BUILD_BUG_ON’
   58 |         BUILD_BUG_ON(sizeof(_s) > sizeof(long));                        \
      |         ^~~~~~~~~~~~
drivers/ata/libahci.c:1137:23: note: in expansion of macro ‘array_index_nospec’
 1137 |                 pmp = array_index_nospec(pmp, EM_MAX_SLOTS);
      |                       ^~~~~~~~~~~~~~~~~~

This is fixed upstream by commit f07788079f515ca (ata: ahci: fix enum
constants for gcc-13), which has been backported to 5.10.x as of 5.10.184,
so bump to v5.10.217 to fix the build.

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>