boards/odroidc2: fix genimage execution
fix the following error:
ERROR: hdimage(sdcard.img): partition [MBR] (offset 0x1b8, size 0x48) overlaps previous partition bl1 (offset 0x0, size 0xc200)
ERROR: hdimage(sdcard.img): bootloaders, etc. that overlap with the partition table must declare the overlapping area as a hole.

which started at the genimage version bump to 15 commit.

Fixes: https://gitlab.com/buildroot.org/buildroot/-/jobs/1865935217
Signed-off-by: Dagg Stompler <daggs@gmx.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>