package/libcamera-apps: fix build
Buildroot commit 95c385e2d6b92e7afa2d1fac84ecf2dabfb81d25 in -next
branch bumped libcamera to version 0.6.0 which breaks the build:

../core/options.cpp:405:44: error: conversion from
 'std::basic_string_view<char>' to non-scalar type
 'const std::string' {aka 'const std::__cxx11::basic_string<char>'}
 requested
  405 |                 const std::string cam_id =
 *cameras[camera]->properties().get(libcamera::properties::Model);

Added upstream patch, included since version 1.10.0, to fix the problem.

Please note that since version 1.9.1 this package is incompatible with
the current version of ffmpeg used in buildroot so bumping it is not an
option atm:
https://github.com/raspberrypi/rpicam-apps/commit/cbe9921eeddd8e1c2e5798102f485baea5de3f65

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
[Julien: fix Buildroot commit id of libcamera bump]
Signed-off-by: Julien Olivain <ju.o@free.fr>