package/gerbera: fix build with fmt >= 9.0.0
Fix the following build failure with fmt >= 9.0.0 raised since commit
5c83dc5451fb59ffa5cd40d30c4c532dd25e8333:

/tmp/instance-5/output-1/build/gerbera-1.10.0/src/database/sql_database.cc:1688:26:   required from here
/tmp/instance-5/output-1/host/x86_64-buildroot-linux-gnu/sysroot/usr/include/fmt/format.h:3973:36: error: passing 'const fmt::v9::formatter<fmt::v9::join_view<__gnu_cxx::__normal_iterator<const ColumnUpdate*, std::vector<ColumnUpdate> >, __gnu_cxx::__normal_iterator<const ColumnUpdate*, std::vector<ColumnUpdate> >, char>, char, void>::formatter_type' {aka 'const fmt::v9::formatter<ColumnUpdate>'} as 'this' argument discards qualifiers [-fpermissive]
 3973 |       out = value_formatter_.format(map(*it), ctx);
      |             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/56c46fa7e922360d2c4b4093f8a030cc83726799

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 9b911c8e8fe52914c1578b846914d7399450067b)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>