package/rabbitmq-c: bump to version 0.14.0
- Drop patch (already in version)
- Update hash of README.md (updates unrelated to license:
  https://github.com/alanxz/rabbitmq-c/commit/ea9acb88814a9240327bd27a30cdc06e5b69735c
  https://github.com/alanxz/rabbitmq-c/commit/7dab48f03419661133abdf12d53733a4d4369b76
  https://github.com/alanxz/rabbitmq-c/commit/8f8a320c5a9a58647f2f39d66107e7f116f4bc4a)
- This bump will fix the following build failure without the deprecated
  libopenssl engines raised since commit
  623d3bbe43e9193aa8e3395367d01af59071b859:

  /home/autobuild/autobuild/instance-1/output-1/build/rabbitmq-c-0.13.0/librabbitmq/amqp_openssl.c:602:42: error: 'ENGINE_METHOD_ALL' undeclared (first use in this function)
    602 |   if (ENGINE_set_default(openssl_engine, ENGINE_METHOD_ALL) == 0) {
        |                                          ^~~~~~~~~~~~~~~~~

https://github.com/alanxz/rabbitmq-c/releases/tag/v0.14.0

Fixes: 623d3bbe43e9193aa8e3395367d01af59071b859
 - http://autobuild.buildroot.org/results/b95d080a0de635baaea2f08a888746cddcd1f26e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>