package/bdwgc: needs MMU
Fix the following build failure raise since bump to version 8.2.2 in
commit d7619682552dd34f499e9f17b0234af53da743ec and
https://github.com/ivmai/bdwgc/commit/9d8c196268068bb75f86dee0ba75ccd024531e72:

os_dep.c: In function 'block_unmap_inner':
os_dep.c:2668:17: warning: implicit declaration of function 'madvise'; did you mean 'raise'? [-Wimplicit-function-declaration]
 2668 |             if (madvise(start_addr, len, MADV_DONTNEED) == -1)
      |                 ^~~~~~~
      |                 raise

Fixes:
 - http://autobuild.buildroot.org/results/2b9924cb8c36a75e1ca7aefe83e95dc11c10ded6

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>