package/lttng-libust: fix legal-info
COPYING has been removed since version 2.13.0 and
https://github.com/lttng/lttng-ust/commit/c0c0989ab70574e09b2f7e8b48c2da6af664a849
resulting in the following build failure since bump to version 2.13.1 in
commit 733bf73e3ff86dd80e68e22c0ccc2f43e4a3d475:

ERROR: COPYING has wrong sha256 hash:
ERROR: expected: 74125a84c2166300776980166e29de40d5f98d1a75e487f0bbc0c03b4cd2342e
ERROR: got     :

So use the new license files, add BSD-3-Clause (which was added in
version 2.13.0 and
https://github.com/lttng/lttng-ust/commit/d8621b3ea82b7fc1937b0eefb2b1316b2ce361a5)
and don't add BSD-2-Clause and GPL-3.0+ as tests are disabled

Fixes:
 - http://autobuild.buildroot.org/results/470d6401f2a97f4ac91b2d8cfb1af90b638320a9

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>