package/pixman: fix mips build
Disable Loongson MMI fast paths to fix the following mips build failure:

./loongson-mmintrin.h:407:2: error: impossible constraint in 'asm'
  407 |  asm("pinsrh_%3 %0, %1, %2\n\t"
      |  ^~~

Fixes:
 - http://autobuild.buildroot.org/results/75267aa5b5a631f091d4c8cb6ad9baeb5f72ee11
 - http://autobuild.buildroot.org/results/55b7431a50b85c24406131af1932d6f3f6853de6

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit 7e0fbf4dcd4cd0cf17cfe89ebf6808fdace8f01f)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>