package/bpftool: add BR2_PACKAGE_BPFTOOL_ARCH_SUPPORTS
bpftool uses its own local copy of libbpf so add
BR2_PACKAGE_BPFTOOL_ARCH_SUPPORTS to avoid the following build failure
on ARM:

btf.c: In function 'btf_type_by_id':
btf.c:461:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (type_id < btf->start_id)
              ^
bpf.c:62:4: error: #error __NR_bpf not defined. libbpf does not support your arch.
 #  error __NR_bpf not defined. libbpf does not support your arch.
    ^

Fixes:
 - http://autobuild.buildroot.org/results/aae772f1cfb16516a57f310c4f022e80a2a8d65e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit c750dd4e5d03430148841d2d897e90dbe19ce172)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>