package/tftpd: bump to latest git commit
- Update hash of tftpd.c (changes not related to license)
- --include=$(@D)/autoconf/m4 and --disable-tcpwrappers must be passed
  since
  https://git.kernel.org/pub/scm/network/tftp/tftp-hpa.git/commit/?id=fefaa2cc5c2ae1537fccbb552496787130feeeaa
- This bump will also fix the following musl build failure raised since
  latest bump in ee2b57e0c98acf1d02cf66a38c9ec82bd69bcbeb:

  In file included from tftpsubs.h:41,
                   from tftpsubs.c:34:
  /home/autobuild/autobuild/instance-9/output-1/build/tftpd-e52af4207a6e09a1ba21f61d6f85d8b2b1e6efc0/config.h:209:13: error: conflicting types for 'socklen_t'; have 'int'
    209 | typedef int socklen_t;
        |             ^~~~~~~~~

Fixes: ee2b57e0c98acf1d02cf66a38c9ec82bd69bcbeb
 - http://autobuild.buildroot.org/results/4b5320013d8ab50499a459d64a71e0b71814fb2f

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit d4a84e61615553ff678d3c3b52ed33f898e9fcc9)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>