package/libdbi: needs dynamic library
libdbi needs dynamic library to avoid the following build failure raised
since the addition of the package in commit
c6aac6ebdbbd3873110a9e19de1957e49cb9344e:

dbi_main.c:84:2: error: #error no dynamic loading support
   84 | #error no dynamic loading support
      |  ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/9cd56a625cbd52b0c070e2d462e02f5161d9631d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit a24f0e8eeebbd6a77775a5eb5dbe830417fc9d22)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>