package/libgsasl: bump version to 2.2.1
Release notes, since 1.10.0:
2.0.0: https://lists.gnu.org/archive/html/help-gsasl/2022-06/msg00005.html
2.0.1: https://lists.gnu.org/archive/html/help-gsasl/2022-07/msg00000.html
2.2.0: https://lists.gnu.org/archive/html/help-gsasl/2022-09/msg00001.html
2.2.1: https://lists.gnu.org/archive/html/help-gsasl/2024-01/msg00003.html

Updates:
- COPYING.LIB renamed to COPYING.LESSER.
  https://gitlab.com/gsasl/gsasl/-/commit/2492403b4e6d65a3c2d6dd7eee9ddedbc733275b
- Upstream tarball no longer includes the lib prefix.
- COPYING hash changed due to copyright URL update.
  https://gitlab.com/gsasl/gsasl/-/commit/89c4c35d7b0204dc3d6ecbccadab47d76640f0be
- README hash changed due to multiple revisions.
  https://gitlab.com/gsasl/gsasl/-/commits/master/README.md?ref_type=heads
- Tarball's sha256sum mentioned in the release notes was base64-encoded. It was decoded with the following command:
  echo "1FtWLhO9E7n8ILNy9LUyaXQM9iefg28JzhG50yvO4HU=" | base64 -d | xxd -c 32 -p

Also, this libgsasl-2.2.1 fixes a msmtp-1.8.27 build failure. When
using a Buildroot config with:

    BR2_PACKAGE_MSMTP=y
    BR2_PACKAGE_LIBGSASL=y
    BR2_PACKAGE_OPENSSL=y

mtmsp is failing to build with error.

    smtp.c: In function 'smtp_auth':
    smtp.c:1392:19: error: 'GSASL_CB_TLS_EXPORTER' undeclared (first use in this function); did you mean 'GSASL_CB_TLS_UNIQUE'?
     1392 |                 ? GSASL_CB_TLS_EXPORTER : GSASL_CB_TLS_UNIQUE,
          |                   ^~~~~~~~~~~~~~~~~~~~~

This GSASL_CB_TLS_EXPORTER was introduced in gsasl v2.1.0. This bump
fixes this build failure.

Fixes:
https://gitlab.com/buildroot.org/buildroot/-/commit/e9007bc74ed571234bb938c1fdc4cc99d6571bfc
https://autobuild.buildroot.org/results/835fec8275d4ff6eed298b892807dd295436d99d

Signed-off-by: Akhilesh Nema <nemaakhilesh@gmail.com>
[Julien:
  - add other release notes since previous version
  - add comment about msmtp build failure fix
]
Signed-off-by: Julien Olivain <ju.o@free.fr>