package/gdal: deflate64 needs libzlib
deflate64 unconditionally uses FAR since its addition with
https://github.com/OSGeo/gdal/commit/d6baebcc73ffc2ede6e9635846676b275b02bab3
resulting in the following build failure with zlib-ng since bump to
version 3.8.2 in commit d2e349301b79ad3a1840083714ee396f4302b68a:

In file included from /home/autobuild/autobuild/instance-2/output-1/build/gdal-3.8.2/frmts/zlib/contrib/infback9/infback9.c:6:
/home/autobuild/autobuild/instance-2/output-1/build/gdal-3.8.2/frmts/zlib/contrib/infback9/minified_zutil.h:46:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'uchf'
   46 | typedef uch FAR uchf;
      |                 ^~~~

Fixes: d2e349301b79ad3a1840083714ee396f4302b68a
 - http://autobuild.buildroot.org/results/8b55108dee4faa98c234d00a1a22b62ed948e8d3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>