package/shairport-sync: fix build w/ mbedtls v3.6
Since [1] when trying to build this package with mbedtls v3.6 the
following error is happening:

```
player.h:12:10: fatal error: mbedtls/havege.h: No such file or directory
   12 | #include <mbedtls/havege.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

This error can be reproduced with the following config:

```
cat <<EOF >.config
BR2_arm=y
BR2_cortex_a7=y
BR2_TOOLCHAIN_EXTERNAL=y
BR2_TOOLCHAIN_EXTERNAL_BOOTLIN=y
BR2_PACKAGE_MBEDTLS=y
BR2_PACKAGE_SHAIRPORT_SYNC=y
EOF
make olddefconfig
make
```

This patch backport the upstream commit [2] that add support for
mbedtls v3.

[1] 3481a9643f package/mbedtls: bump to version 3.6.3.1
[2] https://github.com/mikebrady/shairport-sync/commit/d73b585c6f6d9136ae7a04243a54d734fa57d779

Signed-off-by: Thomas Perale <thomas.perale@mind.be>
Signed-off-by: Julien Olivain <ju.o@free.fr>
(cherry picked from commit d53f8f26910df2f75e0f4a053fd6ef0c65e639c1)
Signed-off-by: Titouan Christophe <titouan.christophe@mind.be>