package/bluez5_utils: hid needs hog
Build of hid without hog is broken since commit
fb9fc969d91f69851b4c70dba512b607e52bda7b:

/home/buildroot/autobuild/instance-3/output-1/host/opt/ext-toolchain/bin/../lib/gcc/i586-buildroot-linux-musl/9.3.0/../../../../i586-buildroot-linux-musl/bin/ld: profiles/input/bluetoothd-manager.o: in function `input_init':
manager.c:(.text+0x2fd): undefined reference to `input_set_auto_sec'

Fixes:
 - http://autobuild.buildroot.org/results/9222879c9fe958e01e33f69531270355ea016d17

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Michael Nosthoff <buildroot@heine.tech>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 9850f262fd6546d15ae27f84a0e36411abc2b7b5)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>