board/qemu/aarch64-sbsa: use partition-type-uuid for genimage-15
Genimage 15 restricted the partition-type option to mbr and hybrid
partition-table-type and now prints a warning when it is used [1]:

ERROR: hdimage(disk.img): part boot: 'partition-type' is only valid for mbr and hybrid partition-table-type

[1] https://github.com/pengutronix/genimage/commit/1d72d8091f83790a0a35a1ea7dc25d46adba8876

Sync the genimage.cfg with the one used for aarch64_efi_defconfig

Fixes:
https://gitlab.com/buildroot.org/buildroot/-/jobs/1929717179
https://gitlab.com/buildroot.org/buildroot/-/jobs/1921792262

FTR, the magic UUID are from:
    https://en.wikipedia.org/wiki/GUID_Partition_Table#Partition_type_GUIDs

Signed-off-by: Romain Naour <romain.naour@gmail.com>
Cc: Dick Olsson <hi@senzilla.io>
Cc: Pierre-Jean Texier <texier.pj2@gmail.com>
[yann.morin.1998@free.fr: add Wikipedia link]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>