package/python-magic-wormhole-mailbox-server: add missing python-setuptools dependency
TestPythonPy3MagicWormhole runtime test is currently broken due to
missing python-setuptools dependency.

wormhole-mailbox server fail to start with:

    File "/usr/lib/python3.12/site-packages/wormhole_mailbox_server/server_tap.py", line 11, in <module>
    File "/usr/lib/python3.12/site-packages/wormhole_mailbox_server/database.py", line 5, in <module>
  ModuleNotFoundError: No module named 'pkg_resources'

Signed-off-by: Romain Naour <romain.naour@smile.fr>
Signed-off-by: Julien Olivain <ju.o@free.fr>