package/libcamera: bump to version 40f5fddca7f774944a53f58eeaebc4db79c373d8
This will fix the following build failure raised since commit
c09f126f570355b8ec134724b453300a4811339c thanks to
https://git.linuxtv.org/libcamera.git/commit/?id=c52e8429cce91dadf98378d87015d8f476a44f70:

/tmp/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/sparc-buildroot-linux-uclibc/9.3.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: src/libcamera/base/libcamera-base.so.p/message.cpp.o: in function `libcamera::Message::registerMessageType()':
message.cpp:(.text+0x290): undefined reference to `__atomic_fetch_add_4'

Fixes:
 - http://autobuild.buildroot.org/results/6e3471df8e9312a1789ca05ae70cc2283bfeec23

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>