configs/rock5b_defconfig: add missing U-Boot build dependency
When building the rock5b with BR2_PER_PACKAGE_DIRECTORIES enabled, the
following error occurs from U-Boot.

  tools/mkeficapsule.c:19:10: fatal error: uuid/uuid.h: No such file or
  directory
     19 | #include <uuid/uuid.h>
        |          ^~~~~~~~~~~~~

Signed-off-by: Brandon Maier <brandon.maier@collins.com>
Reviewed-by: Niklas Cassel <cassel@kernel.org>
Signed-off-by: Julien Olivain <ju.o@free.fr>