package/xtables-addons: bump to version 3.22
Support for up to Linux 6.1 by fixing the following build failure:

/tmp/instance-5/output-1/build/xtables-addons-3.21/extensions/xt_CHAOS.c: In function ‘xt_chaos_total’:
/tmp/instance-5/output-1/build/xtables-addons-3.21/extensions/xt_CHAOS.c:70:46: error: implicit declaration of function ‘prandom_u32’; did you mean ‘prandom_u32_max’? [-Werror=implicit-function-declaration]
   70 |         if (!ret || hotdrop || (unsigned int)prandom_u32() > delude_percentage)
      |                                              ^~~~~~~~~~~
      |                                              prandom_u32_max

https://fossies.org/linux/privat/xtables-addons-3.22.tar.xz/xtables-addons-3.22/doc/changelog.rst

Fixes:
 - http://autobuild.buildroot.org/results/4564ba888156710819f6bd86117e0c0bdd513dba

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>