package/wpa_supplicant: need EAP when HOTSPOT is enabled.
Make WPA_SUPPLICANT_HOTSPOT depend on WPA_SUPPLICANT_EAP, Otherwise,
compilation fails with errors like:

interworking.c:1439:15: error: ‘struct wpa_ssid’ has no member named ‘eap’

Signed-off-by: Nicolas Cavallari <nicolas.cavallari@green-communications.fr>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>