package/gnuplot: fix readline dependency
--without-readline is interpreted as --with-readline=builtin since bump
to version 5.4.0 in commit 263da09323e83bb3d6552b70b739523b66459df8 and
https://github.com/gnuplot/gnuplot/commit/b492ea63bd604081ffb9dee3843e295b0b29df85
so add a mandatory dependency to readline or libedit to gnuplot

As a side-effect, this will avoid the following build failure with
builtin readline raised since bump to version 6.0.0 in commit
5f11ce4aeaba99917778c384b236d267e78a7b29:

/home/autobuild/autobuild/instance-14/output-1/host/lib/gcc/arm-buildroot-linux-gnueabi/13.2.0/../../../../arm-buildroot-linux-gnueabi/bin/ld: history.o: in function `read_history':
history.c:(.text+0xa8): undefined reference to `gp_read_history'

Fixes: 5f11ce4aeaba99917778c384b236d267e78a7b29
 - http://autobuild.buildroot.org/results/5e45dd8f9071694110c8481f222b9b07b6a97ef3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 93864cef0b1ec94c44498a4edd31de92725b28b2)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>