package/clamav: doesn't build with zlib-ng
clamav doesn't build with zlib-ng since bump to version 1.9.9-b1 in
commit 1f7b12a0b4572d7e763c431a63c22cfb912b8b14 and the removal of FAR:
https://github.com/zlib-ng/zlib-ng/commit/0db1040667b13c0f9405af810f669857a487b08e:

In file included from nsis/nsis_zlib.h:32,
                 from nsis/nulsft.c:38:
nsis/nsis_zutil.h:36:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'uchf'
   36 | typedef uch FAR uchf;
      |                 ^~~~

Fixes:
 - http://autobuild.buildroot.org/results/524ee31face8be6a813829b036c4d6134ee5ca98

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit f7744aba7bcc7f4ad38ff4bba3d0c37969544fce)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>