package/lynis: add wchar dependency
Since the introduction of the package lynis in 48bce6ad8f autobuild
failure for the gzip package started appearing on configuration
without wchar support with the following error message:

vasnprintf.c:355:38: warning: implicit declaration of function 'wctomb' [-Wimplicit-function-declaration]
  355 | #   define local_wcrtomb(S, WC, PS)  wctomb ((S), (WC))
      |                                      ^~~~~~

This error happens when building gzip without BR2_USE_WCHAR dependency.
The gzip package already depends on BR2_USE_WCHAR, this patch also apply
this dependency to the lynis package.

Fixes:
https://autobuild.buildroot.org/results/fbf/fbf31c8c09496cd3fe02e8ed55939dad5c1cbaec
https://autobuild.buildroot.org/results/560/56083310acedba31dccc1f6594f814347bf21caf
https://autobuild.buildroot.org/results/1d9/1d97e3f0c626421fdae45e794f02c560d1b9080c

Signed-off-by: Thomas Perale <thomas.perale@mind.be>
Signed-off-by: Julien Olivain <ju.o@free.fr>