package/ledmon: add upstream patch to fix build w/ gcc-14
Add an upstream patch to fix a build issue related to uint64_t:

utils.c: In function ‘get_uint64’:
utils.c:118:18: error: passing argument 1 of ‘str_toul’ from incompatible pointer type [-Wincompatible-pointer-types]
  118 |         str_toul(&defval, p, NULL, 16);
      |                  ^~~~~~~
      |                  |
      |                  uint64_t * {aka long long unsigned int *}
In file included from utils.c:48:
utils.h:412:29: note: expected ‘long unsigned int *’ but argument is of type ‘uint64_t *’ {aka ‘long long unsigned int *’}

Fixes:

  https://autobuild.buildroot.org/results/51af1d7bf71061f22d49213951a5f6a9565710c3/

Signed-off-by: Dario Binacchi <dario.binacchi@amarulasolutions.com>
Signed-off-by: Julien Olivain <ju.o@free.fr>
(cherry picked from commit c8923662cc7e1f0a1d30d0926f979c21d36aa9df)
Signed-off-by: Thomas Perale <thomas.perale@mind.be>