package/dhcpdump: bump to version 1.9
- Switch to an active fork (which is already used by Fedora 39)
- Drop patch (not needed since
  https://github.com/bbonev/dhcpdump/commit/be272278c3c3fd7fe0d30203d9047fff6b83fa44)
- HAVE_STRSEP has been dropped since
  https://github.com/bbonev/dhcpdump/commit/0f7c525da62e7ae928782b2beae9c5313fb972f8
- CFLAGS and LDFLAGS must be set since
  https://github.com/bbonev/dhcpdump/commit/6eac74e7efb88bcce9423b3a452dcaa1d48850f0
- This bump will fix the following build failure with gcc 14 thanks to
  https://github.com/bbonev/dhcpdump/commit/be272278c3c3fd7fe0d30203d9047fff6b83fa44:

dhcpdump.c: In function 'pcap_callback':
dhcpdump.c:153:17: error: implicit declaration of function 'strftime' [-Wimplicit-function-declaration]
  153 |                 strftime(timestamp, sizeof(timestamp), "%Y-%m-%d %H:%M:%S.",
      |                 ^~~~~~~~
dhcpdump.c:28:1: note: include '<time.h>' or provide a declaration of 'strftime'
   27 | #include "dhcp_options.h"
  +++ |+#include <time.h>
   28 |

https://github.com/bbonev/dhcpdump/releases/tag/v1.9

Fixes:
 - http://autobuild.buildroot.org/results/9e559d634ac4e06f74f7b9e0402e45209aef2952

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>