package/gstreamer1/gst1-plugins-base: fix build with gcc 4.8
Fix the following build failure with gcc 4.8 raised since bump to
version 1.20.0 in commit 801131157dcef2c97e947a1d3e8c9bfa7aa3d870:

../gst-libs/gst/video/video-converter.c: In function 'convert_I420_v210':
../gst-libs/gst/video/video-converter.c:3771:7: error: 'for' loop initial declarations are only allowed in C99 mode
       for (int j = width * 4 - 1; j >= 0; j--) {
       ^

Fixes:
 - http://autobuild.buildroot.org/results/c4b1449f35debcbabff7e42abe239695d4ad4d21

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>