package/mokutil: select libxcrypt if needed
Fix the following build failure raised since the addition of the package
in commit 2e6e121496bfcbe09c018558be13733077b6df9b:

mokutil.c:45:10: fatal error: crypt.h: No such file or directory
   45 | #include <crypt.h>
      |          ^~~~~~~~~

Fixes: 2e6e121496bfcbe09c018558be13733077b6df9b
 - http://autobuild.buildroot.org/results/59e470ad6bf7f48314cd26ed4163c095e4c803ab

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>