package/qpdf: requires RC4 support in openssl
Fix the following build failure raised since bump to version 10.5.0 in
commit b5352c2177011ca389cbb7c68e78447549cbdaaa:

libqpdf/QPDFCrypto_openssl.cc: In constructor 'QPDFCrypto_openssl::QPDFCrypto_openssl()':
libqpdf/QPDFCrypto_openssl.cc:46:9: error: 'EVP_rc4' was not declared in this scope
   46 |     rc4(EVP_rc4()),
      |         ^~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/3b7f19ecb3303c9c9eb89c493c7e0d8a47b4be95

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>