package/dc3dd: needs MMU
savewd.c:75:27: error: implicit declaration of function 'fork' [-Wimplicit-function-declaration]
   75 |           wd->val.child = fork ();

Fixes:
https://autobuild.buildroot.net/results/40a/40a90638f90260ca2cb51bac03b0f8fb23a6ccc4/

The build error occurred already in January 2025:
https://autobuild.buildroot.net/results/9f3/9f3fefe5578dc41272e460146b566ac20f6cde75/
so a backport to the LTS branches should be considered.

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 4df3fa1ab50fb280f011550edc5b178e7a4a0482)
Signed-off-by: Thomas Perale <thomas.perale@mind.be>