configs/acmesystems_acqua_a5_*: remove at91bootstrap3 license
When using a specific git repo and version for at91bootstrap3,
BR2_TARGET_AT91BOOTSTRAP3_LICENSE_FILES defaults to "LICENSES/MIT.txt".
However the git version we use (namely v3.10.3) does not provide this
file. Actually, it does not provide a license file at all. This causes
‘make legal-info’ to fail with:

>>> at91bootstrap3 v3.10.3 Collecting legal info
sha256sum: /builds/buildroot.org/buildroot/output/build/at91bootstrap3-v3.10.3/LICENSES/MIT.txt: No such file or directory
ERROR: while checking hashes from boot/at91bootstrap3/at91bootstrap3.hash
ERROR: LICENSES/MIT.txt has wrong sha256 hash:
ERROR: expected: 5a3809b1c2ba13b7242572322951311c584419f1f8516f665d6c06f0668d78de
ERROR: got     :
ERROR: Incomplete download, or man-in-the-middle (MITM) attack

Let's be explicit that there is no license file to check.

Fixes:
 - https://gitlab.com/buildroot.org/buildroot/-/jobs/12992815386
 - https://gitlab.com/buildroot.org/buildroot/-/jobs/12992815390

Signed-off-by: Edgar Bonet <bonet@grenoble.cnrs.fr>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit df61ce39c1ae66e9778f225e875ce191275835b7)
Signed-off-by: Thomas Perale <thomas.perale@mind.be>