package/botan: fix build with sh4{a, eb, aeb}
Fix the following build failure with sh4{a,eb,aeb} probably raised since
the addition of the package in commit
e43da7bb32285bbd41b38a379aef77132d149df7:

  ERROR: Unknown or unidentifiable processor "sh4a"

Fixes:
 - http://autobuild.buildroot.org/results/fb6885a8a299f20ed77e4c10b330d2a2a7853931

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit dbff193c74bfda9cee96e3f6975f7430dd5acbd4)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>