package/nut: needs threads
threads are mandantory since bump to version 2.8.2 in commit
4edd837ac0193db83202030ee2997ac811e6bc45 and
https://github.com/networkupstools/nut/commit/ff401e538bcbead62a3532887135518ef9e779df:

In file included from nutipc.cpp:38:
../include/nutipc.hpp:455:3: error: 'pthread_t' does not name a type
  455 |   pthread_t m_impl;
      |   ^~~~~~~~~

Fixes: 4edd837ac0193db83202030ee2997ac811e6bc45
 - http://autobuild.buildroot.org/results/d16a24d60b298d7616a516ec0c6c30696ed93a58

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit ddc46ee1a2024ec9eb38718e34ab9aca38a7302b)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>