package/pistache: fix build with gcc >= 13
Fix the following build failure with gcc >= 13:

In file included from ../include/pistache/reactor.h:19,
                 from ../src/common/reactor.cc:13:
../include/pistache/flags.h:29:35: error: 'uint8_t' was not declared in this scope
   29 |         struct TypeStorage<sizeof(uint8_t)>
      |                                   ^~~~~~~
../include/pistache/flags.h:17:1: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   16 | #include <iostream>
  +++ |+#include <cstdint>
   17 | #include <type_traits>

Fixes:
 - http://autobuild.buildroot.org/results/d3b6eb6fb943d69571a311235944df879fccc831

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 6bb275a59a2a0d8454a1121b2660d382c2476b2d)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>