package/batman-adv: needs CONFIG_CRC16
CONFIG_CRC16 is needed to avoid the following build failure:

ERROR: modpost: "crc16" [/nvmedata/autobuild/instance-6/output-1/build/batman-adv-2021.4/net/batman-adv/batman-adv.ko] undefined!

Fixes:
 - http://autobuild.buildroot.org/results/64bf0f89ef444dda4d1277c0e46d189ad2515713

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Christian Stewart <christian@paral.in>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>