package/libcamera-apps: X11 support needs libdrm
- X11 support needs libdrm (optional libdrm dependency already
  present in libcamera-apps.mk)

Fixes:

  http://autobuild.buildroot.net/results/5df48038df5deb4f1e85287cde9a403c5681c28e

  .../build/libcamera-apps-2d1009e3badcc8047361ff81149ad6cba3b911b5/preview/egl_preview.cpp:18:10: fatal error: libdrm/drm_fourcc.h: No such file or directory
     18 | #include <libdrm/drm_fourcc.h>
        |          ^~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit e2bc5e916beedc1965da2a7bf9a86e74b24a5562)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>