configs/amarula_vyasa_rk3288_defconfig: bump to Linux version 6.1.91
Build fails with gcc 13 with:
drivers/ata/libahci.c: In function 'ahci_led_store':
././include/linux/compiler_types.h:357:45: error: call to
'__compiletime_assert_302' declared with attribute error: BUILD_BUG_ON failed:
sizeof(_s) > sizeof(long)
  357 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)

As explained in Linux commit[0] that fixes the build, sizeof() of enum
like '(1<<31)' translate to a 64-bit type, but we expect a 32-bit type.
So commit[0] makes sure the data type to be 32-bits wide by using BIT()
macro.

Fixes:
https://gitlab.com/buildroot.org/buildroot/-/jobs/6865596548

[0]:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=97e28deab8bfe70d5687650f94484f8f9101e566

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>