package/wireplumber: mark broken on uClibc
../lib/wp/log.c:780:49: error: implicit declaration of function ‘gettid’;
 did you mean ‘getgid’? [-Wimplicit-function-declaration]
  780 |   g_autofree gchar *tid = g_strdup_printf("%d", gettid());

The problem was hidden by pipewire being broken with uClibc since at
least Sep 2024: https://autobuild.buildroot.net/results/ee5/ee50c8331946814c2fecb0ca56ca51c1bb0bc551/

Pipewire was bumped from 0.3.81 to 1.2.2 in Aug 2024 with buildroot commit
93b72692c36f8357e867650f4b8fac91dff375f5 which afaics caused all uClibc
builds to fail due to missing tss_t() whose usage was added to pipewire in
version 1.1.81, see
https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/de0db48f17aa391917ff5b430b7b9fe1dac443fe
and later removed with
https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/9c19284f7f062a50e059b0593068429b345acf34
in version 1.3.81.

In wireplumber the relevant part of code with gettid() was added in
version 0.5.9. Buildroot bumped wireplumber from 0.5.5 directly to 0.5.10
with commit c42b26bb471a260e2bb3da7988af77f78b2b4280.

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
[Julien: unwrap URLs in commit log]
Signed-off-by: Julien Olivain <ju.o@free.fr>