package/perl: bump perl-cross to version 1.4
This bump will fix the following static build failure with berkeleydb
thanks to
https://github.com/arsv/perl-cross/commit/31dac3e264a7f1f53dbf49570771123ebd514055:

/nvmedata/autobuild/instance-6/output-1/host/lib/gcc/mipsel-buildroot-linux-uclibc/10.3.0/../../../../mipsel-buildroot-linux-uclibc/bin/ld: lib/auto/DB_File/DB_File.a(DB_File.o): in function `ParseOpenInfo':
DB_File.c:(.text+0x7d30): undefined reference to `db_create'

Fixes:
 - http://autobuild.buildroot.org/results/e01a042185b2221bee815bb9096c4419eeb6e558

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 0425b12daf0d95abd4d5309426bc4af915a626b3)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>