package/wlroots: fix uclibc build
Fix the following uclibc build failure raised since at least bump to
version 0.11.0 in commit 0bc9c89612cc1f41f9a64f6e889f8bcd8a871e30:

In file included from ../include/wlr/types/wlr_data_device.h:13,
                 from ../types/data_device/wlr_drag.c:7:
../include/wlr/types/wlr_seat.h:221:18: error: field 'last_event' has incomplete type
  221 |  struct timespec last_event;
      |                  ^~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/3501ceb4290638b2f6d70aaa4d8ce74feec3a525

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
(cherry picked from commit 301502b7f7e3d1c7b99bab8addbbcdc794bf8d50)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>