package/ibm-sw-tpm2: fix openssl build
Fix the following build failure raised since bump of openssl to version
3.2.0 in commit 973b1eba5a4ee72f040bd471b147267e36be73ad:

In file included from BnValues.h:327,
                 from Global.h:80,
                 from Tpm.h:78,
                 from ACTCommands.c:62:
TpmToOsslMath.h:83:5: error: #error Untested OpenSSL version
   83 | #   error Untested OpenSSL version
      |     ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/f22867e71dca64d4ab5fee4db39fe9b1899f4b85

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>