package/boost: fix sparc build
Fix the following build failure on sparc raised since bump to version
1.77.0 in commit d39d8f7cee9b4634e6f490020204f63fae419e8e:

./boost/predef/architecture/sparc.h:37:38: error: missing ')' in expression
   37 | #   if !defined(BOOST_ARCH_SPARC) && (defined(__sparcv9) || defined(__sparc_v9__)
      |                                      ^

Fixes:
 - http://autobuild.buildroot.org/results/c1f15e3a0cefb7e65e5288fb4564d59a3b06a0bd

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>