package/c-icap: bump version to 0.5.14
0.5.11: https://sourceforge.net/p/c-icap/mailman/message/38634903/
0.5.12: https://sourceforge.net/p/c-icap/mailman/message/58723532/
0.5.13: https://github.com/c-icap/c-icap-server/compare/C_ICAP_0.5.12...C_ICAP_0.5.13
        (no announcement found)
0.5.14: https://sourceforge.net/p/c-icap/mailman/message/59202148/

Rebased patch 0001 due to upstream commit
https://github.com/c-icap/c-icap-server/commit/1559d1662a9c0cd8280073202f187f0d5c080f87

Rebased patch 0003 due to upstream commit
https://github.com/c-icap/c-icap-server/commit/b650bfdd4ac5aa32fd1b2de8cc0a47e2dc08c6d7

Removed patch 0004 which is included in this release:
https://github.com/c-icap/c-icap-server/commit/16cdaa505db2108d9a7c42baa3779f5831e62916

Renamed patches 0005 & 0006.

Disabled zstd support added upstream with commit
https://github.com/c-icap/c-icap-server/commit/1559d1662a9c0cd8280073202f187f0d5c080f87
due to build errors when enabled:

encode.c: In function 'ci_compress_to_membuf':
encode.c:75:16: error: implicit declaration of function
 'ci_zstd_compress_to_membuf'; did you mean 'ci_decompress_to_membuf'?
 [-Wimplicit-function-declaration]

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>