package/freeswitch: disable mod_enum to fix build with glibc 2.43
Build is broken with glibc 2.43:

mod_enum.c: In function 'add_result':
mod_enum.c:246:23: error: passing argument 1 of '__assert_single_arg'
 makes integer from pointer without a cast [-Wint-conversion]
  246 |         switch_assert(new_result);
      |                       ^~~~~~~~~~
      |                       |
      |                       enum_record_t * {aka struct enum_record *}

Since both services (e164.org, freenum.org) used in the default
configutation of mod_enum
https://github.com/signalwire/freeswitch/blob/master/src/mod/applications/mod_enum/conf/autoload_configs/enum.conf.xml

seem to be dead for years now:
https://community.asterisk.org/t/asterisk-network-interconnect/88659

we do not care to try to fix the build error.
Instead the optional support for mod_enum is removed from the package.

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>