package/efivar: needs threads
Add a thread dependency as Upstream quickly closed
https://github.com/rhboot/efivar/pull/238 to fix the following build
failure without threads raised since bump to version 38 in commit
f24029b561fbda0953c7dbd93d2485b03873996d and
https://github.com/rhboot/efivar/commit/cff88dd96b9d43e2c5875a24ba6180b196890ded:

thread-test.c:14:10: fatal error: pthread.h: No such file or directory
   14 | #include <pthread.h>
      |          ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/f2da14f91dc602a32dd5b2b7bdf3d3aa43afa7f4

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit c29f6d63e0adebc8502dd707d3e4050af254d342)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>