package/hawktracer: bump to 3c22b3908912e2ec727fd2ddc5dbfe7464e6b4a5
This bump will fix the following build failure with gcc >= 12:

/tmp/instance-8/output-1/build/hawktracer-2ec19d71923344148928ef45fce549eda67030a4/hawktracer.cpp: In function 'HT_Thread* ht_thread_create(ht_thread_callback_t, void*)':
/tmp/instance-8/output-1/build/hawktracer-2ec19d71923344148928ef45fce549eda67030a4/hawktracer.cpp:1006:28: error: no matching function for call to 'operator new(sizetype, std::thread*)'
 1006 |     new(&th->th) HT_Thread();
      |                            ^

https://github.com/amzn/hawktracer/compare/e53b07bc812c4cfe8f6253ddb48ac43de8fa74a8...2ec19d71923344148928ef45fce549eda67030a4

Fixes:
 - http://autobuild.buildroot.org/results/d18a1b2ee6cdcb289567ae90b2d836844427b5f6

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>