configs/solidrun_{macchiatobin, clearfog_gt_8k}: disable SSP
The Armada target does not provide platform level support for SSP.

Fixes link failure:

(.text.asm.update_stack_protector_canary+0x4): undefined reference to `plat_get_stack_protector_canary'

This error does not show up on CI jobs because SSP was effectively always
disabled until the previous commit.

Signed-off-by: Baruch Siach <baruch@tkos.co.il>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>