package/libpsl: require libiconv if !BR2_ENABLE_LOCALE
Fixes build error

Checking for function "iconv_open" : NO
Header <iconv.h> has symbol "iconv_open" : NO

output/build/libpsl-0.21.1/meson.build:101:4:
 ERROR: Problem encountered: iconv implementation not found

using this defconfig:

BR2_TOOLCHAIN_BUILDROOT_WCHAR=y
BR2_PACKAGE_LIBPSL=y

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Reviewed-by: Adrian Perez de Castro <aperez@igalia.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>