package/janus-gateway: fix build with libressl >= 3.5.0
Fix the following build failure with libressl raised since bump to
version 3.5.2 in commit 8b216927db080b38fdbf1f8b025b6f90a89d4bc2:

dtls-bio.c:40:1: error: variable 'janus_dtls_bio_agent_methods' has initializer but incomplete type
   40 | static BIO_METHOD janus_dtls_bio_agent_methods = {
      | ^~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/92fe19446b40551c0139254d9efc6b3904fa287a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>