package/shadow: disable on uclibc
shadow unconditionally uses reallocarray and explicit_bzero
since bump to version 4.14.3 in commit
8a01774d9897310c00a0945865f5a6d5167dfca3 and
https://github.com/shadow-maint/shadow/commit/1aa22c14674e14e84efa171614dea2b515d5a223
https://github.com/shadow-maint/shadow/commit/0e0a310acf5111251589116343897a63ebc88e7a
resulting in the following uclibc build failure:

/home/autobuild/autobuild/instance-9/output-1/host/lib/gcc/arc-buildroot-linux-uclibc/13.1.1/../../../../arc-buildroot-linux-uclibc/bin/ld: groups.o: in function `main':
groups.c:(.text.startup+0x20): undefined reference to `reallocarray'

Fixes:
 - http://autobuild.buildroot.org/results/98be07d299aa383a447a1f1dd2924a00c1a29a34

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[Peter: add a comment about what functions are missing, reallocf reference]
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>