package/softhsm2: select BR2_PACKAGE_LIBOPENSSL_ENGINES
softhsm2 unconditionally calls the (deprecated) ENGINE_* logic in
libopenssl resulting in a build failure when
!BR2_PACKAGE_LIBOPENSSL_ENGINES since commit
623d3bbe43e9193aa8e3395367d01af59071b859:

OSSLCryptoFactory.cpp: In constructor 'OSSLCryptoFactory::OSSLCryptoFactory()':
OSSLCryptoFactory.cpp:146:9: error: 'ENGINE_load_rdrand' was not declared in this scope
  146 |         ENGINE_load_rdrand();
      |         ^~~~~~~~~~~~~~~~~~

Fixes: 623d3bbe43e9193aa8e3395367d01af59071b859
 - http://autobuild.buildroot.org/results/9d0047755d19f1f27a42a758277de8d7a3366832

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>