package/libtheora: fix build on arm big-endian
Buildroot commit 5e769b87ecfb5d61c6f32fac3f8cdf2fb24e91a6 bumped
libtheora to version 1.2.0 and forgot to disable asm on arm big-endian
as well.

Fixes:
https://autobuild.buildroot.net/results/8af/8af9ce8c03b00da2dcf29bc1c6f4afef9a002a58/

arm/armint.h:24:5: error: #error "Big-endian configurations are not
 supported by the ARM asm. " "Reconfigure with --disable-asm or undefine
 OC_ARM_ASM."

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>