package/resiprocate: bump version to 1.13.2
Release notes:
https://github.com/resiprocate/resiprocate/blob/resiprocate-1.13.2/CHANGELOG.md

Switched _SITE to github, the previous URL redirects to github.com.

Removed patches which are included in this release.

License file was renamed and updated:
https://github.com/resiprocate/resiprocate/commits/resiprocate-1.13.2/LICENSE.md

Switch build system to cmake, removed apps-specific option:
- sipdial is built if OpenSSL is enabled:
  https://github.com/resiprocate/resiprocate/blob/resiprocate-1.13.2/apps/CMakeLists.txt#L6
- clicktocall build is broken
  AddressTranslator.cxx: In member function 'void clicktocall::AddressTranslator::
    addTranslation(const resip::Data&, const resip::Data&)':
  AddressTranslator.cxx:55:16: error: assignment of read-only variable 'flags'
     55 |          flags |= std::regex_constants::nosubs;

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>