package/minetest: add missing header "memory" required since gcc 11
Backport from upstream.

Fixes:

minetest-5.4.1/src/clientiface.h:444:36: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
  444 |         ClientInterface(const std::shared_ptr<con::Connection> &con);

Signed-off-by: Romain Naour <romain.naour@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>