package/igh-ethercat: fix build with kernel >= 6.15
Buildroot commit c6e914819774212e79be19f62706f653b9646f11 bumped the
package from 1.6.3 to 1.6.8. The previous version 1.6.3 failed to build
with kernel >= 6.15 as seen here:
https://autobuild.buildroot.net/results/7f4/7f4b3e632a5de67dec2624a2097045ec4d767246/
"examples/mini/mini.c:528:5: error: implicit declaration of function
 'del_timer_sync' [-Wimplicit-function-declaration]
  528 |     del_timer_sync(&timer);"

The bump to 1.6.8 includes a commit which fixes the problem:
https://gitlab.com/etherlab.org/ethercat/-/commit/240080f11062cca42f9132cd32fad3b993502665

but it only masked other build errors which were found by the
autobuilders:
https://autobuild.buildroot.net/results/1a5/1a546ee2217e7843b852a5b79b477ef23df6a064/
"examples/tty/tty.c:236:5: error: implicit declaration of function
 'del_timer_sync' [-Wimplicit-function-declaration]
  236 |     del_timer_sync(&timer);"

which need similar fixes.

Fixes:
https://autobuild.buildroot.net/results/0ba/0ba7163e5012309d3a31aa7186ca95a9d5c8de69/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>