package/mpd: update to version 0.24.13
Version 0.24.13 change log:

* configuration
  - add range checks to number parser
  - copy replay_gain_mode when creating a new partition
* storage
  - curl: eliminate auth probe requests
* decoder
  - opus: do not add 5 dB to Opus header playback gain
* tags:
  - id3: limit ID3 tags to 4 MB
* output
  - pipewire: fix file descriptor leak bug after connect failure
  - pipewire: support the "media.album" tag
* systemd: allow AF_NETLINK when UPnP is enabled

In addition, the fix for fmt 12.2.0 is also included in this release
(https://github.com/MusicPlayerDaemon/MPD/commit/88d5b52).

Fixes:
../src/net/ToString.cxx: In function 'std::string ToString(SocketAddress)':
../src/net/ToString.cxx:80:37: error: 'format' is not a member of 'fmt'
   80 |                         return fmt::format("[{}]:{}", host, serv);
      |                                     ^~~~~~

Signed-off-by: Andreas Ziegler <br025@umbiko.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>