package/meson: bump version to 1.11.1
https://mesonbuild.com/Release-notes-for-1-11-0.html

Removed patch which is included in this bump.

Disabled the usage of ccache in mesa3d with BR2_PACKAGE_MESA3D_RUSTICL=y
due to upstream commit:
https://github.com/mesonbuild/meson/commit/aac5f78580a3ea1cf0cae487cb46cab68a048660
(bisected https://github.com/mesonbuild/meson/compare/1.10.1...1.10.2 to
 find the offending commit, the same defconfig works with meson 1.10.1)

Without this change mesa3d configure is broken:

output/build/mesa3d-26.0.3/src/gallium/frontends/rusticl/meson.build:420:27:
 ERROR: No build machine compiler for 'src/gallium/frontends/rusticl/proc/lib.rs'

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Tested-by: Fiona Klute <fiona.klute@gmx.de>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>