package/libnpupnp: needs gcc >= 7
Buildroot commit 2774502344f35b587ea8f1a2f43ec2398c3ebdad bumped the
package from 4.2.2 to 6.2.3. Upstream added the usage of
std::scoped_lock in version 6.2.0:
https://framagit.org/medoc92/npupnp/-/commit/a760b3278aee06408d9f50d0c54942f5ba9df989

causing a build error detected by the Gitlab pipelines for the
bootlin-aarch64-glibc-old defconfig:

../src/inc/upnpapi.h:132:22: error:
 ‘scoped_lock’ is not a member of ‘std’

scoped_lock was introduced in gcc 7.1:
https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017

so we raise the minimum required gcc version accordingly.

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>