package/argp-standalone: bump to version 1.4.1
- Switch site to an up-to-date fork
- Drop first and second patches (not needed since:
  https://github.com/ericonr/argp-standalone/commit/c474ac2af74a8ba336b5480927741c13950ea01b
  https://github.com/ericonr/argp-standalone/commit/80691135993109ec0c8a41327418195fc6d82694
- Drop third patch (not needed since:
  https://github.com/ericonr/argp-standalone/commit/e7ff8d9787d2641e55f6ac4afb777da60ef98043)
- License is LGPL-2.1+ since
  https://github.com/ericonr/argp-standalone/commit/c474ac2af74a8ba336b5480927741c13950ea01b
- README.md can be used as the license file since
  https://github.com/ericonr/argp-standalone/commit/da0206414df4fe55f70b6dfba86ec232acf5d444
- This bump will also fix the following build failure with
  BR2_OPTIMIZE_0 thanks to
  https://github.com/ericonr/argp-standalone/commit/e7ff8d9787d2641e55f6ac4afb777da60ef98043:

  /nvmedata/autobuild/instance-27/output-1/host/lib/gcc/microblaze-buildroot-linux-uclibc/10.3.0/../../../../microblaze-buildroot-linux-uclibc/bin/ld: libargp.a(argp-help.o): in function `indent_to':
  /nvmedata/autobuild/instance-27/output-1/build/argp-standalone-1.3/argp-help.c:930: undefined reference to `argp_fmtstream_point'

Fixes:
 - http://autobuild.buildroot.org/results/8e2cd69356f40bae534847ad58f4aa0dabb4c791

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>