package/python-libusb1: needs python3
python2 support has been dropped since version 1.10.0 and
https://github.com/vpelletier/python-libusb1/commit/69fd5a3ed2f674d412131dfaf24bbc2534f3cf13
resulting in the following build failure since bump to version 2.0.1 in
commit 6703b94f24320316ddfc2a3ec3e40fe3876dc8c8:

Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    from html.parser import HTMLParser
ImportError: No module named html.parser

Fixes:
 - http://autobuild.buildroot.org/results/fe011ccb7eac1be9762919f9feda35114e752d8a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>