package/gtkiostream: add BR2_PACKAGE_GTKIOSTREAM_ARCH_SUPPORTS
gtkiostream only supports little-endian since its addition in commit
fab48302865e5c0c98d91b696bc90e75e38189bb resulting in the following
build failure:

In file included from BitStream.C:23:
../include/BitStream.H:35:2: error: #error "iobitstream not tested on big endian systems"
   35 | #error "iobitstream not tested on big endian systems"
      |  ^~~~~

Fixes: fab48302865e5c0c98d91b696bc90e75e38189bb
 - http://autobuild.buildroot.org/results/aec24d92cc2196596413cf509d686f1f8d1eca95

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>