package/safeclib: fix build with gcc 4.8
Add -std=c99 to fix the following build failure with gcc 4.8 raised
since bump to version 3.7.1 in commit
cc27267ae41bf44276c63b1e86042c4fae4adf50:

In file included from abort_handler_s.c:35:0:
safeclib_private.h:167:18: error: anonymous variadic macros were introduced in C99 [-Werror=variadic-macros]
 #define slprintf(...) fprintf(stderr, __VA_ARGS__)
                  ^

Fixes:
 - http://autobuild.buildroot.org/results/5c3468585942879b47331e05058d25d324c8cc23

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>