package/memcached: fix uclibc build on aarch64
Fix the following uclibc build failure on aarch64:

crc32c.c:277:10: fatal error: sys/auxv.h: No such file or directory
  277 | #include <sys/auxv.h>
      |          ^~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/08591fbf9677ff126492c50c15170c641bcab56a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit 97b533c3c2571eccf501de05b270ff5eec711f0d)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>