package/libcap-ng: bump version to 0.9.3
https://github.com/stevegrubb/libcap-ng/blob/v0.9.3/ChangeLog

The source tarball is not distributed on the project site anymore so we
switch to the github helper and need to enable autoreconf.

Added dependency to BR2_TOOLCHAIN_HAS_SYNC_4 to fix a build error:

/home/bernd/buildroot/test-libcap/bootlin-sparc-uclibc/host/opt/ext-toolchain/bin/../lib/gcc/sparc-buildroot-linux-uclibc/14.3.0/../../../../sparc-buildroot-linux-uclibc/bin/ld:
 ../src/.libs/libcap-ng.so: undefined reference to `__sync_bool_compare_and_swap_4'

due to this upstream commit added in version 0.9.2:
https://github.com/stevegrubb/libcap-ng/commit/ba2e9e03199541b1c07f3e925ffc5b23774bd18f

Added _POST_EXTRACT_HOOKS and dependency to host-pkgconf to fix
autoreconf errors.

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>