package/iproute2: bump to version 6.10
This bump will fix the following build failure with gcc >= 14 thanks to
https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=53a89bfd86fff1a00cc77cabb8457a03eaa3bc7d:

../include/json_print.h: In function 'print_tv':
../include/json_print.h:58:48: error: passing argument 5 of 'print_color_tv' from incompatible pointer type [-Wincompatible-pointer-types]
   58 |                                                value);                  \
      |                                                ^~~~~
      |                                                |
      |                                                const struct timeval *

Fixes:
 - http://autobuild.buildroot.org/results/c47c1e13659e4bfcccd98ebd22949e9dd278079e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 7ecca28e209b811b1ece19f114a2bde4bf5639be)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>