package/php-pecl-dbus: bump version to 0.4.1
For a list of changes, see:
https://github.com/derickr/pecl-dbus/compare/b147624d480c3353e6c700e9a2d0c6f14d853941...0.4.1

Removed patches which are included in this release.

Also, since Buildroot commit [1] (package/php: bump version to 8.4.13)
php-pecl-dbus is failing to build with error:

    /builds/buildroot.org/buildroot/test-output/TestPhpPeclDbus/build/php-pecl-dbus-b147624d480c3353e6c700e9a2d0c6f14d853941/php_dbus.h:52:9: error: implicit declaration of function 'rebuild_object_properties'; did you mean 'rebuild_object_properties_internal'? [-Wimplicit-function-declaration]

This commits fixes the issue.

Fixes:
https://gitlab.com/buildroot.org/buildroot/-/jobs/12184413758

[1] https://gitlab.com/buildroot.org/buildroot/-/commit/a9e5cf6ac2cb7ba62d23c842899b3f7816eca14c

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
[Julien: add commit log info about build failure]
Signed-off-by: Julien Olivain <ju.o@free.fr>