package/expat: disable examples, tests and xmlwf
Disable examples and tests (enabled by default) through
--without-{examples,tests} which are available since version 2.2.7 and
https://github.com/libexpat/libexpat/commit/1fdfd8a1b490f8ac9e7e11896298e41cc210d87d

Also disable xmlwf (a binary that determines if an XML document is
well-formed) through --without-xmlwf which is available since version
2.2.4 and
https://github.com/libexpat/libexpat/commit/9d950527a07783c104aada685384edf3f8f23f8a

This will fix the following build failure on riscv64:

ERROR: reloc type R_RISCV_SET6 unsupported in this context

Fixes:
 - http://autobuild.buildroot.org/results/99890c9c7ebe3266dd533c81352a3cbcf4d3d738

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit dac5873314581786630466741074c1e3af61b2b4)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>