package/uqmi: update patch for fix compile error (gcc false error reporting)
Update the patch to to avoid gcc false error reporting (apply pragma ignored
only for gcc >= 12.x (as the warning '-Wdangling-pointer' was introduced
with gcc-12.x).

Fixes:

  - http://autobuild.buildroot.net/results/df380f921b74527b77290a658de0c57680083afa

  .../build/uqmi-0a19b5b77140465c29e2afa7d611fe93abc9672f/dev.c:213:32: error: unknown option after '#pragma GCC diagnostic' kind [-Werror=pragmas]
    213 | #pragma GCC diagnostic ignored "-Wdangling-pointer"
        |                                ^~~~~~~~~~~~~~~~~~~~

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 6219046db6a434d549706e039f221c46464cee21)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>