package/tvheadend: disable execinfo
Disable execinfo to avoid the following build failure if libexecinfo is
built before tvheadend since the addition of the package in commit
eea8ba446c10701a273432552108d80fb2224ef4:

/home/peko/autobuild/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/i686-buildroot-linux-uclibc/9.3.0/../../../../i686-buildroot-linux-uclibc/bin/ld: /home/peko/autobuild/instance-0/output-1/build/tvheadend-b8710206eb073c72b142bce95846b77a0ffa34a6/build.linux/src/tvhlog.o: in function `tvhlog_backtrace_printf':
/home/peko/autobuild/instance-0/output-1/build/tvheadend-b8710206eb073c72b142bce95846b77a0ffa34a6/src/tvhlog.c:522: undefined reference to `backtrace'

Fixes:
 - http://autobuild.buildroot.org/results/ee9ad2c999b622097fe0f1522e7e32184722e548

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>