package/rtl8723ds: bump to version 2025-12-09
With Kernel >= 6.18 introduced in [1] rtl8723ds fails at build
time with error:

    core/rtw_security.c:2183:13: error: conflicting types for 'sha256_init'; have 'void(struct rtl_sha256_state *)'

Fixes:
https://autobuild.buildroot.org/results/52081e3a500dd2566af145e8c6d793df7f72d025/

[1] https://gitlab.com/buildroot.org/buildroot/-/commit/a06d79862a60d3c8d5ddd6a9ab12b5ccdd91984c

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
[Julien: add details in commit log]
Signed-off-by: Julien Olivain <ju.o@free.fr>