package/openblas: fix build
Buildroot commit b08ac7636dc7b2753592989dc5fe73959e0f6507 bumped the
package to version 0.3.31 and introduced a build error

linktest.c:(.text.startup+0x6f4):
 undefined reference to `openblas_set_threads_callback_function'

which according to https://github.com/OpenMathLib/OpenBLAS/issues/5607
was introduced by upstream commit
https://github.com/OpenMathLib/OpenBLAS/commit/879497990f42e6dcfa370bcbf478cc5674158336
that was first included in version 0.3.31.

This patch adds another upstream commit to fix the problem.

Fixes:
https://autobuild.buildroot.net/results/7d8/7d80a912ddda01acd109786641df02ad826399f6/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Julien Olivain <ju.o@free.fr>