configs/mx6cubox: select BR2_TARGET_UBOOT_NEEDS_OPENSSL
Select BR2_TARGET_UBOOT_NEEDS_OPENSSL to fix the following build
error:

include/image.h:1178:12: fatal error: openssl/evp.h: No such file or directory
 1178 | #  include <openssl/evp.h>
      |            ^~~~~~~~~~~~~~~

Fixes:
- https://gitlab.com/buildroot.org/buildroot/-/jobs/1915006257
Signed-off-by: Fabio Estevam <festevam@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 635f4b8b5a04d0802aa429fb92dbcd757feed66c)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>