package/python-can: add missing setuptools runtime dependency
The commit [1] removed setuptools from runtime dependencies
"Drop spurious setuptools runtime dependency.". Since then
the test TestPythonPy3Can fail with the following error:

  ModuleNotFoundError: No module named 'pkg_resources'

Add back setuptools to provide "pkg_resources".

Fixes
https://gitlab.com/buildroot.org/buildroot/-/jobs/4322819285

[1] 09c966af735ca53b447f52965d123c21e43ae522

Signed-off-by: Romain Naour <romain.naour@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>