package/sedutil: fix build with gcc >= 13
Fix the following build failure with gcc >= 13:

In file included from ./Common/log.h:45,
                 from LinuxPBA/LinuxPBA.cpp:25:
./Common/DtaOptions.h:33:5: error: 'uint8_t' does not name a type
   33 |     uint8_t password;   /**< password supplied */
      |     ^~~~~~~
./Common/DtaOptions.h:1:1: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?

Fixes:
 - http://autobuild.buildroot.org/results/b6feb4fb33d595414b61174deb9867e8c30cd186

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit bdf1506e9664b7b7d2441496192723e26383623d)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>