package/usbguard: fix build with gcc >= 13
Fix the following build failure with gcc >= 13:

In file included from src/Library/Base64.cpp:23:
src/Library/Base64.hpp:34:34: error: 'uint8_t' does not name a type
   34 |   std::string base64Encode(const uint8_t* buffer, size_t buflen);
      |                                  ^~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/1a08823020c37a73f4e4a40f47b02fca3f159748

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 05db019ea6f12c407a1ff7e8a365ba2743668d81)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>