configs/freescale_imx8m[mq]evk*: uboot needs openssl and gnutls
Those defconfigs were recently bumped to NXP BSP lf-6.6.23-2.0.0.

NXP BSP U-Boot version lf-6.6.23-2.0.0 is based on upstream
version 2024.04. This version now requires OpenSSL and GnuTLS for
that configuration.

Those defconfigs are failing in uboot build, with output:

    In file included from tools/imagetool.h:24,
                     from tools/imagetool.c:8:
    include/image.h:1471:12: fatal error: openssl/evp.h: No such file or directory
     1471 | #  include <openssl/evp.h>
          |            ^~~~~~~~~~~~~~~

and:

    tools/mkeficapsule.c:20:10: fatal error: gnutls/gnutls.h: No such file or directory
       20 | #include <gnutls/gnutls.h>
          |          ^~~~~~~~~~~~~~~~~

This commit fixes the issue by adding BR2_TARGET_UBOOT_NEEDS_GNUTLS=y
and BR2_TARGET_UBOOT_NEEDS_OPENSSL=y in those defconfigs.

Signed-off-by: Julien Olivain <ju.o@free.fr>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>