package/hiawatha: add libxcrypt optional dependency
Fix the following build failure raised since bump of glibc to version
2.39 in commit b5680f53d60acf8ff6010082f873438a39bd5d97:

/home/autobuild/autobuild/instance-13/output-1/host/lib/gcc/mips-buildroot-linux-gnu/11.4.0/../../../../mips-buildroot-linux-gnu/bin/ld: CMakeFiles/hiawatha.dir/src/httpauth.c.o: in function `basic_http_authentication':
/home/autobuild/autobuild/instance-13/output-1/build/hiawatha-11.2/src/httpauth.c:334:(.text+0x614): undefined reference to `crypt'

Fixes: b5680f53d60acf8ff6010082f873438a39bd5d97
 - http://autobuild.buildroot.org/results/8054bd47edf613a12b09a9958f78abd5f355f17b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>