package/lsof: fix build failure due to missing BR2_PACKAGE_LIBTIRPC_RPCDB
Package lsof requires libtirpc rpcdb option enabled with non-glibc
toolchains since the bump of libtirpc to version 1.3.7 with buildroot
commit 3f3d6e43de9b4aac7df8545fd811171256f878d3 which includes upstream
commit:
https://git.linux-nfs.org/?p=steved/libtirpc.git;a=commit;h=7cea8ad66aecc21e6caae330b5d31075af399193

Fixes:
https://autobuild.buildroot.net/results/59e/59e0cc2692a8a7d587f5a4da90ec268237141dab/

/home/autobuild/autobuild/instance-10/output-1/host/lib/gcc/arc-buildroot-linux-uclibc/14.2.0/../../../../arc-buildroot-linux-uclibc/bin/ld:
 print.c:(.text+0x166): undefined reference to `getrpcbynumber'

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>