package/python-evdev: bump to version 1.9.0
Since Buildroot commit [1] "package/python-evdev: bump to version
1.8.0", python-evdev is failing to build with error:

    evdev/ecodes.c: In function 'PyInit__ecodes':
    evdev/ecodes.c:65:29: error: 'BUS_AMD_SFH' undeclared (first use in this function)
       65 |     PyModule_AddIntMacro(m, BUS_AMD_SFH);
          |                             ^~~~~~~~~~~
    /home/autobuild/autobuild/instance-8/output-1/build/python3-3.12.8/Include/modsupport.h:61:70: note: in definition of macro 'PyModule_AddIntMacro'
       61 | #define PyModule_AddIntMacro(m, c) PyModule_AddIntConstant((m), #c, (c))
          |                                                                      ^
    ...

Upstream commit [2] included in this version fixes issues when
building wheels.

Fixes:
- https://gitlab.com/buildroot.org/buildroot/-/jobs/9085451384
- https://autobuild.buildroot.org/results/61a3b74e60f2f0f93e312803812ab4d98c492599/
- and many others...

[1] https://gitlab.com/buildroot.org/buildroot/-/commit/455ef44d26f027abc1936ba9041427a4b2e86f42
[2] https://github.com/gvalkov/python-evdev/commit/3ff9816e08be95b331ea9dadc18fc17f1e04e272

Signed-off-by: Vincent Fazio <vfazio@xes-inc.com>
[Julien: reworded the commit log to add extra info]
Signed-off-by: Julien Olivain <ju.o@free.fr>