package/dc3dd: disable on arc
Disable dc3dd on arc like we've done for riscv32 because of the size of
time_t:

In file included from getdate.y:40:
verify.h:132:30: error: negative width in bit-field 'verify_error_if_negative_size__'
  132 |       (struct { unsigned int verify_error_if_negative_size__: (R) ? 1 : -1; }))
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
verify.h:138:61: note: in expansion of macro 'verify_true'
  138 | # define verify(R) extern int (* verify_function__ (void)) [verify_true (R)]
      |                                                             ^~~~~~~~~~~
getdate.y:116:1: note: in expansion of macro 'verify'
  116 | verify (LONG_MIN <= TYPE_MINIMUM (time_t) && TYPE_MAXIMUM (time_t) <= LONG_MAX);
      | ^~~~~~

Fixes:
http://autobuild.buildroot.net/results/9e2/9e2a8f0548ecb5ce9539eda007cd886ddea7dc0a/

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit fa937f2756ab1f683df65b3445722cc4bb11f144)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>