package/python-tftpy: fix legal info
Fix the following build failure raised since the addition of the package
in commit 8dd5390be6b210eaac1bf02af2fea84d4c87dcd1:

>>> python-tftpy 0.8.2 Collecting legal info
ERROR: No hash found for LICENSE.txt

Fixes:
 - http://autobuild.buildroot.org/results/9e12e0cd81bdf1a09884a340ca809c194e4dba9b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>