package/sane-backends: bump version to 1.4.0
https://gitlab.com/sane-project/backends/-/releases/1.2.1
https://gitlab.com/sane-project/backends/-/releases/1.3.1
https://gitlab.com/sane-project/backends/-/releases/1.4.0

Removed patch which is included in this release.

Added sha256 tarball provided by upstream.

The build of the umax_pp backend fails for microblazeel/mipsel/powerpc
when used with uClibc (detected by the Gitlab pipelines):

umax_pp_low.c: In function ‘sanei_umax_pp_initPort’:
umax_pp_low.c:835:7: error: implicit declaration of function 'iopl'
 [-Wimplicit-function-declaration]
  835 |   if (iopl (3) != 0)

Fix this by disabling that backend under those conditions. The proper
way to do that would be to patch configure.ac to add an option to
exclude specific backends, and then give the corresponding CONF_OPT.
However, that's quite a complex patch for such a corner case, so instead
simply patch configure to remove the umax_pp backend from ALL_BACKENDS.
We only want to do this conditionally, so do it with sed in a post-patch
hook rather than with a patch.

Fixes:
https://autobuild.buildroot.net/results/364/364bfa29f9df16079dd10be628ddefcf80f581f9/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
[Arnout: do it in a post-patch instead of post-extract hook]
Signed-off-by: Arnout Vandecappelle <arnout@rnout.be>