package/luajit: disable on armeb
armeb has never been supported by luajit since its addition in version
2.0.0 by
https://github.com/LuaJIT/LuaJIT/commit/ed6c895ae56288b6982d1651c4ea638452c9e99b:

lj_arch.h:473:2: error: #error "No support for big-endian ARM"
  473 | #error "No support for big-endian ARM"
      |  ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/3751096941ae16184b835fd6879b4904f28c6432

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit dbbc25ff762348a4c32e7c5bd28a3fe3c858d9b3)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>