package/ivi-homescreen: needs gcc >= 8
ivi-homescreen needs C++17 filesystem resulting in the following build
failure with gcc < 8 since its addition in commit
9d8497e79de3ced144877ba6ee38cc5b7181aaeb:

In file included from /home/buildroot/instance-0/output-1/build/ivi-homescreen-5ab78a19e95c88cc5d6b173ab1260a211e78cf0a/third_party/flutter/shell/platform/common/path_utils.cc:5:0:
/home/buildroot/instance-0/output-1/build/ivi-homescreen-5ab78a19e95c88cc5d6b173ab1260a211e78cf0a/third_party/./flutter/shell/platform/common/path_utils.h:8:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~

Fixes: 9d8497e79de3ced144877ba6ee38cc5b7181aaeb
 - http://autobuild.buildroot.org/results/a5e88d5a4264a6165be31a99f1c123af53fa382e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit 898cf04e47b5d292afc1ab1e67f59b10b8637b12)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>