package/netsurf: force libopenssl
netsurf raises the following build failure since bump of libressl to
version 3.5.2 in commit 8b216927db080b38fdbf1f8b025b6f90a89d4bc2:

content/fetchers/about.c: In function 'ns_X509_get_signature_nid':
content/fetchers/about.c:548:25: error: dereferencing pointer to incomplete type 'X509 {aka struct x509_st}'
  return OBJ_obj2nid(cert->cert_info->key->algor->algorithm);
                         ^~

Fixes:
 - http://autobuild.buildroot.org/results/c225aaac31398ba495921bd4b85e588199822561

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>